import {readTestWallet,testWalletAction} from '../../lib/test-wallet';
import {messageAction,readMessageTools,transcriptHash} from '../../lib/message-actions';
import {readLibrary,personaSnapshot,readSessionDetails} from '../../lib/library';
import {libraryAction} from '../../lib/library-actions';
import {applyTracker} from '../../lib/tracker-actions';
import {readStatus} from '../../lib/status';
import {normalizeStatusTemplate,cleanStatusData} from '../../lib/status-fields';
import { readMemory, scheduleSummary, compileProviderContext } from '../../lib/memory';
import { getChatGPTUser } from '../../chatgpt-auth';
import { db } from '../../lib/db';
import { covers, acceptedCovers, normalizedWork, publicWork, defaultRules, workRating, type Work } from '../../lib/data';
import { sampleChatProvider } from '../../lib/providers';
import { readWork, adultDeclared, mayChat, bucket, parseCondition, assetMetadata, progressFor, awardAssets, collections } from '../../lib/collectibles';
export const dynamic='force-dynamic';
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const err=(message:string,status=400)=>response({error:message},status);
function clean(v:unknown,max:number){return typeof v==='string'?v.trim().slice(0,max):''}
async function state(owner:string){const [w,s,a,b,l,adult,activity,library]=await Promise.all([db().prepare('SELECT id,data,revision,archived,updated FROM works WHERE owner=? ORDER BY updated DESC').bind(owner).all<any>(),db().prepare("SELECT s.id,s.work_id,s.snapshot,s.opening,s.created,s.archived,d.title,d.persona_snapshot,d.provenance,COALESCE((SELECT MAX(created) FROM messages WHERE session_id=s.id AND owner=s.owner),s.created) AS last_active,(SELECT content FROM messages WHERE session_id=s.id AND owner=s.owner ORDER BY created DESC,id DESC LIMIT 1) AS last_message,(SELECT COUNT(*) FROM messages WHERE session_id=s.id AND owner=s.owner AND role='user') AS turns FROM sessions s LEFT JOIN session_details d ON d.session_id=s.id AND d.owner=s.owner WHERE s.owner=? ORDER BY last_active DESC").bind(owner).all<any>(),collections(owner),db().prepare('SELECT 120+COALESCE(SUM(delta),0) AS balance FROM ledger WHERE owner=?').bind(owner).first<any>(),db().prepare('SELECT * FROM ledger WHERE owner=? ORDER BY created DESC').bind(owner).all(),adultDeclared(owner),db().prepare("SELECT s.work_id,COUNT(m.id) AS turns,MAX(m.created) AS last_played FROM sessions s JOIN messages m ON m.session_id=s.id AND m.owner=s.owner AND m.role='user' WHERE s.owner=? AND s.archived=0 AND EXISTS (SELECT 1 FROM messages a WHERE a.id=m.id||':reply' AND a.owner=m.owner) GROUP BY s.work_id").bind(owner).all<any>(),readLibrary(owner)]);return {...library,works:w.results.map(r=>({...publicWork(JSON.parse(r.data)),id:r.id,revision:r.revision,archived:!!r.archived,updated:r.updated})),sessions:s.results.map(({persona_snapshot,provenance,...r})=>({...r,archived:!!r.archived,personaSnapshot:JSON.parse(persona_snapshot||'{}'),provenance:JSON.parse(provenance||'{}'),snapshot:publicWork(JSON.parse(r.snapshot))})),assets:a,balance:b.balance,ledger:l.results,adultDeclared:adult,activity:activity.results};}
async function ownWork(owner:string,workId:string){const row=await db().prepare('SELECT data,revision FROM works WHERE id=? AND owner=? AND archived=0').bind(workId,owner).first<any>();return row?{...normalizedWork(JSON.parse(row.data)),revision:row.revision}:null;}
export async function GET(req:Request){try{const u=await getChatGPTUser();if(!u)return err('로그인이 필요합니다.',401);const url=new URL(req.url),sessionId=url.searchParams.get('session'),workId=url.searchParams.get('assetsFor'),editId=url.searchParams.get('editWork');if(url.searchParams.has('wallet'))return response(await readTestWallet(u.userId));if(url.searchParams.has('library'))return response(await readLibrary(u.userId));if(editId){const work=await ownWork(u.userId,editId);if(!work)return err('작품을 찾을 수 없습니다.',404);return response({work});}if(workId){const w=await readWork(u.userId,workId);if(!w)return err('작품을 찾을 수 없습니다.',404);return response({assets:await assetMetadata(u.userId,workId,!!await ownWork(u.userId,workId))});}if(sessionId){const s=await db().prepare('SELECT * FROM sessions WHERE id=? AND owner=? AND archived=0').bind(sessionId,u.userId).first<any>();if(!s)return err('대화를 찾을 수 없습니다.',404);const snapshot=normalizedWork(JSON.parse(s.snapshot));const current=await readWork(u.userId,s.work_id);if(!await mayChat(u.userId,current||snapshot))return err('19+ 작품은 만 19세 이상 이용 확인 후 샘플 대화를 열 수 있습니다. 실제 본인·나이 인증은 연결되지 않았습니다.',403);await awardAssets(u.userId,s);const m=await db().prepare('SELECT * FROM messages WHERE session_id=? AND owner=? ORDER BY created,id').bind(sessionId,u.userId).all();return response({session:{id:s.id,work_id:s.work_id,opening:s.opening,created:s.created,...await readSessionDetails(u.userId,s.id),snapshot:publicWork(snapshot)},messages:m.results,sourceHash:await transcriptHash(m.results),...await readMessageTools(u.userId,s.id),unlocks:await progressFor(u.userId,s),memory:await readMemory(u.userId,s.id),status:await readStatus(u.userId,s.id)});}return response(await state(u.userId));}catch(e){console.error(e);return err('불러오지 못했습니다. 새로고침해 다시 시도해 주세요.',503);}}
export async function POST(req:Request){try{const u=await getChatGPTUser();if(!u)return err('로그인이 필요합니다.',401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return err('요청 출처를 확인할 수 없습니다.',403);const b=await req.json() as any;const owner=u.userId;
const walletResult=await testWalletAction(owner,b);if(walletResult)return walletResult;
const messageResult=await messageAction(owner,b);if(messageResult)return messageResult;
if(b.action==='applyTracker')return applyTracker(owner,b);
const libraryResult=await libraryAction(owner,b);if(libraryResult)return libraryResult;
if(b.action==='declareAdult'){if(b.confirm!==true)return err('만 19세 이상임을 직접 확인해 주세요.');await db().prepare('INSERT OR IGNORE INTO age_declarations(owner,declared_at) VALUES(?,?)').bind(owner,now()).run();return response({adultDeclared:true});}
if(b.action==='saveWork'){
 const x=b.work as Work;if(!x)return err('작품 정보가 필요합니다.');const isDraft=x.status!=='catalog';if(!isDraft&&!clean(x.title,80))return err('작품 제목을 입력해 주세요.');
 if(!Array.isArray(x.characters)||x.characters.length<1||x.characters.length>6)return err('등장인물은 1~6명으로 설정해 주세요.');
 if(x.characters.some(c=>(!isDraft&&!clean(c.name,40))||typeof c.age!=='number'||!Number.isInteger(c.age)||c.age<19||c.age>999))return err('등장인물 이름과 성인 나이(19세 이상)를 입력해 주세요.');
 if(!Array.isArray(x.openings)||!x.openings.length||x.openings.length>4||x.openings.some(o=>!isDraft&&!clean(o.text,4000)))return err('첫 장면을 1~4개 작성해 주세요.');
 const openingTitles=x.openings.map(o=>clean(o.title,60)||'첫 만남');if(new Set(openingTitles).size!==openingTitles.length)return err('첫 장면 이름을 서로 다르게 입력해 주세요. 이어하기와 에셋 조건에 사용됩니다.');
 const wid=clean(x.id,80)||id();if(wid.startsWith('sample-'))return err('예시 작품은 복제한 후 수정할 수 있습니다.');
 const found=await db().prepare('SELECT owner,data,revision FROM works WHERE id=?').bind(wid).first<any>();if(found&&found.owner!==owner)return err('수정 권한이 없습니다.',403);
 if(found&&found.revision!==x.revision)return err('다른 창에서 작품이 변경됐어요. 내 작품에서 다시 열어 주세요. 현재 입력은 남아 있습니다.',409);
 const previous=found?normalizedWork(JSON.parse(found.data)):null;
 const characters=x.characters.map((c,i)=>({id:previous?.characters.some(p=>p.id===c.id)?c.id:`${wid}-character-${crypto.randomUUID()}`,name:clean(c.name,40),age:c.age,...(c.portrait&&acceptedCovers.includes(c.portrait)?{portrait:c.portrait}:{}),role:clean(c.role,100),personality:clean(c.personality,2000)}));
 if(new Set(characters.map(c=>c.id)).size!==characters.length)return err('등장인물 ID가 중복되었습니다.');
 const rules=x.responseRules||defaultRules();const work:Work={id:wid,authorName:previous?.authorName||clean(u.fullName,60)||'나',revision:found?found.revision+1:0,trackerName:clean(x.trackerName,60)||'작품 기본 트래커',statusTemplate:normalizeStatusTemplate(x.statusTemplate),responseRules:{ooc:clean(rules.ooc,4000),style:clean(rules.style,2000),perspective:clean(rules.perspective,1000),length:['short','balanced','long'].includes(rules.length)?rules.length:'balanced'},rating:workRating({...x,id:wid}),created:previous?.created||now(),...(['남성향','여성향','공통'].includes(x.audience||'')?{audience:x.audience}:{}),...(Array.isArray(x.keywords)?{keywords:x.keywords.slice(0,3).map(k=>clean(k,30))}:{}),title:clean(x.title,80)||'제목 없는 작품',tag:clean(x.tag,30),hook:clean(x.hook,80),desc:clean(x.desc,220),world:clean(x.world,6000),secret:clean(x.secret,6000),characters,openings:x.openings.map(o=>({title:clean(o.title,60)||'첫 만남',text:clean(o.text,4000),suggestions:Array.isArray(o.suggestions)?o.suggestions.slice(0,3).map(z=>clean(z,120)):[]})),cover:acceptedCovers.includes(x.cover)?x.cover:covers[1],status:x.status==='catalog'?'catalog':'draft'};
 const saved=await db().batch([db().prepare('INSERT INTO works(id,owner,data,revision,updated) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,revision=works.revision+1,updated=excluded.updated WHERE works.owner=excluded.owner AND works.revision=?').bind(wid,owner,JSON.stringify(work),work.revision,now(),x.revision??0),db().prepare('UPDATE collectible_assets SET rating=? WHERE work_id=? AND owner=? AND changes()=1 AND EXISTS(SELECT 1 FROM works WHERE id=? AND owner=? AND revision=?)').bind(work.rating,wid,owner,wid,owner,work.revision)]);if(!saved[0].meta.changes)return err('다른 창에서 작품이 변경됐어요. 다시 열어 확인해 주세요.',409);return response({work,...await state(owner)});
}
if(b.action==='archiveWork'||b.action==='restoreWork'){const r=await db().prepare('UPDATE works SET archived=?,updated=? WHERE id=? AND owner=?').bind(b.action==='archiveWork'?1:0,now(),b.id,owner).run();if(!r.meta.changes)return err('작품을 찾을 수 없습니다.',404);return response(await state(owner));}
if(b.action==='saveCollectible'){
 const w=await ownWork(owner,clean(b.workId,80));if(!w)return err('내 작품에서만 에셋을 편집할 수 있습니다.',403);
 const character=w.characters.find(c=>c.id===b.characterId),condition=parseCondition(b.condition,w),title=clean(b.title,100);if(!character||!condition||!title)return err('캐릭터, 에셋 이름과 해금 조건을 확인해 주세요.');
 if(b.id){const r=await db().prepare('UPDATE collectible_assets SET title=?,condition=?,updated=? WHERE id=? AND owner=? AND work_id=? AND character_id=? AND active=1').bind(title,JSON.stringify(condition),now(),b.id,owner,w.id,character.id).run();if(!r.meta.changes)return err('수정할 에셋을 찾을 수 없습니다.',404);return response({assets:await assetMetadata(owner,w.id,true)});}
 const requestId=clean(b.requestId,80);if(!requestId)return err('요청 ID가 필요합니다.');const aid=owner+':'+requestId;const existing=await db().prepare('SELECT work_id FROM collectible_assets WHERE id=? AND owner=?').bind(aid,owner).first<any>();if(existing){if(existing.work_id!==w.id)return err('다른 작품의 요청 ID입니다.',409);return response({assets:await assetMetadata(owner,w.id,true)});}
 const count=await db().prepare('SELECT COUNT(*) AS n FROM collectible_assets WHERE owner=? AND work_id=? AND active=1').bind(owner,w.id).first<any>();if(count.n>=30)return err('작품당 최대 30개의 에셋을 등록할 수 있습니다.');
 const match=typeof b.file==='string'&&b.file.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match||match[2].length>2800000)return err('2 MB 이하 PNG, JPEG, WebP 파일을 선택해 주세요.');
 let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));}catch{return err('이미지 파일을 읽지 못했습니다.');}
 if(bytes.length>2*1024*1024||bytes.length<12)return err('2 MB 이하의 이미지 파일이 필요합니다.');
 const isPNG=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const isJPEG=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const isWebP=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!(match[1]==='png'&&isPNG||match[1]==='jpeg'&&isJPEG||match[1]==='webp'&&isWebP))return err('파일 형식이 올바르지 않습니다.');
 
 const key=`collectibles/${crypto.randomUUID()}`,mime='image/'+match[1];await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});try{const inserted=await db().prepare('INSERT OR IGNORE INTO collectible_assets(id,owner,work_id,character_id,character_name,title,condition,storage_key,mime,rating,created,updated) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM collectible_assets WHERE owner=? AND work_id=? AND active=1)<30').bind(aid,owner,w.id,character.id,character.name,title,JSON.stringify(condition),key,mime,workRating(w),now(),now(),owner,w.id).run();if(!inserted.meta.changes){await bucket().delete(key);const saved=await db().prepare('SELECT work_id FROM collectible_assets WHERE id=? AND owner=?').bind(aid,owner).first<any>();if(!saved)return err('작품당 최대 30개의 에셋을 등록할 수 있습니다.');if(saved.work_id!==w.id)return err('다른 작품의 요청 ID입니다.',409);}}catch(e){await bucket().delete(key);throw e;}return response({assets:await assetMetadata(owner,w.id,true)});
}
if(b.action==='archiveCollectible'){const r=await db().prepare('UPDATE collectible_assets SET active=0,updated=? WHERE id=? AND owner=?').bind(now(),b.id,owner).run();if(!r.meta.changes)return err('에셋을 찾을 수 없습니다.',404);return response({ok:true});}
if(b.action==='startChat'){
 const request=clean(b.requestId,80);if(request&&!/^[A-Za-z0-9_-]{1,80}$/.test(request))return err('시작 요청을 다시 열어 주세요.');
 const requestPayload=JSON.stringify({workId:clean(b.workId,80),opening:Number.isInteger(b.opening)?b.opening:0,personaId:clean(b.personaId,80),title:clean(b.title,80),sourceSessionId:clean(b.sourceSessionId,80)});
 const digest=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),v=>v.toString(16).padStart(2,'0')).join('');
 const sid=request?await digest(owner+'|start|'+request):id(),fingerprint=await digest(requestPayload);
 const prior=await db().prepare('SELECT s.id,s.work_id,s.snapshot,d.provenance FROM sessions s JOIN session_details d ON d.session_id=s.id AND d.owner=s.owner WHERE s.id=? AND s.owner=?').bind(sid,owner).first<any>();
 if(prior){if(JSON.parse(prior.provenance||'{}').startRequestHash!==fingerprint)return err('이 시작 요청의 내용이 바뀌었어요. 새 대화 시작을 다시 열어 주세요.',409);if(!await mayChat(owner,await readWork(owner,prior.work_id)||normalizedWork(JSON.parse(prior.snapshot))))return err('19+ 이용 확인이 필요합니다.',403);return response({id:sid});}
 let work=await readWork(owner,clean(b.workId,80));if(b.sourceSessionId){const source=await db().prepare('SELECT snapshot FROM sessions WHERE id=? AND owner=?').bind(b.sourceSessionId,owner).first<any>();if(!source)return err('원본 대화를 찾을 수 없습니다.',404);work=normalizedWork(JSON.parse(source.snapshot));}if(!work)return err('작품을 찾을 수 없습니다.',404);const current=await readWork(owner,work.id);if(!await mayChat(owner,current||work))return err('19+ 작품은 만 19세 이상 이용 확인이 필요합니다. 실제 본인·나이 인증은 연결되지 않았습니다.',403);
 const oi=Number.isInteger(b.opening)?b.opening:0,opening=work.openings[oi];if(!opening||!opening.text.trim())return err('내 작품에서 첫 장면을 작성하고 저장해 주세요.');let persona:any;try{persona=await personaSnapshot(owner,b.personaId)}catch(e:any){return err(e.message,409)}const date=now();
 await db().batch([db().prepare('INSERT OR IGNORE INTO sessions(id,owner,work_id,snapshot,opening,created) VALUES(?,?,?,?,?,?)').bind(sid,owner,work.id,JSON.stringify(work),opening.title,date),db().prepare('INSERT OR IGNORE INTO session_details(session_id,owner,title,persona_snapshot,provenance,updated) SELECT ?,?,?,?,?,? WHERE changes()=1').bind(sid,owner,clean(b.title,80),JSON.stringify(persona),JSON.stringify({startRequestHash:fingerprint,openingIndex:oi}),date),db().prepare("INSERT OR IGNORE INTO messages(id,owner,session_id,role,content,created) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM session_details WHERE session_id=? AND owner=? AND json_extract(provenance,'$.startRequestHash')=?)").bind(sid+':opening',owner,sid,'assistant',opening.text,date,sid,owner,fingerprint),db().prepare("INSERT OR IGNORE INTO session_memory(session_id,owner,persona,updated) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM session_details WHERE session_id=? AND owner=? AND json_extract(provenance,'$.startRequestHash')=?)").bind(sid,owner,persona.content||'',date,sid,owner,fingerprint)]);
 const saved=await db().prepare('SELECT provenance FROM session_details WHERE session_id=? AND owner=?').bind(sid,owner).first<any>();if(!saved||JSON.parse(saved.provenance).startRequestHash!==fingerprint)return err('시작 요청이 다른 창에서 변경됐어요. 새 대화 시작을 다시 열어 주세요.',409);
 await awardAssets(owner,{id:sid,work_id:work.id,opening:opening.title});return response({id:sid});
}
if(b.action==='message'){const content=clean(b.content,2000);if(!content)return err('메시지를 입력해 주세요.');const sid=clean(b.sessionId,80);const s=await db().prepare('SELECT * FROM sessions WHERE id=? AND owner=? AND archived=0').bind(sid,owner).first<any>();if(!s)return err('대화를 찾을 수 없습니다.',404);const work=normalizedWork(JSON.parse(s.snapshot));const current=await readWork(owner,s.work_id);if(!await mayChat(owner,current||work))return err('19+ 이용 확인이 필요합니다.',403);const count=await db().prepare("SELECT COUNT(*) AS n FROM messages WHERE session_id=? AND owner=? AND role='user'").bind(sid,owner).first<any>();const context=await compileProviderContext(owner,sid,work);const reply=await sampleChatProvider.reply({work,turn:count.n,message:content,context});const latest=await db().prepare('SELECT MAX(created) AS created FROM messages WHERE session_id=? AND owner=?').bind(sid,owner).first<any>();const time=Math.max(Date.now(),(Date.parse(latest?.created)||0)+1),requestId=clean(b.requestId,80);if(!/^[A-Za-z0-9_-]{1,80}$/.test(requestId))return err('요청 ID 형식이 올바르지 않습니다.');const mid=owner+':'+sid+':'+requestId;await db().batch([db().prepare('INSERT OR IGNORE INTO messages(id,owner,session_id,role,content,created) VALUES(?,?,?,?,?,?)').bind(mid,owner,sid,'user',content,new Date(time).toISOString()),db().prepare('INSERT OR IGNORE INTO messages(id,owner,session_id,role,content,created) VALUES(?,?,?,?,?,?)').bind(mid+':reply',owner,sid,'assistant',reply,new Date(time+1).toISOString())]);await scheduleSummary(owner,sid);return response({ok:true,earned:await awardAssets(owner,s)});}
if(b.action==='saveStatus'){const sid=clean(b.sessionId,80);const session=await db().prepare('SELECT id FROM sessions WHERE id=? AND owner=? AND archived=0').bind(sid,owner).first();if(!session)return err('대화를 찾을 수 없습니다.',404);const existing=await readStatus(owner,sid);if(existing.revision!==b.revision)return err('상태가 다른 창에서 바뀌었어요. 다시 열어 주세요.',409);const r=await db().prepare('INSERT INTO session_status(session_id,owner,data,revision,updated) VALUES(?,?,?,1,?) ON CONFLICT(session_id) DO UPDATE SET data=excluded.data,revision=session_status.revision+1,updated=excluded.updated WHERE session_status.owner=excluded.owner AND session_status.revision=?').bind(sid,owner,JSON.stringify({values:cleanStatusData(b.data),template:b.template?normalizeStatusTemplate(b.template):existing.template||null,tracker:b.template&&JSON.stringify(normalizeStatusTemplate(b.template))!==JSON.stringify(existing.template)?{...existing.tracker,source:'custom',name:'직접 구성한 트래커'}:existing.tracker}),now(),b.revision).run();if(!r.meta.changes)return err('상태가 변경됐어요. 다시 열어 주세요.',409);return response({status:await readStatus(owner,sid)});}
if(b.action==='saveMemory'||b.action==='saveSummary'){
 const sid=clean(b.sessionId,80);const session=await db().prepare('SELECT id FROM sessions WHERE id=? AND owner=? AND archived=0').bind(sid,owner).first();if(!session)return err('대화를 찾을 수 없습니다.',404);
 if(b.action==='saveMemory'){const manual=clean(b.manual,6000),notes=clean(b.userNotes,3000),persona=clean(b.persona,2000),interval=Number(b.interval);if(!Number.isInteger(interval)||interval<2||interval>100)return err('요약 간격은 2~100턴으로 설정해 주세요.');
 const existing=await db().prepare('SELECT revision,include_book FROM session_memory WHERE owner=? AND session_id=?').bind(owner,sid).first<any>();if((existing?.revision||0)!==b.revision)return err('다른 창에서 기억이 변경됐어요. 다시 열어 확인해 주세요.',409);
 const result=await db().prepare('INSERT INTO session_memory(session_id,owner,manual,user_notes,persona,interval,enabled,include_book,revision,updated) VALUES(?,?,?,?,?,?,?,?,1,?) ON CONFLICT(session_id) DO UPDATE SET manual=excluded.manual,user_notes=excluded.user_notes,persona=excluded.persona,interval=excluded.interval,enabled=excluded.enabled,include_book=excluded.include_book,revision=session_memory.revision+1,updated=excluded.updated WHERE session_memory.owner=excluded.owner AND session_memory.revision=?').bind(sid,owner,manual,notes,persona,interval,b.enabled?1:0,typeof b.includeBook==='boolean'?(b.includeBook?1:0):(existing?.include_book??1),now(),b.revision).run();if(!result.meta.changes)return err('기억이 변경됐어요. 다시 열어 확인해 주세요.',409);await scheduleSummary(owner,sid);
 }else{const result=await db().prepare("UPDATE memory_summaries SET content=?,status='manual',pinned=?,revision=revision+1,updated=? WHERE id=? AND owner=? AND session_id=? AND revision=?").bind(clean(b.content,4000),b.pinned?1:0,now(),b.id,owner,sid,b.revision).run();if(!result.meta.changes)return err('요약이 변경되었거나 찾을 수 없습니다. 다시 열어 확인해 주세요.',409);}
 return response({memory:await readMemory(owner,sid)});
}
if(b.action==='archiveSession'||b.action==='restoreSession'){const changed=await db().prepare('UPDATE sessions SET archived=? WHERE id=? AND owner=?').bind(b.action==='archiveSession'?1:0,b.id,owner).run();if(!changed.meta.changes)return err('대화를 찾을 수 없습니다.',404);return response(await state(owner));}
if(b.action==='generate')return err('실제 AI 생성은 아직 연결되지 않았습니다. 크레딧은 차감되지 않았습니다.',503);
if(b.action==='demoAsset')return err('샘플 제작은 종료되었습니다. 기존 기록은 보존되며 수집함에는 표시되지 않습니다.',410);
return err('지원하지 않는 요청입니다.');}catch(e){console.error(e);return err('저장하지 못했습니다. 입력 내용은 유지됩니다. 다시 시도해 주세요.',503);}}
