import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const works=sqliteTable('works',{id:text('id').primaryKey(),owner:text('owner').notNull(),data:text('data').notNull(),revision:integer('revision').notNull().default(0),archived:integer('archived').notNull().default(0),updated:text('updated').notNull()},t=>[index('works_owner').on(t.owner,t.archived)]);
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),owner:text('owner').notNull(),workId:text('work_id').notNull(),snapshot:text('snapshot').notNull(),opening:text('opening').notNull(),archived:integer('archived').notNull().default(0),created:text('created').notNull()},t=>[index('sessions_owner').on(t.owner,t.archived)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),owner:text('owner').notNull(),sessionId:text('session_id').notNull(),role:text('role').notNull(),content:text('content').notNull(),revision:integer('revision').notNull().default(0),created:text('created').notNull()},t=>[index('messages_session').on(t.owner,t.sessionId,t.created)]);
export const assets=sqliteTable('assets',{id:text('id').primaryKey(),owner:text('owner').notNull(),requestId:text('request_id').notNull(),prompt:text('prompt').notNull(),ratio:text('ratio').notNull(),image:text('image').notNull(),cost:integer('cost').notNull(),count:integer('count').notNull(),created:text('created').notNull()},t=>[uniqueIndex('asset_request').on(t.owner,t.requestId),index('assets_owner').on(t.owner)]);
export const ledger=sqliteTable('ledger',{id:text('id').primaryKey(),owner:text('owner').notNull(),assetId:text('asset_id').notNull(),delta:integer('delta').notNull(),created:text('created').notNull()},t=>[uniqueIndex('ledger_asset').on(t.assetId),index('ledger_owner').on(t.owner)]);
export const collectibleAssets=sqliteTable('collectible_assets',{id:text('id').primaryKey(),owner:text('owner').notNull(),workId:text('work_id').notNull(),characterId:text('character_id').notNull(),characterName:text('character_name').notNull(),title:text('title').notNull(),condition:text('condition').notNull(),storageKey:text('storage_key').notNull(),mime:text('mime').notNull(),rating:text('rating').notNull().default('19+'),active:integer('active').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('collectible_work').on(t.owner,t.workId,t.active)]);
export const collectionGrants=sqliteTable('collection_grants',{id:text('id').primaryKey(),owner:text('owner').notNull(),assetId:text('asset_id').notNull(),workId:text('work_id').notNull(),characterId:text('character_id').notNull(),sessionId:text('session_id').notNull(),created:text('created').notNull()},t=>[uniqueIndex('collection_unique').on(t.owner,t.assetId),index('collection_owner').on(t.owner)]);
export const ageDeclarations=sqliteTable('age_declarations',{owner:text('owner').primaryKey(),declaredAt:text('declared_at').notNull()});
export const sessionMemory=sqliteTable('session_memory',{sessionId:text('session_id').primaryKey(),owner:text('owner').notNull(),manual:text('manual').notNull().default(''),userNotes:text('user_notes').notNull().default(''),persona:text('persona').notNull().default(''),interval:integer('interval').notNull().default(10),enabled:integer('enabled').notNull().default(1),includeBook:integer('include_book').notNull().default(1),revision:integer('revision').notNull().default(0),updated:text('updated').notNull()},t=>[index('memory_owner').on(t.owner)]);
export const memorySummaries=sqliteTable('memory_summaries',{id:text('id').primaryKey(),owner:text('owner').notNull(),sessionId:text('session_id').notNull(),fromTurn:integer('from_turn').notNull(),toTurn:integer('to_turn').notNull(),content:text('content').notNull().default(''),status:text('status').notNull().default('provider_required'),pinned:integer('pinned').notNull().default(0),revision:integer('revision').notNull().default(0),created:text('created').notNull(),updated:text('updated').notNull()},t=>[uniqueIndex('memory_range').on(t.owner,t.sessionId,t.fromTurn,t.toTurn),index('summary_owner').on(t.owner,t.sessionId)]);
export const sessionStatus=sqliteTable('session_status',{sessionId:text('session_id').primaryKey(),owner:text('owner').notNull(),data:text('data').notNull().default('{}'),revision:integer('revision').notNull().default(0),updated:text('updated').notNull()},t=>[index('status_owner').on(t.owner)]);

export const personas=sqliteTable('personas',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),content:text('content').notNull(),revision:integer('revision').notNull().default(0),archived:integer('archived').notNull().default(0),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('personas_owner').on(t.owner,t.archived)]);
export const statusTemplates=sqliteTable('status_templates',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),fields:text('fields').notNull(),authorName:text('author_name').notNull().default('익명 제작자'),visibility:text('visibility').notNull().default('private'),sourceId:text('source_id'),revision:integer('revision').notNull().default(0),archived:integer('archived').notNull().default(0),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('templates_owner').on(t.owner,t.archived),index('templates_gallery').on(t.visibility,t.archived)]);
export const templateImports=sqliteTable('template_imports',{owner:text('owner').notNull(),sourceId:text('source_id').notNull(),templateId:text('template_id').notNull()},t=>[uniqueIndex('template_import_once').on(t.owner,t.sourceId)]);
export const sessionDetails=sqliteTable('session_details',{sessionId:text('session_id').primaryKey(),owner:text('owner').notNull(),title:text('title').notNull().default(''),personaSnapshot:text('persona_snapshot').notNull().default('{}'),provenance:text('provenance').notNull().default('{}'),updated:text('updated').notNull()},t=>[index('session_details_owner').on(t.owner)]);

export const messageRevisions=sqliteTable('message_revisions',{id:text('id').primaryKey(),owner:text('owner').notNull(),sessionId:text('session_id').notNull(),messageId:text('message_id').notNull(),requestId:text('request_id').notNull(),captureKey:text('capture_key').notNull(),revision:integer('revision').notNull(),previousContent:text('previous_content').notNull(),content:text('content').notNull(),created:text('created').notNull()},t=>[uniqueIndex('message_edit_request').on(t.owner,t.requestId),uniqueIndex('message_edit_version').on(t.messageId,t.revision),index('message_revision_owner').on(t.owner,t.sessionId)]);
export const messageBookmarks=sqliteTable('message_bookmarks',{messageId:text('message_id').primaryKey(),owner:text('owner').notNull(),sessionId:text('session_id').notNull(),label:text('label').notNull(),active:integer('active').notNull().default(1),revision:integer('revision').notNull().default(0),requestId:text('request_id').notNull(),updated:text('updated').notNull()},t=>[index('bookmark_owner').on(t.owner,t.sessionId)]);

export const testPurchases=sqliteTable('test_purchases',{id:text('id').primaryKey(),owner:text('owner').notNull(),requestId:text('request_id').notNull(),packId:text('pack_id').notNull(),units:integer('units').notNull(),acknowledged:integer('acknowledged').notNull().default(0),created:text('created').notNull()},t=>[uniqueIndex('test_purchase_request').on(t.owner,t.requestId),index('test_purchase_owner').on(t.owner,t.created)]);
