'use client';
import {useState,useCallback} from 'react';
import ReaderLibrary from './reader-library';
export default function AccountSettings({data,onChange,onError,onNotice,onDirtyChange,onNavigate,font,setFont,art,setArt}:{data:any;onChange:(d:any)=>void;onError:(s:string)=>void;onNotice:(s:string)=>void;onDirtyChange:(b:boolean)=>void;onNavigate:(v:'chats'|'studio')=>void;font:number;setFont:(n:number)=>void;art:boolean;setArt:(b:boolean)=>void}){
 const [section,setSection]=useState('library'),[dirty,setDirty]=useState(false);
 const reportDirty=useCallback((b:boolean)=>{setDirty(b);onDirtyChange(b)},[onDirtyChange]);
 function select(id:string){if(dirty&&!window.confirm('저장하지 않은 설정이 있어요. 저장하지 않고 이동할까요?'))return;setDirty(false);onDirtyChange(false);setSection(id)}
 return <section className="settings-hub"><div className="page-heading"><div><h1>내 설정</h1><p>페르소나, 상태창과 대화 화면을 관리해요.</p></div></div><nav className="settings-sections" aria-label="내 설정 메뉴">{[['library','페르소나·상태창'],['display','화면·글자 설정']].map(([id,label])=><button key={id} className={section===id?'selected':''} aria-pressed={section===id} onClick={()=>select(id)}>{label}</button>)}</nav><div className="settings-content">{section==='library'?<ReaderLibrary data={data} onChange={onChange} onError={onError} onNotice={onNotice} onDirtyChange={reportDirty}/>:<div className="settings-panel"><h2>화면·글자 설정</h2><p className="field-help">이 브라우저의 모든 대화에 바로 적용되며, 새로고침해도 유지돼요.</p><label className="field"><span>대화 글자 크기</span><select value={font} onChange={e=>setFont(Number(e.target.value))}>{[16,17,19,21].map(n=><option key={n} value={n}>{n}px</option>)}</select></label><label className="settings-check"><input type="checkbox" checked={art} onChange={e=>setArt(e.target.checked)}/>대화 옆 캐릭터 이미지 표시 · PC</label><p className="field-help">글자 크기 미리보기</p><p className="settings-message-preview" style={{fontSize:font}}>“다음 장면은 어디에서 시작할까요?”</p><p className="field-help">대화별 페르소나·노트·기억은 대화 화면 오른쪽 위 메뉴에서 바꿀 수 있어요.</p><button className="secondary" onClick={()=>onNavigate('chats')}>나의 대화로 이동</button></div>}</div></section>
}
