'use client';
import {useState,useCallback} from 'react';
import ReaderLibrary from './reader-library';
export default function AccountSettings({data,onChange,onError,onNotice,onDirtyChange,onNavigate,font,setFont,art,setArt}:{data:any;onChange:(d:any)=>void;onError:(s:string)=>void;onNotice:(s:string)=>void;onDirtyChange:(b:boolean)=>void;onNavigate:(v:'chats'|'studio')=>void;font:number;setFont:(n:number)=>void;art:boolean;setArt:(b:boolean)=>void}){
 const [section,setSection]=useState('library'),[dirty,setDirty]=useState(false);
 const reportDirty=useCallback((b:boolean)=>{setDirty(b);onDirtyChange(b)},[onDirtyChange]);
 function select(id:string){if(dirty&&!window.confirm('저장하지 않은 설정이 있어요. 저장하지 않고 이동할까요?'))return;setDirty(false);onDirtyChange(false);setSection(id)}
 return <section className="settings-hub"><div className="page-heading"><div><h1>내 설정</h1><p>페르소나, 트래커와 대화 화면을 관리해요.</p></div></div><nav className="settings-sections" aria-label="내 설정 메뉴">{[['library','설정집'],['display','대화 환경'],['assets','에셋'],['account','계정 안내']].map(([id,label])=><button key={id} className={section===id?'selected':''} aria-pressed={section===id} onClick={()=>select(id)}>{label}</button>)}</nav><div className="settings-content">{section==='library'?<ReaderLibrary data={data} onChange={onChange} onError={onError} onNotice={onNotice} onDirtyChange={reportDirty}/>:section==='display'?<div className="settings-panel"><h2>대화 환경</h2><p className="field-help">화면 설정은 이 탭에만 적용돼요. 새로고침하면 초기화됩니다.</p><label className="field"><span>대화 글자 크기</span><select value={font} onChange={e=>setFont(Number(e.target.value))}>{[16,17,19,21].map(n=><option key={n} value={n}>{n}px</option>)}</select></label><label className="settings-check"><input type="checkbox" checked={art} onChange={e=>setArt(e.target.checked)}/>캐릭터 일러스트 표시</label><p className="settings-message-preview" style={{fontSize:font}}>“다음 장면은 어디에서 시작할까요?”</p><p className="field-help">대화별 페르소나·노트·기억은 대화 화면 오른쪽 위 메뉴에서 바꿀 수 있어요.</p><button className="secondary" onClick={()=>onNavigate('chats')}>나의 대화로 이동</button></div>:section==='assets'?<div className="settings-panel"><h2>에셋</h2><p>수집한 이미지와 캐릭터 에셋을 확인해요.</p><button className="primary" onClick={()=>onNavigate('studio')}>에셋 스튜디오로 이동</button></div>:<div className="settings-panel"><h2>계정 안내</h2><p>나에게만 보이는 비공개 프로토타입입니다. 작품과 대화는 이 계정에 저장돼요.</p><p className="field-help">계정 정보 변경과 실제 결제는 아직 지원하지 않아요.</p><div className="settings-disabled"><button className="secondary" disabled>프로필 변경 · 준비 중</button><button className="secondary" disabled>계정 관리 · 준비 중</button></div></div>}</div></section>
}
