'use client';
import {useEffect,useRef,useState} from 'react';
import {LockKeyhole,Plus,Save,Archive} from 'lucide-react';
import type {Work} from './lib/data';
const label=(c:any)=>c.type==='messages'?`내 메시지 ${c.value}개`:c.type==='opening'?`첫 장면: ${c.value}`:`키워드: ${c.value}`;
export default function AssetEditor({work,onError}:{work:Work;onError:(s:string)=>void}){
 const [assets,setAssets]=useState<any[]>([]),[title,setTitle]=useState(''),[character,setCharacter]=useState(work.characters[0]?.id||''),[kind,setKind]=useState('messages'),[value,setValue]=useState('3'),[file,setFile]=useState(''),[editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false);const request=useRef('');
 async function load(){const r=await fetch('/api/app?assetsFor='+encodeURIComponent(work.id));const j=await r.json() as any;if(!r.ok)throw Error(j.error);setAssets(j.assets);}
 useEffect(()=>{if(work.id)load().catch(e=>onError(e.message));setCharacter(work.characters[0]?.id||'');},[work.id]);
 async function post(action:string,data:any){const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const j=await r.json() as any;if(!r.ok)throw Error(j.error);return j;}
 async function save(){setBusy(true);onError('');try{request.current ||=crypto.randomUUID();const j=await post('saveCollectible',{workId:work.id,id:editing?.id,title,characterId:character,condition:{type:kind,value:kind==='messages'?Number(value):value},file,requestId:request.current});setAssets(j.assets);request.current='';setEditing(null);setTitle('');setFile('');}catch(e:any){onError(e.message)}finally{setBusy(false)}}
 if(!work.id)return <div className="info-note"><LockKeyhole size={18}/>작품을 먼저 저장하면 캐릭터별 에셋과 해금 조건을 등록할 수 있어요.</div>;
 return <div className="asset-editor"><p className="field-help">표지와 수집 에셋은 별개예요. 직접 등록한 이미지만 대화 조건을 달성한 뒤 수집됩니다. 이미 수집한 에셋은 조건을 바꿔도 유지돼요.</p><div className="creator-assets">{assets.map(a=><article key={a.id}><img src={a.image} alt={a.title}/><div><strong>{a.title}</strong><small>{a.character_name} · {label(a.condition)}</small><button className="text-button" onClick={()=>{setEditing(a);setTitle(a.title);setCharacter(a.character_id);setKind(a.condition.type);setValue(String(a.condition.value));setFile('')}}>조건 편집</button><button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await post('archiveCollectible',{id:a.id});await load()}catch(e:any){onError(e.message)}finally{setBusy(false)}}}><Archive size={13}/>신규 해금 중지</button></div></article>)}</div>
 <div className="character-form"><h3>{editing?'해금 조건 편집':'새 수집 에셋'}</h3><label className="field"><span className="field-label">캐릭터</span><select value={character} disabled={!!editing} onChange={e=>setCharacter(e.target.value)}>{work.characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span className="field-label">에셋 이름</span><input maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="예: 비밀 정원의 초대장"/></label>{!editing&&<label className="field"><span className="field-label">이미지 업로드 · 최대 2 MB</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024){onError('2 MB 이하 이미지를 선택해 주세요.');return}const r=new FileReader();r.onload=()=>{setFile(String(r.result));request.current='';};r.readAsDataURL(f)}}/><small>PNG, JPEG, WebP · 권리를 가진 이미지만 등록하세요. 공개 표지 경로는 수집 에셋으로 사용할 수 없어요.</small></label>}
 <label className="field"><span className="field-label">해금 조건</span><select value={kind} onChange={e=>{setKind(e.target.value);setValue(e.target.value==='messages'?'3':e.target.value==='opening'?work.openings[0].title:'')}}><option value="messages">이 대화에서 내 메시지 N개</option><option value="opening">특정 첫 장면으로 시작</option><option value="keyword">내 메시지에 특정 문구 포함</option></select></label><label className="field"><span className="field-label">{kind==='messages'?'필요 메시지 수':kind==='opening'?'첫 장면':'해금 문구'}</span>{kind==='opening'?<select value={value} onChange={e=>setValue(e.target.value)}>{work.openings.map((o,i)=><option key={i}>{o.title}</option>)}</select>:<input type={kind==='messages'?'number':'text'} min={1} max={500} maxLength={100} value={value} onChange={e=>setValue(e.target.value)}/>}</label><p className="field-help">{kind==='keyword'?'대소문자를 구분하지 않고, 내가 보낸 메시지의 포함 여부로 판정해요.':kind==='messages'?'서버에 저장된 내 메시지를 세요. 중복 전송은 한 번만 세며 새 대화는 0부터 시작해요.':'선택한 첫 장면의 이름이 일치하는 대화에서 해금돼요.'} AI의 감정 추정은 사용하지 않아요.</p><div className="choice-row"><button className="primary" disabled={busy||!title.trim()||(!editing&&!file)} onClick={save}><Save size={16}/>{busy?'저장 중…':'에셋 저장'}</button>{editing&&<button className="secondary" onClick={()=>{setEditing(null);setTitle('');setFile('')}}>취소</button>}</div></div></div>
}
