'use client';
import {useEffect,useRef,useState} from 'react';
import {Grape,Gift,Check,ArrowUpRight} from 'lucide-react';
type AttendanceData={day:string;claimed:boolean;count:number;grapes:number;nextReward:number;history:{day:string;grapes:number}[]};
export default function Attendance({expanded=false,onExpand}:{expanded?:boolean;onExpand?:()=>void}) {
 const [data,setData]=useState<AttendanceData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const flight=useRef(false),sequence=useRef(0),mounted=useRef(true);
 async function load(){const seq=++sequence.current;try{const r=await fetch('/api/app?attendance=1');const j=await r.json() as AttendanceData & {error?:string};if(!r.ok)throw Error(j.error||'출석 정보를 불러오지 못했어요.');if(mounted.current&&seq===sequence.current){setData(j);setError('')}}catch(e){if(mounted.current&&seq===sequence.current)setError((e as Error).message)}}
 useEffect(()=>{mounted.current=true;void load();const refresh=()=>{if(!flight.current)void load()};window.addEventListener('onseo-attendance-updated',refresh);const timer=setInterval(()=>{if(!flight.current)void load()},60000);return()=>{mounted.current=false;sequence.current++;clearInterval(timer);window.removeEventListener('onseo-attendance-updated',refresh)}},[]);
 async function claim(){if(flight.current||!data||data.claimed)return;flight.current=true;sequence.current++;setBusy(true);setError('');try{const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'claimAttendance'})});const j=await r.json() as AttendanceData & {error?:string};if(!r.ok)throw Error(j.error||'출석을 확인하지 못했어요. 다시 시도해 주세요.');if(mounted.current){setData(j);window.dispatchEvent(new Event('onseo-attendance-updated'))}}catch(e){if(mounted.current)setError((e as Error).message)}finally{flight.current=false;if(mounted.current)setBusy(false)}}
 const count=data?.count||0,progress=count>0&&count%7===0&&data?.claimed?7:count%7;
 return <section className={'attendance-card '+(expanded?'expanded':'')} aria-label="출석 포도"><div className="attendance-top"><span className="eyebrow"><Grape size={15}/> DAILY GIFT</span>{onExpand&&<button className="icon-button" onClick={onExpand} aria-label="출석 포도 상세 보기"><ArrowUpRight size={18}/></button>}</div><h2>하루 한 번,<br/>이야기가 익어가는 시간</h2><p>출석하고 포도를 모아 보세요.</p><div className="grape-stamps" aria-label={`7회 중 ${progress}회 출석`}>{Array.from({length:7},(_,i)=><span key={i} className={i<progress?'done':i===progress&&!data?.claimed?'today':''}><span>{i<progress?<Check size={18}/>:i===6?<Gift size={18}/>:<Grape size={18}/>}</span><small>{i+1}일</small></span>)}</div><button className="attendance-claim" disabled={!data||data.claimed||busy} onClick={claim}>{busy?'확인 중…':data?.claimed?'오늘 출석 완료 ✓':`출석하고 ${data?.nextReward??10}포도 받기`}</button><div className="attendance-meta"><span>누적 <b>{data?.grapes??'—'}</b> 포도</span><span>7회마다 30포도</span></div>{error&&<p className="tool-error" role="alert">{error} <button onClick={load}>다시 불러오기</button></p>}<p className="reward-disclaimer">체험용 보상 · 잉크와 별도 · 현금 가치 없음</p>{expanded&&<div className="attendance-history"><h3>나의 출석 기록</h3><p>한국 시간 자정에 다시 출석할 수 있어요. 연속 출석이 아니어도 누적 7회마다 보너스를 받아요. 포도 사용처는 준비 중이에요.</p>{data?.history.length?data.history.map(r=><div key={r.day}><span>{r.day}</span><b>+{r.grapes} 포도</b></div>):<p>첫 포도를 받아 보세요.</p>}</div>}</section>
}
