'use client';
import {characterImage} from './lib/simulation-dialogue';
import {useRef,useState} from 'react';
import {Bookmark,Check,GitBranch,PenLine,RefreshCw,History,Image as ImageIcon,ImagePlus,LockKeyhole} from 'lucide-react';
import {dialoguePreview} from './lib/dialogue';
const conditionLabel=(c:any)=>c.type==='messages'?`내 메시지 ${c.value}개 보내기`:c.type==='opening'?`첫 장면 「${c.value}」로 시작`:`내 메시지에 「${c.value}」 포함`;
import {type Work} from './lib/data';
export function MessageActions({message,bookmarked,busy,onEdit,onBookmark,onBranch,onSnapshot}:{message:any;bookmarked:boolean;busy:boolean;onEdit:()=>void;onBookmark:()=>void;onBranch:()=>void;onSnapshot?:()=>void}){
 return <div className="message-actions" aria-label="메시지 도구"><span className="message-version">{message.revision>0&&`수정 ${message.revision}`}</span><button type="button" disabled={busy} onClick={onBookmark} aria-pressed={bookmarked} title={bookmarked?'책갈피 수정':'책갈피 남기기'} aria-label={bookmarked?'책갈피 수정':'책갈피 남기기'}><Bookmark size={17} fill={bookmarked?'currentColor':'none'}/></button><button type="button" disabled={busy} onClick={onEdit} title="메시지 수정" aria-label="메시지 수정"><PenLine size={17}/></button>{message.role==='assistant'&&<><button type="button" disabled={busy} onClick={onBranch} title="이 답변에서 분기" aria-label="이 답변에서 분기"><GitBranch size={17}/></button><button type="button" aria-disabled="true" title="리롤 · 실제 AI 연결 후 사용할 수 있어요" aria-label="리롤 · 실제 AI 연결 필요" className="reroll-unavailable" onClick={e=>{const text=e.currentTarget.nextElementSibling as HTMLElement;text.hidden=!text.hidden}}><RefreshCw size={17}/></button><span className="reroll-help" role="status" hidden>리롤은 실제 AI 연결 후 사용할 수 있어요. 잉크는 차감되지 않습니다.</span>{onSnapshot&&<button type="button" className="snapshot-message-action" disabled={busy} onClick={onSnapshot} title="이 답변으로 스냅샷 만들기" aria-label="이 답변으로 스냅샷 만들기"><ImagePlus size={16}/><span>스냅샷</span></button>}</>}</div>;
}
async function post(action:string,data:any){const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const j=await r.json() as any;if(!r.ok)throw Error(j.error);return j;}
export function MessageEditor({sessionId,message,onSaved,onClose,formatOriginal=(text:string)=>text}:{sessionId:string;message:any;onSaved:()=>Promise<void>;onClose:()=>void;formatOriginal?:(text:string)=>string}){
 const [initialText]=useState(()=>message.revision>0?message.content:formatOriginal(message.content));
 const [text,setText]=useState(initialText),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revisions,setRevisions]=useState<any[]|null>(null),[historyOpen,setHistoryOpen]=useState(false);const request=useRef('');
 async function history(){setHistoryOpen(!historyOpen);if(revisions)return;try{const j=await post('messageHistory',{sessionId,messageId:message.id});setRevisions(j.revisions)}catch(e:any){setError(e.message)}}
 return <div className="message-editor"><p className="tool-note">원문과 이전 수정은 남겨 둡니다. 뒤의 답변은 자동으로 다시 생성되지 않아요. 관련 메모리북 요약은 확인 전까지 사용하지 않습니다.</p><label className="field"><span className="field-label">{message.role==='assistant'?'캐릭터의 답변':'내 메시지'}<small>{text.length}/{message.role==='user'?2000:8000}</small></span><textarea autoFocus rows={10} maxLength={message.role==='user'?2000:8000} value={text} onChange={e=>{setText(e.target.value);request.current=''}} disabled={busy}/></label><p className="field-help">행동은 *별표*로 감싸고, 대사는 따로 줄을 띄워 써 주세요.</p>{message.revision>0&&<button className="text-button" onClick={history}><History size={16}/>{historyOpen?'수정 기록 접기':'이전 내용 보기'}</button>}{historyOpen&&<div className="message-revisions">{revisions?revisions.map(r=><details key={r.revision}><summary>{r.revision===1?'원문':`${r.revision-1}차 수정`}<span>{new Date(r.created).toLocaleString('ko-KR')}</span></summary><p>{r.revision===1?formatOriginal(r.previous_content):r.previous_content}</p><button className="text-button" disabled={busy} onClick={()=>{setText(r.revision===1?formatOriginal(r.previous_content):r.previous_content);request.current=''}}>이 내용을 편집기에 가져오기</button></details>):<p>수정 기록을 불러오는 중이에요.</p>}</div>}{error&&<p className="tool-error" role="alert">{error}</p>}<div className="tool-footer"><button className="text-button" disabled={busy} onClick={onClose}>취소</button><button className="primary" disabled={busy||!text.trim()} onClick={async()=>{setBusy(true);setError('');request.current ||=crypto.randomUUID();try{await post('editMessage',{sessionId,messageId:message.id,revision:message.revision,content:text===initialText?message.content:text,requestId:request.current});await onSaved();onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{busy?'저장 중…':'수정 저장'}</button></div></div>;
}
export function BookmarkEditor({sessionId,message,bookmark,onSaved,onClose}:{sessionId:string;message:any;bookmark:any;onSaved:(b:any[])=>void;onClose:()=>void}){
 const [label,setLabel]=useState(bookmark?.active?bookmark.label:dialoguePreview(message.content).slice(0,40)),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef(''),intent=useRef<boolean|undefined>(undefined);
 async function save(active:boolean){if(busy)return;if(intent.current!==active){request.current='';intent.current=active}request.current ||=crypto.randomUUID();setBusy(true);setError('');try{const j=await post('bookmarkMessage',{sessionId,messageId:message.id,revision:bookmark?.revision??-1,label,active,requestId:request.current});onSaved(j.bookmarks);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="message-editor"><p className="marked-excerpt">{dialoguePreview(message.content).slice(0,180)}</p><label className="field"><span className="field-label">책갈피 이름</span><input autoFocus maxLength={80} value={label} disabled={busy} onChange={e=>{setLabel(e.target.value);request.current=''}}/></label><p className="field-help">이 메시지에 표시돼요. 대화 메뉴의 책갈피에서 바로 돌아올 수 있습니다.</p>{error&&<p className="tool-error" role="alert">{error}</p>}<div className="tool-footer">{bookmark?.active?<button className="text-button" disabled={busy} onClick={()=>save(false)}>책갈피 해제</button>:<button className="text-button" disabled={busy} onClick={onClose}>취소</button>}<button className="primary" disabled={busy||!label.trim()} onClick={()=>save(true)}>{busy?'저장 중…':'책갈피 저장'}</button></div></div>;
}
export function BookmarkShelf({bookmarks,messages,onJump}:{bookmarks:any[];messages:any[];onJump:(id:string)=>void}){
 const saved=bookmarks.filter(b=>b.active&&messages.some(m=>m.id===b.message_id));return <div className="bookmark-shelf"><div className="sheet-intro"><span className="eyebrow">BOOKMARKS</span><h2>다시 읽고 싶은 장면</h2><p>이 대화에 남긴 책갈피 {saved.length}개</p></div>{saved.length?saved.map((b,i)=><button className="bookmark-entry" key={b.message_id} onClick={()=>onJump(b.message_id)}><span className="bookmark-index">{String(i+1).padStart(2,'0')}</span><span><strong>{b.label}</strong><small>{dialoguePreview(messages.find(m=>m.id===b.message_id).content).slice(0,110)}</small><em>이 메시지로 이동</em></span><Bookmark size={18}/></button>):<div className="sheet-empty"><Bookmark size={28}/><p>마음에 드는 메시지 옆의<br/>책갈피를 눌러 남겨 보세요.</p></div>}</div>;
}
export function AssetShelf({work,unlocks,selected,onSelect}:{work:Work;unlocks:any[];selected:string;onSelect:(id:string)=>void}){
 const earned=unlocks.filter(a=>a.unlocked&&a.image),locked=unlocks.filter(a=>!a.unlocked);const items=[{id:'cover',title:'작품 표지',image:work.cover,source:'작품에 공개된 이미지'},...(work.characters.length>1?work.characters.filter(c=>c.portrait).map(c=>({id:'cast:'+c.id,title:c.name,image:characterImage(work,c),source:'작품에 공개된 캐릭터 이미지'})):[]),...earned.map(a=>({...a,source:`${a.character_name||work.characters[0]?.name} · 수집 완료`}))];
 return <div className="asset-shelf"><div className="sheet-intro"><span className="eyebrow">ART COLLECTION</span><h2>{work.characters.length>1?work.title:work.characters[0]?.name}의 에셋</h2><p>볼 수 있는 이미지 {items.length}개 · 잠긴 에셋 {locked.length}개</p></div><div className="chat-asset-grid">{items.map(a=><button key={a.id} className={selected===a.id?'selected':''} aria-pressed={selected===a.id} onClick={()=>onSelect(a.id)}><div><img src={a.image} alt={a.title}/>{selected===a.id&&<span><Check size={15}/>표시 중</span>}</div><strong>{a.title}</strong><small>{a.source}</small></button>)}</div><p className="field-help">이미지를 고르면 대화 옆에 표시됩니다.</p>{locked.length>0&&<div className="locked-asset-list"><h3>아직 열리지 않은 에셋</h3>{locked.map(a=><div key={a.id}><LockKeyhole size={18}/><span><strong>{a.title}</strong><small>{conditionLabel(a.condition)}</small></span></div>)}</div>}</div>;
}
