'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Bookmark,BookOpen,ChevronRight,Image as ImageIcon,Menu,PenLine,Settings2,UserRound,Volume2} from 'lucide-react';
import MemoryPanel from './memory-panel';
import TrackerPicker from './tracker-picker';
import {BookmarkShelf} from './chat-tools';
import {characterImage} from './lib/simulation-dialogue';

type Section='menu'|'persona'|'notes'|'memory'|'tracker'|'bookmarks'|'display'|'rename';
export function ChatHeaderTools({open,onAssets,onMenu}:{open:boolean;onAssets:()=>void;onMenu:()=>void}){return <div className="chat-header-tools" aria-label="대화 도구"><button type="button" className="assets-button" onClick={onAssets} aria-label="에셋 보기" title="에셋 보기"><ImageIcon size={19}/><span>에셋</span></button><button type="button" id="chat-menu-trigger" className="icon-button chat-menu-button" onClick={onMenu} aria-label="대화 메뉴" title="대화 메뉴" aria-haspopup="dialog" aria-expanded={open} aria-controls={open?'chat-settings':undefined}><Menu size={20}/></button></div>}
export default function ChatSettings({session,memory,status,bookmarks,messages,busy,onMemory,onStatus,onError,onDirtyChange,onJump,onNewChat,onBranch,balance,onWallet,onAssets,onRename,font,setFont,art,setArt,initialSection='menu'}:{session:any;memory:any;status:any;bookmarks:any[];messages:any[];busy:boolean;onMemory:(m:any)=>void;onStatus:(s:any)=>void;onError:(s:string)=>void;onDirtyChange:(dirty:boolean)=>void;onJump:(id:string)=>void;onNewChat:()=>void;onBranch:(m:any)=>void;balance?:number;onWallet?:()=>void;onAssets?:()=>void;onRename?:(title:string)=>Promise<void>;font?:number;setFont?:(n:number)=>void;art?:boolean;setArt?:(v:boolean)=>void;initialSection?:Section}){
 const [section,setSection]=useState<Section>(initialSection),[error,setError]=useState(''),[title,setTitle]=useState(session.title||session.snapshot.title),[saving,setSaving]=useState(false);const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus()},[section]);
 const labels={persona:'페르소나',notes:'유저 노트',memory:'장기 기억',tracker:'상태창',bookmarks:'북마크',display:'맞춤 채팅방',rename:'채팅방 이름'};
 return <div id="chat-settings" className="chat-settings">
 {section==='menu'?<div className="reference-settings-menu"><div className="drawer-wallet"><span>테스트 잉크 {balance??120}</span><button onClick={onWallet}>내역</button><button onClick={onWallet}>테스트 충전</button></div><section className="drawer-room"><h3>채팅방 이름</h3><button className="drawer-room-name" onClick={()=>setSection('rename')}><strong>{session.title||session.snapshot.title}</strong><PenLine size={20}/></button></section><section className="drawer-album"><button className="drawer-section-link" onClick={onAssets}><strong>앨범</strong><ChevronRight size={20}/></button><div className="drawer-album-strip">{(session.snapshot.characters.length>1?session.snapshot.characters:[session.snapshot.characters[0]]).map((c:any)=><button key={c.id||c.name} onClick={onAssets} aria-label={c.name+' 앨범 보기'}><img src={characterImage(session.snapshot,c)} alt={c.name}/></button>)}</div></section><section className="drawer-model"><h3>선택된 모델</h3><select aria-label="선택된 모델" disabled value="sample"><option value="sample">샘플 대화 · 실제 AI 연결 전</option></select><label className="drawer-disabled-toggle"><span>크리에이터 추천 모델 사용</span><input type="checkbox" disabled checked={false} readOnly/></label><button className="drawer-row" disabled><Settings2 size={20}/><span>모델 설정 <small>AI 연결 후 사용</small></span><ChevronRight size={18}/></button></section><section><h3 className="drawer-group-title">정보 수정</h3><nav aria-label="정보 수정"><button className="drawer-row" onClick={()=>setSection('persona')}><UserRound size={21}/><span>페르소나</span><ChevronRight size={18}/></button><button className="drawer-row" onClick={()=>setSection('notes')}><PenLine size={21}/><span>유저 노트</span><ChevronRight size={18}/></button></nav></section><section><h3 className="drawer-group-title">채팅방 설정</h3><nav aria-label="채팅방 설정"><button className="drawer-row" onClick={()=>setSection('tracker')}><Settings2 size={21}/><span>상태창 <small>표시 항목 선택</small></span><ChevronRight size={18}/></button><button className="drawer-row" onClick={()=>setSection('display')}><Settings2 size={21}/><span>맞춤 채팅방</span><ChevronRight size={18}/></button><button className="drawer-row" disabled><Volume2 size={21}/><span>목소리 <small>준비 중</small></span><ChevronRight size={18}/></button><button className="drawer-row" onClick={()=>setSection('bookmarks')}><Bookmark size={21}/><span>북마크</span><ChevronRight size={18}/></button></nav></section></div>:<div className="settings-section-heading"><button className="text-button" onClick={()=>setSection(section==='memory'?'notes':'menu')}><ArrowLeft size={16}/>돌아가기</button><h2 ref={heading} tabIndex={-1}>{labels[section]}</h2></div>}
 {error&&<p className="tool-error settings-error" role="alert">{error}</p>}
 {section==='rename'&&<form className="settings-panel" onSubmit={async e=>{e.preventDefault();if(!title.trim()||!onRename)return;setSaving(true);try{await onRename(title.trim());setSection('menu')}catch(e:any){setError(e.message)}finally{setSaving(false)}}}><label className="field"><span>채팅방 이름</span><input value={title} maxLength={80} onChange={e=>setTitle(e.target.value)}/></label><button className="primary" disabled={saving||!title.trim()}>저장</button></form>}
 {memory&&<div hidden={!['persona','notes','memory'].includes(section)}><MemoryPanel sessionId={session.id} memory={memory} section={section==='persona'?'persona':section==='notes'?'notes':'memory'} onChange={onMemory} onError={message=>{setError(message);onError(message)}} onDirtyChange={onDirtyChange}/></div>}
 {section==='notes'&&<button className="text-button drawer-advanced" onClick={()=>setSection('memory')}><BookOpen size={17}/>장기 기억 · 메모리북</button>}
 {section==='tracker'&&(status?<TrackerPicker sessionId={session.id} work={session.snapshot} status={status} onApply={onStatus} onClose={()=>setSection('menu')}/>:<p>상태창을 다시 불러와 주세요.</p>)}
 {section==='bookmarks'&&<BookmarkShelf bookmarks={bookmarks} messages={messages} onJump={onJump}/>}
 {section==='display'&&<div className="settings-panel"><label className="field"><span>대화 글자 크기</span><select value={font??17} onChange={e=>setFont?.(Number(e.target.value))}>{[16,17,19,21].map(n=><option key={n} value={n}>{n}px</option>)}</select></label><label className="settings-check"><input type="checkbox" checked={art??true} onChange={e=>setArt?.(e.target.checked)}/>캐릭터 일러스트 표시</label><p className="field-help">이 탭의 화면에만 적용돼요.</p></div>}
 </div>
}
