'use client';
import {useEffect,useState} from 'react';
import {modelCatalog,modelByChoice} from './lib/model-catalog';
import type {Work} from './lib/data';
export function CreatorGuideView({work}:{work:Work}){const guide=work.creatorGuide;if(!guide)return null;return <section className="creator-guide"><h2>추천 설정</h2>{guide.settings.map((s,i)=><div className="guide-setting" key={i}><b>{String(i+1).padStart(2,'0')}</b><p>{s}</p></div>)}<h2>추천 모델</h2>{guide.models.map((m,i)=><article key={i}><h3>{m.name} <small>{m.purpose}</small></h3><p>{m.note}</p></article>)}</section>}
export function ModelRecommendation({work,sessionId}:{work:Work;sessionId:string}){
 const [choice,setChoice]=useState('sample'),[saved,setSaved]=useState('sample'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;fetch('/api/app?modelPreference='+encodeURIComponent(sessionId)).then(async r=>{if(!r.ok)throw Error('모델 설정을 불러오지 못했어요.');return r.json()}).then((j:any)=>{if(alive){const id=modelByChoice(j.choice)?.id||'sample';setChoice(id);setSaved(id)}}).catch(e=>{if(alive)setNotice(e.message)});return()=>{alive=false}},[sessionId]);
 const selected=modelByChoice(choice)!,recommendations=(work.creatorGuide?.models||[]).map(m=>modelByChoice(m.name)?.id).filter(Boolean);
 return <section className="model-recommendation"><h3>모델 설정</h3><p>답변 1회 기준 · 온서 크레딧 가격안</p><div className="model-price-list" role="radiogroup" aria-label="대화 모델">{modelCatalog.map(m=><label key={m.id} className={choice===m.id?'selected':''}><input type="radio" name={'model-'+sessionId} checked={choice===m.id} disabled={busy} onChange={()=>{setChoice(m.id);setNotice('')}}/><span><strong>{m.name}</strong><small>{recommendations.includes(m.id)?'제작자 추천 · ':''}{m.group} · {m.description}</small></span><b>{m.credits===0?'무료':m.credits+' 크레딧'}</b></label>)}</div><p>선택: <strong>{selected.name}</strong> · {selected.credits} 크레딧/답변</p><p className="field-help">예정 요금입니다. 현재는 어떤 모델을 선택해도 샘플 답변이며 실제 차감은 0 크레딧입니다. 선택은 이 대화에만 저장돼요.</p><button className="primary full" disabled={busy||choice===saved} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveModelPreference',sessionId,choice})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setSaved(choice);setNotice('이 대화의 모델 설정을 저장했어요. 현재 샘플 답변 비용은 0 크레딧입니다.')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}}>{busy?'저장 중…':choice===saved?'적용 중':'이 대화에 적용'}</button>{notice&&<p role="status">{notice}</p>}</section>
}
