'use client';
import {useEffect,useRef,useState} from 'react';
export default function KGCheckout(){
 const [config,setConfig]=useState<any>(null),[packId,setPackId]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[order,setOrder]=useState<any>(null);const request=useRef(''),flight=useRef(false);
 useEffect(()=>{fetch('/api/payments').then(async r=>{const j:any=await r.json();if(!r.ok)throw Error(j.error);setConfig(j)}).catch(e=>setError(e.message))},[]);
 const pack=config?.packs.find((p:any)=>p.id===packId);
 async function pay(){if(flight.current||!pack||!consent)return;flight.current=true;setBusy(true);setError('');try{
 if(/Android|iPhone|iPad/i.test(navigator.userAgent))throw Error('현재 KG 결제는 PC 웹에서 이용해 주세요.');
 if(!request.current)request.current=crypto.randomUUID();const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({packId,requestId:request.current,confirm:true,name,phone,email})}),j:any=await r.json();if(!r.ok)throw Error(j.error);
 if(!(window as any).INIStdPay)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://stdpay.inicis.com/stdjs/INIStdPay.js';script.onload=()=>resolve();script.onerror=()=>{script.remove();reject(Error('KG 결제창을 불러오지 못했습니다.'))};document.head.appendChild(script)});
 document.getElementById('kg-payment-form')?.remove();const form=document.createElement('form');form.id='kg-payment-form';form.method='POST';form.hidden=true;for(const [key,value]of Object.entries(j.fields)){const input=document.createElement('input');input.name=key;input.value=String(value);form.appendChild(input)}document.body.appendChild(form);setOrder({id:j.orderId,status:'pending'});(window as any).INIStdPay.pay(form.id);
 }catch(e:any){setError(e.message)}finally{flight.current=false;setBusy(false)}}
 async function check(){if(!order)return;try{const r=await fetch('/api/payments?order='+encodeURIComponent(order.id));const j:any=await r.json();if(!r.ok)throw Error(j.error);setOrder(j.order)}catch(e:any){setError(e.message)}}
 return <section className="settings-panel"><h2>KG이니시스 결제</h2>{!config?.ready?<p>결제 준비 중입니다. 가맹점 연결과 상품 가격 등록 후 이용할 수 있어요.</p>:<><p>{config.mode==='test'?'KG 테스트 결제 · 실제 잉크 지급 없음':'PC 카드 결제 · 승인 후 잉크 지급'}</p><label className="field">충전 상품<select value={packId} disabled={busy||!!order} onChange={e=>{setPackId(e.target.value);setConsent(false);request.current=''}}><option value="">상품 선택</option>{config.packs.map((p:any)=><option key={p.id} value={p.id}>{p.units} 잉크 · {p.price.toLocaleString()}원</option>)}</select></label>{pack&&<><label className="field">구매자 이름<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">휴대폰<input type="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="field">이메일<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{pack.price.toLocaleString()}원 {config.mode==='test'?'테스트 결제':'결제'}와 구매자 정보의 KG이니시스 전달을 확인했습니다.</label><button className="primary full" disabled={busy||!!order||!consent||!name||!phone||!email} onClick={pay}>{busy?'결제창 준비 중…':'KG 결제창 열기'}</button></>}</>}{config?.orders?.length>0&&<details><summary>KG 결제 내역</summary>{config.orders.map((o:any)=><p key={o.id}>{o.units} 잉크 · {o.amount.toLocaleString()}원 · {o.mode==='test'?'테스트 · ':''}{({pending:'인증 대기',processing:'승인 확인 중',paid:'완료',failed:'실패',cancelled:'취소',review:'확인 필요'} as any)[o.status]} <button onClick={()=>setOrder(o)}>결과 확인</button></p>)}</details>}{order&&<p>주문 {order.id} · {({pending:'인증 대기',processing:'승인 확인 중',paid:'완료',failed:'실패',cancelled:'취소',review:'확인 필요'} as any)[order.status]||'확인 중'} <button onClick={check}>결과 확인</button></p>}{error&&<p role="alert">{error}</p>}</section>
}
