'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,UserRound,LockKeyhole,Check} from 'lucide-react';
import PersonaBuilder from './persona-builder';
import {libraryApi} from './reader-library';
import type {Work} from './lib/data';
export default function LaunchSetup({work,opening,personas,busy,error,onUpdate,onStart,onDirtyChange}:{work:Work;opening:number;personas:any[];busy:boolean;error:string;onUpdate:(data:any)=>void;onStart:(personaId:string,title:string)=>Promise<void>;onDirtyChange:(dirty:boolean)=>void}){
 const [title,setTitle]=useState(''),[selected,setSelected]=useState(''),[adding,setAdding]=useState(false),[name,setName]=useState(''),[content,setContent]=useState(''),[saving,setSaving]=useState(false),[localError,setLocalError]=useState('');
 const addButton=useRef<HTMLButtonElement>(null),previousAdding=useRef(adding);
 useEffect(()=>{if(previousAdding.current&&!adding)addButton.current?.focus();previousAdding.current=adding},[adding]);
 const token=useRef(crypto.randomUUID()),flight=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const choices=personas.filter(p=>!p.archived),pick=choices.find(p=>p.id===selected);
 useEffect(()=>onDirtyChange(!!(title.trim()||name.trim()||content.trim())),[title,name,content,onDirtyChange]);
 async function start(){if(flight.current||busy)return;flight.current=true;setSaving(true);setLocalError('');try{let personaId=selected;if(adding){const result=await libraryApi('savePersona',{name,content,createToken:token.current});onUpdate(result);if(!mounted.current)return;personaId=result.id;setSelected(result.id);setAdding(false);setName('');setContent('');token.current=crypto.randomUUID()}if(!mounted.current)return;await onStart(personaId,title)}catch(e:any){if(mounted.current)setLocalError(e.message)}finally{flight.current=false;if(mounted.current)setSaving(false)}}
 return <><div className="launch-summary"><span className="eyebrow">NEW CHAPTER</span><h2>{work.title}</h2><p>{work.openings[opening]?.title}</p></div><div className="launch-fields"><fieldset disabled={busy||saving}><label className="field"><span className="field-label">대화 이름 <small>선택</small></span><input value={title} maxLength={80} placeholder={work.title} onChange={e=>setTitle(e.target.value)}/></label><div className="launch-persona-heading"><div><span className="eyebrow">MY PERSONA</span><h3>이번 이야기의 나</h3></div>{!adding&&<button ref={addButton} className="secondary" type="button" onClick={()=>setAdding(true)}><Plus size={17}/>페르소나 추가</button>}</div>{adding?<section className="launch-persona-editor"><label className="field"><span className="field-label">설정집에 저장할 이름 <small>필수</small></span><input autoFocus maxLength={60} value={name} placeholder="예: 밤의 기록관" onChange={e=>setName(e.target.value)}/></label><PersonaBuilder value={content} onChange={setContent}/><button type="button" className="text-button" onClick={()=>setAdding(false)}>선택 화면으로 · 초안 유지</button><p className="field-help">아래 버튼을 누르면 비공개 설정집에 저장한 뒤 대화를 시작해요.</p></section>:<><div className="launch-persona-options">{choices.map(p=><button type="button" key={p.id} className={selected===p.id?'selected':''} onClick={()=>setSelected(p.id)} aria-pressed={selected===p.id}><UserRound size={18}/><span><strong>{p.name}</strong><small>{p.content.replace(/\n/g,' · ').slice(0,70)}</small></span>{selected===p.id&&<Check size={17}/>}</button>)}{!choices.length&&<button className="persona-add-empty" type="button" onClick={()=>setAdding(true)}><Plus size={24}/><span><strong>페르소나를 추가해 보세요</strong><small>이름, 역할, 말투를 정하고 이야기 속으로</small></span></button>}</div>{(name||content)&&<button className="text-button" type="button" onClick={()=>setAdding(true)}>작성하던 페르소나 이어 쓰기</button>}{pick&&<div className="persona-read-preview">{pick.content}</div>}<label className="launch-no-persona"><input type="radio" name="launch-persona" checked={!selected} onChange={()=>setSelected('')}/>페르소나 없이 가볍게 시작</label></>}<div className="info-note"><LockKeyhole size={16}/>선택한 설정은 이 대화에 따로 복사돼요. 설정집을 나중에 고쳐도 기존 대화는 유지됩니다.</div>{(localError||error)&&<p className="tool-error" role="alert">{localError||error}</p>}<button className="primary full" disabled={busy||saving||(adding&&(!name.trim()||!content.trim()))} onClick={start}>{saving||busy?'저장하고 있어요…':adding?'페르소나 저장하고 시작':pick?'이 페르소나로 시작':'이 장면에서 시작'}</button></fieldset></div></>
}
