'use client';
import {useEffect,useState,useRef} from 'react';
import PersonaBuilder from './persona-builder';
import {Save} from 'lucide-react';
export default function MemoryPanel({sessionId,memory,section='all',onChange,onError,onDirtyChange}:{sessionId:string;memory:any;section?:'all'|'persona'|'notes'|'memory';onChange:(m:any)=>void;onError:(s:string)=>void;onDirtyChange?:(dirty:boolean)=>void}){
 const [form,setForm]=useState(memory.settings),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[guideDirty,setGuideDirty]=useState(false),[summaryDirty,setSummaryDirty]=useState<Record<string,boolean>>({}),[notice,setNotice]=useState('');
 const noteRequest=useRef('');
 const dirty=JSON.stringify(form)!==JSON.stringify(memory.settings)||!!note.trim()||guideDirty||Object.values(summaryDirty).some(Boolean);
 useEffect(()=>{onDirtyChange?.(dirty)},[dirty,onDirtyChange]);
 async function post(action:string,data:any){onError('');const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,sessionId,...data})});const j=await r.json() as any;if(!r.ok)throw Error(j.error);onChange(j.memory);if(action==='saveMemory'){setForm((current:any)=>JSON.stringify(current)===JSON.stringify(form)?j.memory.settings:{...current,revision:j.memory.settings.revision});setNotice('요청한 내용을 저장했어요. 이후 입력한 내용은 한 번 더 저장해 주세요.')}return j;}
 const show=(name:string)=>section==='all'||section===name;
 return <div className="memory-panel"><fieldset disabled={busy} className="memory-fieldset">
 <p className="info-note">이 대화에만 저장돼요. 실제 AI 연결 후 응답에 사용됩니다.</p>
 <div hidden={!show('memory')}><label className="field"><span className="field-label">직접 쓰는 장기 기억<small>{(form.manual||'').length}/6000</small></span><textarea rows={5} value={form.manual} maxLength={6000} placeholder="반드시 기억할 사실과 관계. 자동 요약이 덮어쓰지 않아요." onChange={e=>{setNotice('');setForm({...form,manual:e.target.value})}}/></label></div>
 <div hidden={!show('notes')}><label className="field"><span className="field-label">유저 노트<small>{(form.user_notes||'').length}/3000</small></span><textarea rows={7} value={form.user_notes} maxLength={3000} placeholder="이번 대화의 진행 방향과 요청" onChange={e=>{setNotice('');setForm({...form,user_notes:e.target.value})}}/></label></div>
 <div hidden={!show('persona')}><PersonaBuilder value={form.persona} onDraftChange={setGuideDirty} onChange={persona=>{setNotice('');setForm({...form,persona})}}/></div>
 <div hidden={!show('memory')}><div className="memory-schedule"><label><input type="checkbox" checked={!!form.enabled} onChange={e=>{setNotice('');setForm({...form,enabled:e.target.checked?1:0})}}/>메모리북 자동 요약 예약</label><label>완료된 대화 <input type="number" min={2} max={100} value={form.interval} onChange={e=>{setNotice('');setForm({...form,interval:Number(e.target.value)})}}/> 턴마다</label></div><p className="field-help">내 메시지와 캐릭터 답변 한 쌍이 1턴입니다. 새 답변이 저장될 때 구간을 확인해요. AI 요약기는 아직 연결되지 않아 예약만 저장되고 자동 요약은 실행되지 않습니다.</p><label className="memory-include"><input type="checkbox" checked={!!form.include_book} onChange={e=>{setNotice('');setForm({...form,include_book:e.target.checked?1:0})}}/>저장한 요약을 AI 문맥에 포함</label><p className="field-help">자동 요약 예약과 별도 설정입니다. 끄면 요약은 보관만 하고 문맥에 넣지 않아요. 켜면 내용이 있는 요약을 고정·최근 순으로 최대 10개 포함합니다. 실제 AI는 연결 전입니다.</p></div>
 <button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setNotice('');try{await post('saveMemory',{manual:form.manual,userNotes:form.user_notes,persona:form.persona,interval:form.interval,enabled:form.enabled,includeBook:!!form.include_book,revision:form.revision})}catch(e:any){onError(e.message)}finally{setBusy(false)}}}><Save size={16}/>{busy?'저장 중…':'설정 저장'}</button>{notice&&<p className="field-help" role="status">{notice}</p>}<p className="field-help">페르소나·유저 노트·장기 기억의 입력 내용을 함께 저장해요.</p>
 <div hidden={!show('memory')}><h3 className="memory-heading">메모리북</h3><div className="manual-summary-create"><label className="field"><span className="field-label">지금까지의 새 기억<small>최대 4000자</small></span><textarea rows={3} maxLength={4000} value={note} onChange={e=>{setNote(e.target.value);noteRequest.current=''}} placeholder="자동 요약 간격을 기다리지 않고, 아직 요약하지 않은 완료 턴을 직접 정리해요."/></label><button className="secondary" disabled={busy||!note.trim()} onClick={async()=>{setBusy(true);noteRequest.current ||=crypto.randomUUID();try{await post('createSummary',{content:note,requestId:noteRequest.current});setNote('');noteRequest.current=''}catch(e:any){onError(e.message)}finally{setBusy(false)}}}>새 구간에 고정 기억 추가</button></div>{!memory.summaries.length?<p className="field-help">아직 요약 구간이 없어요. 설정한 턴 수가 쌓이면 여기에 표시됩니다.</p>:memory.summaries.map((s:any)=><Summary key={s.id+':'+s.revision} summary={s} onDirty={dirty=>setSummaryDirty(previous=>previous[s.id]===dirty?previous:{...previous,[s.id]:dirty})} onSave={async(content,pinned)=>{setBusy(true);try{await post('saveSummary',{id:s.id,content,pinned,revision:s.revision});setSummaryDirty(previous=>({...previous,[s.id]:false}))}catch(e:any){onError(e.message)}finally{setBusy(false)}}} busy={busy}/>)}<p className="field-help">직접 입력하거나 수정한 내용과 고정한 요약은 자동으로 덮어쓰지 않아요. 아직 대화 응답에 반영하는 실제 AI도 연결 전입니다.</p></div>
 </fieldset></div>;
}
function Summary({summary:s,onSave,onDirty,busy}:{summary:any;onSave:(c:string,p:boolean)=>void;onDirty:(dirty:boolean)=>void;busy:boolean}){const [content,setContent]=useState(s.content),[pinned,setPinned]=useState(!!s.pinned);return <div className="memory-summary"><div><strong>{s.from_turn}–{s.to_turn}턴</strong><span>{s.status==='invalidated'?'대화 수정됨 · 다시 확인 필요':s.status==='provider_required'?'AI 연결 필요':'직접 작성한 요약'}</span></div>{s.status==='invalidated'&&<p className="field-help">대화가 수정되어 이 요약은 AI 문맥에서 제외됐어요. 내용을 확인하고 저장하면 다시 포함됩니다.</p>}<textarea maxLength={4000} rows={4} placeholder="자동 요약을 기다리는 동안 직접 기억을 정리할 수 있어요." value={content} onChange={e=>{setContent(e.target.value);onDirty(e.target.value!==s.content||pinned!==!!s.pinned)}}/><div><label><input type="checkbox" checked={pinned} onChange={e=>{setPinned(e.target.checked);onDirty(content!==s.content||e.target.checked!==!!s.pinned)}}/> 고정하기</label><button className="text-button" disabled={busy} onClick={()=>onSave(content,pinned)}>요약 저장</button></div></div>}
