'use client';
import {useState} from 'react';
const fields=[{key:'이름',hint:'이야기 속에서 불릴 이름'},{key:'역할',hint:'예: 도시의 야간 기록관'},{key:'성격',hint:'예: 신중하지만 호기심이 많음'},{key:'말투',hint:'예: 짧고 차분한 존댓말'},{key:'관계',hint:'예: 처음 만난 공동 조사자'},{key:'외형',hint:'예: 긴 코트, 단정한 짧은 머리'},{key:'목표',hint:'이 이야기에서 이루고 싶은 일'},{key:'경계',hint:'예: 내 대사와 선택은 직접 결정하기'}];
export function updatePersonaFields(value:string,patch:Record<string,string>){let lines=value.split('\n');for(const [key,text] of Object.entries(patch)){const index=lines.findIndex(line=>line.startsWith(key+': '));if(index>=0){if(text.trim())lines[index]=`${key}: ${text}`;else lines.splice(index,1)}else if(text.trim())lines.push(`${key}: ${text}`)}const next=lines.filter((line,i)=>line||i>0).join('\n');if(next.length>2000)throw new Error('설정은 2,000자까지 저장할 수 있어요. 기존 내용을 줄인 뒤 다시 입력해 주세요.');return next}
export default function PersonaBuilder({value,onChange,onDraftChange}:{value:string;onChange:(v:string)=>void;onDraftChange?:(dirty:boolean)=>void}){
 const [error,setError]=useState('');
 function apply(patch:Record<string,string>){try{onChange(updatePersonaFields(value,patch));onDraftChange?.(false);setError('')}catch(e:any){setError(e.message)}}
 return <div className="persona-builder"><h3>내 페르소나 만들기</h3><p className="field-help">떠오르는 항목부터 적어 보세요. 아래 설정에 바로 반영됩니다.</p><div className="persona-examples">{[{name:'낯선 여행자',data:{역할:'새로운 도시를 찾은 여행자',성격:'호기심이 많고 관찰력이 좋다',말투:'편안하고 솔직한 말투',관계:'오늘 처음 만난 사이'}},{name:'오랜 동료',data:{역할:'같은 사건을 맡은 동료',성격:'신중하며 약속을 지킨다',말투:'짧고 다정한 말투',관계:'오랜 시간 함께 일한 동료'}}].map(t=><button key={t.name} type="button" onClick={()=>{if(!value.trim()||window.confirm('역할·성격·말투·관계를 이 예시로 채울까요? 그 밖의 내용은 유지됩니다.'))apply(t.data)}}>{t.name} 예시</button>)}</div><div className="persona-guide">{fields.map(f=><label key={f.key}><span>{f.key}</span><input maxLength={250} value={value.split('\n').find(l=>l.startsWith(f.key+': '))?.slice(f.key.length+2)||''} placeholder={f.hint} onChange={e=>apply({[f.key]:e.target.value})}/></label>)}</div>{error&&<p className="tool-error" role="alert">{error}</p>}<small>직접 입력과 예시 템플릿으로 만드는 설정입니다. AI 생성은 사용하지 않아요.</small><label className="field"><span className="field-label">내 페르소나 · 저장할 설정<small>{value.length}/2000</small></span><textarea rows={5} maxLength={2000} value={value} onChange={e=>onChange(e.target.value)} placeholder="위 항목을 채우거나 이곳에 자유롭게 써도 좋아요."/></label></div>
}
