'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Copy,Archive,RotateCcw,LockKeyhole,Share2,Check,BookOpen,UserRound,Settings2} from 'lucide-react';
import PersonaBuilder from './persona-builder';
import {StatusTemplateEditor} from './status-panel';
import {defaultStatusTemplate,normalizeStatusTemplate,type StatusField} from './lib/status-fields';
import {templatePresets} from './lib/template-presets';
export async function libraryApi(action?:string,data:any={}){const r=await fetch('/api/app'+(action?'':'?library=1'),{method:action?'POST':'GET',headers:action?{'Content-Type':'application/json'}:undefined,body:action?JSON.stringify({action,...data}):undefined}),j:any=await r.json();if(!r.ok)throw Error(j.error||'다시 시도해 주세요.');return j;}
export function TemplatePreview({fields}:{fields?:StatusField[]}){const list=normalizeStatusTemplate(fields).filter(f=>f.enabled);return <div className="template-layout-preview">{list.length?list.map(f=><div key={f.key}><span>{f.label}</span><span>미정</span></div>):<p>표시하는 항목이 없어요.</p>}</div>}
export default function ReaderLibrary({data,onChange,onError,onNotice,onDirtyChange}:{data:any;onChange:(d:any)=>void;onError:(e:string)=>void;onNotice:(s:string)=>void;onDirtyChange?:(dirty:boolean)=>void}){
 const [tab,setTab]=useState('personas'),[archived,setArchived]=useState(false),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[share,setShare]=useState(false),[consent,setConsent]=useState(false),[query,setQuery]=useState('');
 const baseline=useRef('null'),flight=useRef(false);
 const dirty=!!draft&&JSON.stringify(draft)!==baseline.current;
 useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false)},[dirty,onDirtyChange]);
 function canDiscard(){return !dirty||window.confirm('저장하지 않은 설정이 있어요. 저장하지 않고 이동할까요?')}
 function openDraft(next:any){if(busy||!canDiscard())return;baseline.current=JSON.stringify(next);setDraft(next);setShare(false)}
 const personas=data.personas||[],templates=data.templates||[],shared=data.sharedTemplates||[];
 function changeTab(t:string){if(busy||!canDiscard())return;setTab(t);setDraft(null);setShare(false);setArchived(false);setQuery('')}
 async function act(action:string,b:any,notice:string,close=true){if(flight.current||close&&!['savePersona','saveTemplate'].includes(action)&&!canDiscard())return;flight.current=true;setBusy(true);onError('');try{const j=await libraryApi(action,b);onChange(j);onNotice(j.alreadyImported?'이미 내 상태창에 있어요. 보관함도 확인해 주세요.':notice);if(close){setDraft(null);setShare(false);setConsent(false)}}catch(e:any){onError(e.message)}finally{flight.current=false;setBusy(false)}}
 const records=(tab==='personas'?personas:templates).filter((r:any)=>!!r.archived===archived&&(!query||(r.name+' '+(r.description||r.content)).toLowerCase().includes(query.toLowerCase())));
 return <><div className="page-heading folio-heading"><div><span className="eyebrow">MY COLLECTION / 03</span><h1>나의 설정집</h1><p>다음 이야기에도 가져갈 나와 장면의 형식.</p></div>{tab!=='shared'&&<button className="primary" onClick={()=>openDraft(tab==='personas'?{name:'',content:''}:{name:'',description:'',fields:defaultStatusTemplate()})}><Plus size={17}/>{tab==='personas'?'새 페르소나':'새 상태창'}</button>}</div>
 <div className="library-tabs" role="tablist" aria-label="설정집 종류">{[['personas','페르소나',UserRound],['templates','내 상태창',Settings2],['shared','공유 상태창',BookOpen]].map(([id,label,Icon]:any)=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'selected':''} onClick={()=>changeTab(id)}><Icon size={17}/>{label}</button>)}</div>
 {tab==='shared'?<><div className="info-note"><LockKeyhole size={17}/>이 사이트에 접근 권한이 있는 이용자끼리 구성을 나눠요. 사이트 자체의 공개 범위는 바뀌지 않습니다.</div><h2 className="collection-section-title">공유 상태창 <small>{shared.length}개</small></h2>{shared.length?<div className="template-catalog">{shared.map((t:any)=><article key={t.id}><span className="eyebrow">공유 상태창</span><h3>{t.name}</h3><p className="tracker-attribution">{t.author_name||'익명 제작자'}</p><p>{t.description}</p><TemplatePreview fields={t.fields}/><div className="template-card-footer"><span>가져온 계정 {t.imports||0}</span><button className="secondary" disabled={busy} onClick={()=>act('importTemplate',{id:t.id},'구성을 내 상태창에 복사했어요.')}><Copy size={15}/>가져오기</button></div></article>)}</div>:<div className="library-empty"><h3>아직 공유된 상태창이 없어요</h3><p>내 상태창에서 미리보기를 확인한 뒤 공유할 수 있어요.</p></div>}</>:<>
 {tab==='templates'&&!archived&&!draft&&<details className="builtin-trackers"><summary>온서 기본 상태창에서 시작하기</summary><h2 className="collection-section-title">온서 기본 상태창</h2><div className="template-catalog">{templatePresets.map(t=><article key={t.id}><span className="eyebrow">ONSEO ORIGINAL</span><h3>{t.name}</h3><p>{t.description}</p><TemplatePreview fields={t.fields}/><button className="secondary" disabled={busy} onClick={()=>act('importTemplate',{id:t.id},'내 상태창에 저장했어요.')}><Plus size={15}/>내 상태창에 저장</button></article>)}</div></details>}<div className="library-toolbar"><input aria-label="설정 검색" placeholder={tab==='personas'?'이름과 설정 검색':'상태창 검색'} value={query} onChange={e=>setQuery(e.target.value)}/><button className={archived?'text-button selected':'text-button'} onClick={()=>{if(busy||!canDiscard())return;setArchived(!archived);setDraft(null)}}><Archive size={16}/>{archived?'현재 항목 보기':'보관함'}</button></div>
 <div className={'library-workspace '+(draft?'has-editor':'')}><section className="library-records" aria-label={tab==='personas'?'저장한 페르소나':'저장한 상태창'}>{records.length?records.map((r:any,i:number)=><article className={'library-record '+(draft?.id===r.id?'selected':'')} key={r.id}><span className="record-number">{String(i+1).padStart(2,'0')}</span><div><div className="record-meta"><span>{tab==='personas'?'PRIVATE PERSONA':r.visibility==='shared'?'공유 중':'나만의 상태창'}</span><span>{new Date(r.updated).toLocaleDateString('ko-KR')}</span></div><h3>{r.name}</h3><p>{tab==='personas'?r.content:r.description||`${r.fields.filter((f:StatusField)=>f.enabled).length}개 항목`}</p><div className="record-actions">{!archived&&<><button className="text-button" onClick={()=>openDraft({...r})}>미리보기 · 편집</button><button className="text-button" disabled={busy} onClick={()=>act(tab==='personas'?'savePersona':'saveTemplate',{...r,id:undefined,revision:undefined,name:(r.name+' · 복사').slice(0,60)},'독립된 복사본을 만들었어요.',false)}><Copy size={14}/>복제</button></>}<button className="text-button" disabled={busy} onClick={()=>act(tab==='personas'?(archived?'restorePersona':'archivePersona'):(archived?'restoreTemplate':'archiveTemplate'),{id:r.id,revision:r.revision},archived?'복원했어요.':'보관함으로 옮겼어요.')}>{archived?<RotateCcw size={14}/>:<Archive size={14}/>} {archived?'복원':'보관'}</button></div></div></article>):<div className="library-empty"><span className="eyebrow">YOUR NEXT STORY</span><h2>{archived?'보관한 항목이 없어요':tab==='personas'?'이야기 속의 나를 저장해 두세요':'나만의 상태창을 만들어 보세요'}</h2><p>{archived?'보관한 항목은 언제든 복원할 수 있어요.':tab==='personas'?'대화를 시작할 때 골라 쓸 수 있어요. 이미 시작한 대화에는 변경이 번지지 않습니다.':'항목 이름·순서·표시만 보관해요. 실제 장면의 값은 대화에 남습니다.'}</p></div>}</section>
 {draft&&<section className="library-editor"><fieldset disabled={busy}><div className="library-editor-heading"><span className="eyebrow">{draft.id?'EDIT COLLECTION':'NEW COLLECTION'}</span><button className="text-button" onClick={()=>{if(busy||!canDiscard())return;setDraft(null);setShare(false)}}>편집 닫기</button></div><label className="field"><span className="field-label">{tab==='personas'?'페르소나 이름':'상태창 이름'}<small>{draft.name.length}/60</small></span><input maxLength={60} value={draft.name} placeholder={tab==='personas'?'예: 밤의 기록관':'예: 여행자의 수첩'} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
 {tab==='personas'?<><PersonaBuilder key={draft.id||'new'} value={draft.content} onChange={content=>setDraft({...draft,content})}/><div className="info-note"><LockKeyhole size={16}/>나에게만 보이는 설정입니다. 저장해도 기존 대화의 페르소나는 바뀌지 않아요.</div></>:<><label className="field"><span className="field-label">짧은 설명</span><textarea maxLength={200} rows={2} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field"><span className="field-label">공유할 때 보일 제작자 이름</span><input maxLength={40} value={draft.authorName??draft.author_name??''} placeholder="익명 제작자" onChange={e=>setDraft({...draft,authorName:e.target.value})}/></label><h3>구성 미리보기</h3><TemplatePreview fields={draft.fields}/><StatusTemplateEditor template={draft.fields} onChange={fields=>setDraft({...draft,fields})} libraryTools={false}/>{draft.visibility==='shared'&&<p className="field-help">편집해서 저장하면 공유가 해제돼요. 바뀐 내용을 확인한 뒤 다시 공유해 주세요.</p>}</>}
 <button className="primary" disabled={busy} onClick={()=>act(tab==='personas'?'savePersona':'saveTemplate',draft,'설정집에 저장했어요.')}><Check size={16}/>저장</button>
 {tab==='templates'&&draft.id&&<div className="template-sharing">{draft.visibility==='shared'?<button className="text-button" disabled={busy} onClick={()=>act('unshareTemplate',{id:draft.id,revision:draft.revision},'앞으로의 가져오기를 중단했어요. 이미 가져간 사본은 유지됩니다.')}><LockKeyhole size={15}/>공유 중단</button>:<button className="text-button" onClick={()=>{setShare(true);setConsent(false)}}><Share2 size={15}/>저장된 구성 공유하기</button>}{share&&<div className="share-confirm"><h3>저장된 버전을 공유할까요?</h3><strong>{templates.find((t:any)=>t.id===draft.id)?.name}</strong><p>{templates.find((t:any)=>t.id===draft.id)?.description}</p><p>제작자: {templates.find((t:any)=>t.id===draft.id)?.author_name||'익명 제작자'}</p><p>상태창 이름, 제작자 이름, 설명, 항목 이름·순서·표시 설정이 이 사이트의 접근 권한이 있는 이용자에게 보입니다. 다른 이용자가 가져간 사본은 공유를 중단해도 남아요.</p><p>현재 편집 중인 내용은 먼저 저장해야 해요. 대화, 실제 상태 값, 기억, 페르소나와 비밀 설정은 포함하지 않습니다.</p><TemplatePreview fields={templates.find((t:any)=>t.id===draft.id)?.fields}/><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>공유 대상과 내용을 확인했어요</label><button className="primary" disabled={busy||!consent} onClick={()=>act('shareTemplate',{id:draft.id,revision:draft.revision,confirmAudience:true},'이 사이트의 이용자가 구성을 가져갈 수 있어요.')}>이용자에게 구성 공유</button></div>}</div>}
 </fieldset></section>}</div></>}
 </>;
}
export function TemplateLibraryTools({fields,onApply}:{fields:StatusField[];onApply:(f:StatusField[])=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<any>(null),[selected,setSelected]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(open){setError('');libraryApi().then(setData).catch(e=>setError(e.message))}},[open]);
 const choices=[...templatePresets,...(data?.templates||[]).filter((t:any)=>!t.archived)],pick=choices.find(t=>t.id===selected);
 return <section className="template-library-tools"><button className="text-button" onClick={()=>setOpen(!open)}><BookOpen size={15}/>설정집에서 불러오기 · 구성 저장</button>{open&&<div><label className="field"><span className="field-label">불러올 상태창</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">구성을 선택해 주세요</option>{choices.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{pick&&<><TemplatePreview fields={pick.fields}/><button className="secondary" onClick={()=>{onApply(normalizeStatusTemplate(pick.fields));setNote('구성만 적용했어요. 현재 값은 유지됩니다. 화면의 저장 버튼으로 확정해 주세요.')}}>이 구성 적용</button></>}<p className="field-help">구성만 바뀌며 현재 상태 값은 그대로예요. 공유 상태창은 설정집에서 먼저 가져와 주세요.</p><label className="field"><span className="field-label">현재 구성의 저장 이름</span><input value={name} maxLength={60} placeholder="내 상태창에 비공개로 보관" onChange={e=>setName(e.target.value)}/></label><button className="secondary" disabled={busy||!name.trim()} onClick={async()=>{setBusy(true);setError('');try{const j=await libraryApi('saveTemplate',{name,fields});setData(j);setName('');setNote('현재 구성을 내 상태창에 비공개로 저장했어요.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>현재 구성만 저장</button>{note&&<p role="status">{note}</p>}{error&&<p role="alert">{error}</p>}</div>}</section>
}
