'use client';
import {dialoguePreview} from './lib/dialogue';
import {useState} from 'react';
import {MessageCircle,Trash2,RotateCcw,Search,PenLine,GitBranch} from 'lucide-react';
export default function SessionLibrary({sessions,onOpen,onAction,busy}:{sessions:any[];onOpen:(id:string)=>void;onAction:(action:string,data:any)=>Promise<boolean>;busy:boolean}){
 const [searchBy,setSearchBy]=useState('character');const searchLabel=searchBy==='character'?'캐릭터 이름':'페르소나 이름';
 const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[editId,setEditId]=useState(''),[title,setTitle]=useState('');
 const list=sessions.filter(s=>!!s.archived===archived&&(!query||(searchBy==='character'?(s.snapshot.characters||[]).map((c:any)=>c.name):[s.personaSnapshot?.name||'']).some((name:string)=>name.toLowerCase().includes(query.trim().toLowerCase()))));
 return <><div className="page-heading folio-heading"><div><span className="eyebrow">MY STORIES / 02</span><h1>나의 대화</h1><p>멈춘 장면에서 이어 쓰고, 다른 가능성을 남겨 두세요.</p></div><span className="subtle-badge">{list.length}개 기록</span></div><div className="workspace-tabs"><button className={!archived?'selected':''} onClick={()=>{setArchived(false);setEditId('')}}>진행 중</button><button className={archived?'selected':''} onClick={()=>{setArchived(true);setEditId('')}}>휴지통</button></div><div className="session-toolbar"><select aria-label="대화 검색 기준" value={searchBy} onChange={e=>setSearchBy(e.target.value)}><option value="character">캐릭터 이름</option><option value="persona">페르소나 이름</option></select><div className="search-box"><Search size={18}/><input aria-label={searchLabel+' 검색'} placeholder={searchLabel+'을 입력하세요'} value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
 {list.length?<div className="session-library-list">{list.map((s,i)=><article className="session-record" key={s.id}><button className="session-record-cover" disabled={archived||busy} onClick={()=>onOpen(s.id)} aria-label={(s.title||s.snapshot.title)+' 이어가기'}><img src={s.snapshot.cover} alt=""/></button><div className="session-record-body"><div className="record-meta"><span>{s.provenance?.kind==='branch'?<><GitBranch size={13}/>갈래 기록</>:'샘플 대화'} · {s.turns||0}턴</span><span>{new Date(s.last_active||s.created).toLocaleDateString('ko-KR')}</span></div>{editId===s.id?<form className="session-rename" onSubmit={async e=>{e.preventDefault();if(await onAction('renameSession',{id:s.id,title}))setEditId('')}}><input aria-label="새 대화 이름" maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/><button className="secondary" disabled={busy||!title.trim()}>저장</button><button className="text-button" type="button" onClick={()=>setEditId('')}>취소</button></form>:<h2><button disabled={archived||busy} onClick={()=>onOpen(s.id)}>{s.title||s.snapshot.title}</button></h2>}<p className="session-origin">{s.snapshot.title} · {s.opening}{s.personaSnapshot?.name?' · '+s.personaSnapshot.name:''}</p><p className="session-excerpt">{dialoguePreview(s.last_message||'첫 장면에서 기다리고 있어요.')}</p>{s.provenance?.sourceTitle&&<p className="branch-origin">「{s.provenance.sourceTitle}」에서 나눈 {s.provenance.turns}턴 이후의 갈래</p>}<div className="record-actions">{!archived&&<button className="text-button" disabled={busy} onClick={()=>onOpen(s.id)}><MessageCircle size={15}/>이어가기</button>}<button className="text-button" onClick={()=>{setEditId(s.id);setTitle(s.title||s.snapshot.title)}}><PenLine size={14}/>이름 변경</button><button className="text-button" disabled={busy} onClick={()=>{if(archived||window.confirm('이 대화를 삭제할까요? 휴지통에서 다시 복원할 수 있어요.'))onAction(archived?'restoreSession':'archiveSession',{id:s.id})}}>{archived?<RotateCcw size={14}/>:<Trash2 size={14}/>} {archived?'복원':'삭제'}</button></div></div><span className="record-number">{String(i+1).padStart(2,'0')}</span></article>)}</div>:<div className="empty-state"><span className="circle-icon"><MessageCircle size={26}/></span><h2>{query?'검색 결과가 없어요':archived?'휴지통이 비어 있어요':'첫 장면을 시작해 보세요'}</h2><p>{query?'다른 이름이나 작품 제목으로 검색해 보세요.':archived?'삭제한 대화는 여기에서 복원할 수 있어요.':'발견에서 작품을 고르면 나의 이야기가 쌓입니다.'}</p></div>}</>;
}
