'use client';
import KGCheckout from './kg-checkout';
import {useEffect,useRef,useState} from 'react';
import {Coins,CheckCircle2,ReceiptText,ArrowLeft,LockKeyhole,CreditCard,Smartphone} from 'lucide-react';
type Pack={id:string;name:string;units:number};
export default function TestWallet({balance,onUpdate}:{balance:number;onUpdate:(data:any)=>void}){
 const [data,setData]=useState<any>(null),[stage,setStage]=useState<'packs'|'review'|'receipt'|'history'>('packs'),[selected,setSelected]=useState<Pack|null>(null),[receipt,setReceipt]=useState<any>(null),[recovered,setRecovered]=useState(false),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const stageHeading=useRef<HTMLHeadingElement>(null),previousStage=useRef(stage);
 useEffect(()=>{if(previousStage.current!==stage){previousStage.current=stage;stageHeading.current?.focus()}},[stage]);
 const request=useRef(''),flight=useRef(false),mounted=useRef(true),readSequence=useRef(0);
 async function load(){const sequence=++readSequence.current;setError('');try{const r=await fetch('/api/app?wallet=1'),j:any=await r.json();if(!r.ok)throw Error(j.error);if(mounted.current&&sequence===readSequence.current){setData(j);if(j.pendingReceipt){setReceipt(j.pendingReceipt);setRecovered(true);setStage('receipt')}}}catch(e:any){if(mounted.current&&sequence===readSequence.current)setError(e.message||'테스트 지갑을 불러오지 못했어요.')}}
 useEffect(()=>{mounted.current=true;load();return()=>{mounted.current=false}},[]);
 function choose(pack:Pack){request.current=crypto.randomUUID();setSelected(pack);setChecked(false);setError('');setStage('review')}
 async function purchase(){if(flight.current||!selected||!checked)return;flight.current=true;readSequence.current++;setBusy(true);setError('');try{const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'testPurchase',packId:selected.id,confirmTest:true,requestId:request.current})}),j:any=await r.json();if(!r.ok)throw Error(j.error);onUpdate({balance:j.balance,ledger:j.ledger});if(mounted.current){setData(j);setReceipt(j.receipt);setRecovered(!!j.recovered);setStage('receipt')}}catch(e:any){if(mounted.current)setError(e.message||'응답을 확인하지 못했어요. 같은 요청으로 다시 시도하거나 내역을 확인해 주세요.')}finally{flight.current=false;if(mounted.current)setBusy(false)}}
 async function acknowledge(next:'packs'|'history'){if(flight.current||!receipt)return;flight.current=true;readSequence.current++;setBusy(true);setError('');try{const r=await fetch('/api/app',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'acknowledgeTestReceipt',receiptId:receipt.id,confirmRead:true})}),j:any=await r.json();if(!r.ok)throw Error(j.error);onUpdate({balance:j.balance,ledger:j.ledger});if(mounted.current){setData(j);if(j.pendingReceipt){setReceipt(j.pendingReceipt);setRecovered(true);setStage('receipt')}else{setReceipt(null);setStage(next)}}}catch(e:any){if(mounted.current)setError(e.message||'완료 기록 확인을 저장하지 못했어요. 다시 시도해 주세요.')}finally{flight.current=false;if(mounted.current)setBusy(false)}}
 return <div className="test-wallet"><KGCheckout/><div className="wallet-intro"><h2>잉크 충전</h2></div><ol className="checkout-steps" aria-label="충전 단계">{['묶음 선택','충전 확인','완료'].map((label,i)=><li key={label} className={(stage==='packs'?0:stage==='review'?1:stage==='receipt'?2:-1)===i?'active':''}><span>{i+1}</span>{label}</li>)}</ol><div className="test-wallet-banner"><span>TEST ONLY</span>현금 가치 없는 테스트 잉크 · 실제 청구 ₩0</div><div className="test-wallet-balance"><Coins size={24}/><div><small>사용 가능한 테스트 잉크</small><strong>{(data?.balance??balance).toLocaleString()}<span> 잉크</span></strong></div>{stage!=='receipt'&&<button className="text-button" disabled={busy} onClick={()=>{setStage(stage==='history'?'packs':'history');load()}}><ReceiptText size={16}/>{stage==='history'?'묶음 보기':'이용 내역'}</button>}</div>{error&&<p className="tool-error" role="alert">{error}</p>}
 {stage==='packs'&&<><h2 ref={stageHeading} tabIndex={-1}>테스트 묶음 선택</h2><p className="field-help">충전 흐름만 체험해요. 카드나 결제 정보를 입력하지 않습니다.</p>{data?<div className="test-pack-list">{data.packs.map((pack:Pack)=><button key={pack.id} className={selected?.id===pack.id?'selected':''} aria-pressed={selected?.id===pack.id} onClick={()=>choose(pack)}><span><strong>{pack.units.toLocaleString()} <small>테스트 잉크</small></strong><small>{pack.name}</small></span><span className="test-pack-price">₩0<small>실제 청구 없음</small></span></button>)}</div>:<div className="wallet-loading">{error?<button className="secondary" onClick={load}>다시 불러오기</button>:'테스트 묶음을 불러오고 있어요.'}</div>}<section className="test-cost-guide"><h3>현재 이용 비용</h3><p><span>샘플 대화 · 페르소나 · 상태창</span><strong>0 잉크</strong></p><p><span>AI · 이미지 · 스냅샷 생성</span><strong>연결 전</strong></p><small>실제 AI와 결제는 연결 전이에요. 사용할 수 없는 기능에는 잉크가 차감되지 않습니다. 최초 120 잉크와 이전 테스트 기록은 유지돼요.</small></section><p className="field-help">계정당 누적 테스트 충전 한도: 10,000 잉크</p></>}
 {stage==='review'&&selected&&<><button className="text-button" disabled={busy} onClick={()=>setStage('packs')}><ArrowLeft size={15}/>다른 묶음 선택</button><h2 ref={stageHeading} tabIndex={-1}>테스트 충전 확인</h2><div className="test-review"><p><span>온서 테스트 묶음</span><strong>{selected.units} 잉크</strong></p><p><span>결제 방식</span><strong>시뮬레이션 · 1회</strong></p><p><span>지급 위치</span><strong>내 테스트 지갑</strong></p><p className="test-review-total"><span>실제 청구 금액</span><strong>₩0</strong></p></div><div className="info-note"><LockKeyhole size={16}/>결제 수단은 연결되지 않았어요. 테스트 완료 기록만 저장합니다.</div><label className="test-wallet-consent"><input type="checkbox" checked={checked} disabled={busy} onChange={e=>setChecked(e.target.checked)}/>실제 결제 없는 테스트 충전임을 확인했어요</label><button className="primary full" disabled={busy||!checked} onClick={purchase}>{busy?'테스트 처리 중…':'₩0 테스트 충전 완료'}</button><button className="text-button full" disabled={busy} onClick={()=>{setStage('packs')}}>취소</button><p className="field-help">완료 버튼 전에는 잔액이 바뀌지 않아요.</p></>}
 {stage==='receipt'&&receipt&&<section className="test-receipt"><CheckCircle2 size={36}/><span className="eyebrow">TEST RECEIPT</span><h2 ref={stageHeading} tabIndex={-1}>{recovered?'이미 완료된 테스트 기록을 확인해 주세요':`${receipt.units} 테스트 잉크가 담겼어요`}</h2>{recovered&&<p>{receipt.units} 잉크가 이미 지급된 기록이에요. 새 충전은 진행하지 않았습니다.</p>}<p>실제 결제 영수증이 아닌 테스트 완료 기록입니다.</p><p className="field-help">이 기록을 확인하기 전에는 새 테스트 충전이 진행되지 않아요. 창을 닫아도 여기서 다시 확인할 수 있습니다.</p><dl><div><dt>실제 청구</dt><dd>₩0</dd></div><div><dt>처리 방식</dt><dd>1회 시뮬레이션</dd></div><div><dt>처리 시간</dt><dd>{new Date(receipt.created).toLocaleString('ko-KR')}</dd></div><div><dt>테스트 기록 번호</dt><dd>{receipt.id.slice(-16)}</dd></div></dl><button className="primary full" disabled={busy} onClick={()=>acknowledge('history')}>{busy?'확인 중…':'확인하고 내역 보기'}</button><button className="text-button full" disabled={busy} onClick={()=>acknowledge('packs')}>확인하고 지갑으로</button></section>}
 {stage==='history'&&<><h2 ref={stageHeading} tabIndex={-1}>테스트 이용 내역</h2><p className="field-help">이 계정의 테스트 기록입니다. 실제 결제 내역이 아니에요.</p><div className="test-ledger"><div><span><strong>테스트 시작 잉크</strong><small>최초 제공</small></span><b>+120</b></div>{(data?.ledger||[]).map((l:any)=><div key={l.id}><span><strong>{l.pack_id?'테스트 충전':'이전 샘플 에셋 저장'}</strong><small>{new Date(l.created).toLocaleString('ko-KR')}{l.pack_id?' · 실제 청구 ₩0':''}</small></span><b>{l.delta>0?'+':''}{l.delta}</b></div>)}</div>{!data&&<button className="secondary" onClick={load}>내역 불러오기</button>}</>}
 </div>
}
