'use client';
import {useEffect,useState} from 'react';
const packs=[{id:'try',units:120,price:1200},{id:'story',units:360,price:3600},{id:'studio',units:900,price:9000}];
export default function TestWallet({balance,onUpdate}:{balance:number;onUpdate:(data:any)=>void}){
 const [selected,setSelected]=useState<typeof packs[number]|null>(null),[method,setMethod]=useState(''),[stage,setStage]=useState('packs'),[checked,setChecked]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/app?wallet=1').then(async r=>{const j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j)}).catch(e=>setError(e.message))},[]);
 const current=data?.balance??balance;
 return <div className="test-wallet"><p className="field-help">결제 전 미리보기 · 표시 가격은 임시이며 실제 청구되지 않습니다.</p><div className="wallet-balance"><span>보유 크레딧</span><strong>{current.toLocaleString()} <small>크레딧</small></strong></div><p>출석과 충전 크레딧을 함께 사용해요.</p><ol className="checkout-steps">{['상품 선택','결제수단','주문 확인'].map((s,i)=><li key={s} className={['packs','method','review'].indexOf(stage)===i?'active':''}><span>{i+1}</span>{s}</li>)}</ol>{stage==='packs'?<><h2>충전할 크레딧</h2><div className="test-pack-grid">{packs.map(p=><button key={p.id} onClick={()=>{setSelected(p);setMethod('');setChecked(false);setStage('method')}}><strong>{p.units} 크레딧</strong><span>{p.price.toLocaleString()}원</span></button>)}</div><details><summary>크레딧 내역</summary>{data?.ledger?.map((l:any)=><p key={l.id}>{l.id.startsWith('attendance:')?'출석 보상':l.delta>0?'충전':'사용'} · {l.delta>0?'+':''}{l.delta}</p>)}</details></>:selected&&<><button className="text-button" onClick={()=>{setStage(stage==='review'?'method':'packs');setChecked(false)}}>이전 단계</button><h2>{stage==='method'?'결제수단 선택':'주문 확인'}</h2><dl className="demo-checkout"><div><dt>충전 상품</dt><dd>{selected.units} 크레딧</dd></div><div><dt>충전 후 예상 잔액</dt><dd>{(current+selected.units).toLocaleString()} 크레딧</dd></div><div><dt>결제 예정 금액 · 임시</dt><dd>{selected.price.toLocaleString()}원</dd></div></dl>{stage==='method'?<><div className="credit-methods" role="radiogroup" aria-label="결제수단">{['신용·체크카드','카카오페이','네이버페이','토스페이'].map(m=><label key={m}><input type="radio" name="payment-method" checked={method===m} onChange={()=>setMethod(m)}/>{m}</label>)}</div><p className="field-help">결제수단 선택 화면입니다. 실제 지원 여부는 PG 계약 후 확정됩니다.</p><button className="primary full" disabled={!method} onClick={()=>setStage('review')}>주문 확인으로</button></>:<><p>결제수단 <strong>{method}</strong></p><label className="demo-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>상품·결제수단·임시 금액을 확인했어요.</label><button className="primary full" disabled={!checked} onClick={()=>setError('결제 직전 단계입니다. 실제 결제 연결은 아직 시작하지 않습니다.')}>{selected.price.toLocaleString()}원 결제하기</button><p className="field-help">여기까지 미리보기입니다. 결제 요청과 크레딧 지급은 실행되지 않습니다.</p></>}</>}{error&&<p role="status">{error}</p>}</div>
}
