'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ChevronRight,Download,Search,Settings2} from 'lucide-react';
import {libraryApi,TemplatePreview} from './reader-library';
import {normalizeStatusTemplate} from './lib/status-fields';
import {workAuthor,type Work} from './lib/data';

export default function TrackerPicker({sessionId,work,status,onApply,onClose}:{sessionId:string;work:Work;status:any;onApply:(s:any)=>void;onClose:()=>void}){
 const [tab,setTab]=useState('creator'),[mode,setMode]=useState(status.tracker?.enabled===false?'none':status.tracker?.source==='creator'||!status.template?'creator':'current');
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(''),[sort,setSort]=useState('popular'),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 // Freeze the revision and preview for this opening. New external state cannot authorize an old preview.
 const [revision]=useState(status.revision),[current]=useState(()=>({fields:normalizeStatusTemplate(status.template||work.statusTemplate),name:status.tracker?.name||'현재 대화의 상태창'}));
 useEffect(()=>{let alive=true;libraryApi().then(j=>{if(alive)setData(j)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[]);
 const shared=data?.sharedTemplates||[],q=query.trim().toLowerCase();
 const results=shared.filter((t:any)=>!q||(t.name+' '+t.description+' '+t.author_name).toLowerCase().includes(q)).sort((a:any,b:any)=>sort==='popular'?(b.imports||0)-(a.imports||0)||b.updated.localeCompare(a.updated):b.updated.localeCompare(a.updated));
 const choice=tab==='shared'?selected:mode==='none'?null:mode==='creator'?{name:work.trackerName||'작품 기본 상태창',fields:normalizeStatusTemplate(work.statusTemplate)}:current;
 async function apply(){if(busy||tab==='shared'&&!selected)return;setBusy(true);setError('');try{const j=await libraryApi('applyTracker',{sessionId,revision,mode:tab==='shared'?'shared':mode,...(tab==='shared'?{sourceId:selected.id,sourceRevision:selected.revision}:{})});onApply(j.status);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="tracker-picker"><div className="tracker-folio-intro"><h2>상태창 선택</h2><p>이 대화에 표시할 항목 구성을 골라 주세요. 장소·시간·관계의 현재 값은 대화 화면에서 입력할 수 있어요.</p></div><div className="tracker-sections" aria-label="상태창 출처"><button aria-pressed={tab==='creator'} className={tab==='creator'?'selected':''} onClick={()=>{setTab('creator');setError('')}}><span>01</span><strong>작품 상태창</strong><small>제작자가 작품에 넣은 구성</small></button><button aria-pressed={tab==='shared'} className={tab==='shared'?'selected':''} onClick={()=>{setTab('shared');setError('')}}><span>02</span><strong>공유 상태창</strong><small>다른 이용자가 나눈 구성</small></button></div>
 <div className="tracker-body">{tab==='creator'?<><div className="tracker-options" role="radiogroup" aria-label="사용할 상태창">{[{id:"creator",name:work.trackerName||"작품 기본 상태창"},...(status.template&&status.tracker?.source!=="creator"?[{id:"current",name:"현재 적용 중 · "+current.name}]:[]),{id:"none",name:"상태창 사용 안 함"}].map(option=><label key={option.id} className={mode===option.id?"selected":""}><input type="radio" name="tracker-mode" checked={mode===option.id} onChange={()=>setMode(option.id)}/><span>{option.name}</span></label>)}</div><p className="tracker-attribution">{mode==='current'?(status.tracker?.source==='shared'?'공유 상태창에서 가져온 구성':'이 대화에서 직접 정한 구성'):<>제작자 {workAuthor(work)} · 이 작품에 넣은 상태창</>}</p><h3 className="tracker-preview-heading">적용할 항목</h3>{choice?<><div className="tracker-preview-title"><Settings2 size={17}/><strong>{choice.name}</strong></div><TemplatePreview fields={choice.fields}/><p className="field-help">항목 이름과 순서만 미리 보여요. 기록한 값은 그대로 유지됩니다.</p></>:<div className="tracker-disabled-preview"><Settings2 size={27}/><strong>상태창 없이 대화합니다</strong><p>언제든 다시 고를 수 있습니다.<br/>기록해 둔 값은 지워지지 않아요.</p></div>}</>:selected?<><button className="text-button" onClick={()=>setSelected(null)}><ArrowLeft size={16}/>공유 상태창 목록</button><div className="tracker-shared-detail"><span className="eyebrow">공유 상태창</span><h2>{selected.name}</h2><p className="tracker-attribution">{selected.author_name||'익명 제작자'} · 가져온 계정 {selected.imports||0}</p><p>{selected.description}</p><h3 className="tracker-preview-heading">적용할 항목</h3><TemplatePreview fields={selected.fields}/><p className="field-help">가져오면 내 상태창에도 사본이 저장돼요. 이 대화방의 표시 항목만 바뀌며, 다른 사람의 대화나 상태 값은 들어오지 않습니다.</p></div></>:<><div className="tracker-search"><Search size={17}/><input aria-label="공유 상태창 검색" placeholder="이름, 설명, 제작자 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="tracker-list-heading"><span>공유 상태창 <strong>{data?shared.length:'…'}</strong>개{q&&` · 검색 ${results.length}개`}</span><label>정렬<select aria-label="공유 상태창 정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">인기순</option><option value="latest">최신순</option></select></label></div>{!data&&error?<p className="field-help">공유 목록을 불러오지 못했어요. 닫았다가 다시 열어 주세요.</p>:!data?<div className="tracker-empty">공유 상태창을 불러오는 중이에요.</div>:results.length?<div className="shared-tracker-list">{results.map((t:any)=><button key={t.id} onClick={()=>setSelected(t)}><span><strong>{t.name}</strong><small>{t.author_name||'익명 제작자'}</small></span><span><ChevronRight size={17}/><small><Download size={13}/>{t.imports||0}</small></span></button>)}</div>:<div className="tracker-empty"><Settings2 size={28}/><h3>{q?'검색 결과가 없어요':'아직 공유된 상태창이 없어요'}</h3><p>{q?'다른 이름이나 제작자로 찾아보세요.':'설정집의 내 상태창에서 직접 만든 상태창을 공유할 수 있어요.'}</p></div>}<p className="field-help">이 사이트에 접근할 수 있는 이용자가 직접 공유한 상태창만 보여요. 인기순은 실제로 가져온 계정 수를 기준으로 합니다.</p></> }</div>
 {error&&<p className="tracker-error" role="alert">{error}</p>}<div className="tracker-footer"><button className="text-button" disabled={busy} onClick={onClose}>취소</button><button className="primary" disabled={busy||tab==='shared'&&!selected} onClick={apply}>{busy?'적용 중…':tab==='shared'?'가져와서 이 대화방에 적용':'이 대화방에 적용'}</button></div></div>;
}
