import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {works} from '../dist/catalog.js';
import {portraits} from '../dist/portraits.js';
const nodes=new Map();
function node(id=''){if(nodes.has(id))return nodes.get(id);const n={id,innerHTML:'',textContent:'',open:false,isConnected:true,hidden:true,value:'',checked:true,scrollHeight:200,scrollTop:0,classList:{add(){},remove(){},toggle(){}},style:{setProperty(){}},focus(){},matches(){return false},setSelectionRange(){},scrollIntoView(){},showModal(){this.open=true},close(){this.open=false},getBoundingClientRect(){return {left:0,top:0,right:500,bottom:500}},querySelector(s){return node(s)},addEventListener(){}};nodes.set(id,n);return n}
const document={querySelector:node,querySelectorAll(){return[]},addEventListener(){},activeElement:node('active'),documentElement:node('html'),visibilityState:'visible'};
const preferences=new Map();
const localStorage={getItem:key=>preferences.get(key)??null,setItem:(key,value)=>preferences.set(key,value)};
const context=vm.createContext({localStorage,works,portraits,document,console,setTimeout(){},clearTimeout(){},setInterval(){},AbortController,location:{hash:''},history:{replaceState(){}},window:{matchMedia(){return{matches:false}},scrollTo(){},addEventListener(){}}});
vm.runInContext(readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace("import {works} from './catalog.js';",'').replace("import {portraits} from './portraits.js';",''),context);
const run=x=>vm.runInContext(x,context);
assert.equal(run('state.view'),'home');assert.match(node('#app').innerHTML,/32개 작품/);
for(const w of works){assert.equal(run(`openWork(${JSON.stringify(w.id)})`),true);assert.match(node('#app').innerHTML,new RegExp(w.title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));run("actions['detail-tab']({dataset:{value:'opening'}})");assert.match(node('#app').innerHTML,/첫 장면 미리보기/)}
assert.equal(run("openWork('not-a-real-work')"),false);
run("openWork(works[0].id); setup()");assert(node('#dialog').open);assert.match(node('#dialog').innerHTML,/페르소나 추가/);node('#persona-name').value='<img src=x onerror=alert(1)>';node('#persona-role').value='여행자';node('#persona-description').value='가상 인물';node('#setup-opening').value='1';run('startChat()');assert.equal(run('state.view'),'chat');assert.equal(run('state.opening'),1);assert.equal(run('state.messages.length'),1);assert(!node('#dialog').open);
run("send('<script>alert(1)</script>')");assert.equal(run('state.messages.length'),3);assert(!node('#app').innerHTML.includes('<script>alert(1)</script>'));assert(node('#app').innerHTML.includes('&lt;script&gt;'));
run('actions.assets()');assert.match(node('#dialog').innerHTML,/공개 표지/);run('actions.snapshot()');assert.match(node('#dialog').innerHTML,/disabled aria-label="스냅샷 생성 · 준비 중"/);run('actions.menu()');assert.match(node('#dialog').innerHTML,/유저 노트/);assert(node('#dialog').innerHTML.includes('data-action="tracker"'));assert(!node('#dialog').innerHTML.includes('data-action="restart"'));
run('tracker()');node('#tracker-text').value='날짜 / 시간 / 장소: 저녁, 광장\n나만의 항목: 기록';run("actions['save-tracker']()");assert.equal(run('state.tracker.text'),'날짜 / 시간 / 장소: 저녁, 광장\n나만의 항목: 기록');assert.match(node('#app').innerHTML,/<summary>상태창<\/summary>/);
run('wallet()');assert.match(node('#dialog').innerHTML,/가격 미확정/);run('checkout(120)');assert.match(node('#dialog').innerHTML,/신용·체크카드/);run("state.checkoutMethod='카카오페이';paymentReview()");assert.match(node('#dialog').innerHTML,/1,200원 결제하기/);const beforePayment=run('state.balance');run("actions['payment-boundary']();actions['complete-checkout']()");assert.equal(run('state.balance'),beforePayment);assert.equal(run('state.transactions.length'),0);

run("actions.restart();actions['confirm-restart']()");assert.equal(run('state.messages.length'),1);
run("actions.home();state.query='존재하지않는검색결과';render()");assert.match(node('#app').innerHTML,/검색 결과가 없어요/);run("actions['clear-search']()");assert.match(node('#app').innerHTML,/32개 작품/);
assert.equal(run("dialogue('*행동*\\n\\n“대사”').includes('action-text')"),true);assert.equal(run("dialogue('*행동*\\n\\n“대사”').includes('dialogue-text')"),true);
console.log('PASS: 32 detail routes; opening selection; persona and input escaping; scripted chat; Assets/Menu/Tracker; disabled snapshot; test wallet success/rejection; restart/search. This is a state/markup harness, not browser visual QA.');
run('beginCreator()');assert.equal(run('state.view'),'creator');assert.equal(run('state.creatorDraft.title'),'');assert.equal(run('state.creatorDraft.cover'),'');assert.equal(run('previewDraft()'),false);assert.equal(run('state.creatorStep'),0);
run("Object.assign(state.creatorDraft,{title:'<img src=x onerror=alert(1)>',hook:'한 줄 소개',world:'새로 쓴 가상의 배경',name:'가상 기록관',age:'18',role:'기록관',personality:'조용하고 솔직해요.',openingTitle:'첫 장면',openingText:'안녕하세요.\\n\\n*책을 펼친다.*',cover:works[1].cover})");assert.equal(run('previewDraft()'),false);assert.equal(run('state.creatorStep'),2);
run("state.creatorDraft.age='25';state.creatorDraft.cover='https://bad.example/private.png'");assert.equal(run('previewDraft()'),false);assert.equal(run('state.creatorStep'),4);
run('state.creatorDraft.cover=works[1].cover');assert.equal(run('previewDraft()'),true);assert.equal(run('state.view'),'detail');assert.equal(run('state.work.demoLocal'),true);assert.equal(run('works.length'),32);assert.equal(run('editorialWorks.length'),32);assert.match(node('#app').innerHTML,/이 탭의 제작 목업/);assert(!node('#app').innerHTML.includes('<img src=x onerror=alert(1)>'));assert(node('#app').innerHTML.includes('&lt;img src=x onerror=alert(1)&gt;'));
run("beginCreator();changeDraft('title','취소할 수정');actions['cancel-creator']()");assert.equal(run('state.view'),'detail');assert.equal(run('state.work.title'),'<img src=x onerror=alert(1)>');assert.equal(run("state.localWorks.find(r=>r.preview)?.draft.title"),'<img src=x onerror=alert(1)>');assert.equal(run("state.localWorks.some(r=>r.draft.title==='취소할 수정')"),true);
assert.equal(run("dialogue('일반 문장',false).includes('action-text')"),false);assert.equal(run("dialogue('*장면 묘사*',false).includes('action-text')"),true);
run('actions.home()');assert.match(node('#app').innerHTML,/32개 작품/);assert(!node('#app').innerHTML.includes('&lt;img src=x onerror=alert(1)&gt;'));
console.log('PASS: blank creator fields; required fields; adult-age and allowlisted-cover checks; escaped local preview; 32-work catalog unchanged; cancel preserves prior preview; creator prose is not inferred as action; no publishing or persistence.');

run("beginCreator();changeDraft('title','작성 중인 제목');beginCreator()");assert.equal(run('state.creatorDraft.title'),'작성 중인 제목');console.log('PASS: creator navigation is idempotent and preserves unsaved inputs.');
// Navigation parity and isolated, explicitly ephemeral work/session management.
assert.deepEqual(Array.from(run('primaryNav.map(x=>x[1])')),['작품 탐색','나의 대화','내 작품','내 설정','에셋 스튜디오']);
run("actions.home();state.localWorks=[];state.sessions=[];state.activeSession=null;beginCreator();Object.assign(state.creatorDraft,{title:'작품 A',hook:'소개 A',world:'가상 배경 A',name:'인물 A',age:'25',openingTitle:'장면 A',openingText:'안녕하세요 A',cover:works[1].cover});previewDraft()");
const workA=run('state.createdWork.id');run("actions.works();beginCreator();Object.assign(state.creatorDraft,{title:'작품 B',hook:'소개 B',world:'가상 배경 B',name:'인물 B',age:'26',openingTitle:'장면 B',openingText:'안녕하세요 B',cover:works[2].cover});previewDraft()");const workB=run('state.createdWork.id');assert.notEqual(workA,workB);assert.equal(run('state.localWorks.length'),2);
run(`actions['edit-local-work']({dataset:{id:'${workA}'}});changeDraft('title','작품 A 수정');actions['save-local-draft']()`);assert.equal(run('state.view'),'works');assert.equal(run(`state.localWorks.find(r=>r.id==='${workB}').title`),'작품 B');assert.equal(run(`state.localWorks.find(r=>r.id==='${workA}').draft.title`),'작품 A 수정');
run(`actions['archive-work']({dataset:{id:'${workA}'}});actions['works-archived']()`);assert(node('#app').innerHTML.includes('작품 A 수정'));assert(!node('#app').innerHTML.includes('<h3>작품 B</h3>'));run(`actions['restore-work']({dataset:{id:'${workA}'}})`);assert.equal(run(`state.localWorks.find(r=>r.id==='${workA}').archived`),false);
run('actions.home();openWork(works[0].id);setup()');node('#persona-name').value='사용자 A';node('#persona-role').value='역할 A';node('#persona-description').value='이름: 사용자 A\n설명 A';node('#setup-opening').value='0';run('startChat();send("첫 대화")');const chatA=run('state.activeSession');run("state.tracker.place='장소 A';actions.chats();openWork(works[1].id);setup()");node('#persona-name').value='사용자 B';node('#persona-role').value='역할 B';node('#persona-description').value='이름: 사용자 B\n설명 B';node('#setup-opening').value='1';run('startChat()');const chatB=run('state.activeSession');assert.notEqual(chatA,chatB);assert.equal(run('state.sessions.length'),2);run(`actions.chats();actions['resume-chat']({dataset:{id:'${chatA}'}})`);assert.equal(run('state.persona.name'),'사용자 A');assert.equal(run('state.tracker.place'),'장소 A');assert.equal(run('state.messages.length'),3);assert.equal(run('state.opening'),0);
run(`actions.chats();actions['resume-chat']({dataset:{id:'${chatB}'}})`);assert.equal(run('state.persona.name'),'사용자 B');assert.equal(run('state.messages.length'),1);assert.equal(run('state.opening'),1);
run("actions.settings();actions.persona()");node('#persona-description').value='이름: 새 기본 페르소나';run("actions['save-persona']()");assert.equal(run(`state.sessions.find(r=>r.id==='${chatA}').persona.name`),'사용자 A');assert.equal(run('state.savedPersona.name'),'새 기본 페르소나');
for(const dest of ['home','chats','works','settings','studio']){run(`actions.${dest}()`);assert.equal(run('state.view'),dest);for(const label of ['작품 탐색','나의 대화','내 작품','내 설정','에셋 스튜디오'])assert(node('#app').innerHTML.includes(label));}
run('actions.settings()');assert(!node('#app').innerHTML.includes('프로필 변경'));assert(!node('#app').innerHTML.includes('계정 안내'));assert.equal(run('works.length'),32);
console.log('PASS parity: five identical primary destinations; independent works create/edit/archive/restore; independent chat/persona/tracker/opening snapshots; settings edit does not mutate old sessions; all routes render; dummy account controls removed; public catalog immutable.');
run('actions.home();beginCreator()');assert.equal(run('creatorSteps.length'),8);for(let i=0;i<8;i++){run(`state.creatorStep=${i};render()`);assert.match(node('#app').innerHTML,/작품 제작 단계/)}run("changeDraft('openingTitle','제목만 있는 초안');actions.works()");assert.equal(run("state.localWorks.some(r=>r.draft.openingTitle==='제목만 있는 초안')"),true);
run(`actions['resume-chat']({dataset:{id:'${chatA}'}});send('다시');actions['confirm-restart']();actions['back-detail']();actions.chats();actions['resume-chat']({dataset:{id:'${chatA}'}})`);assert.equal(run('state.messages.length'),1);run(`actions.chats();location.hash='#chat/${chatA}';routeHash()`);assert.equal(run('state.activeSession'),chatA);assert.equal(run('state.view'),'chat');
console.log('PASS all8 creator sections render; partial draft retained; restarted chat remains reset after resume; existing in-tab hash resolves.');
assert.equal(run("works.filter(w=>w.kind==='simulation').length"),3);assert.equal(run("editorialWorks.slice(-3).every(w=>w.kind==='simulation')"),true);
for(const id of run("works.filter(w=>w.kind==='simulation').map(w=>w.id)")){run(`actions.home();openWork('${id}')`);assert.equal(run('state.work.characters.length'),3);assert.match(node('#app').innerHTML,/등장인물 선택/);run("actions['select-cast']({dataset:{index:'1'}})");assert.equal(run('state.selectedCast'),1);run('setup()');node('#setup-opening').value='0';run('startChat()');for(let i=0;i<3;i++){run("send('다음 장면')");assert.equal(run('speaker(state.work,state.messages.at(-1).text).character.id'),run(`state.work.characters[${i}].id`))}run('actions.menu()');for(const text of ['채팅방 이름','앨범','페르소나','유저 노트','화면·글자 설정','북마크'])assert(node('#dialog').innerHTML.includes(text),text);for(const action of ['restart','back-detail'])assert(!node('#dialog').innerHTML.includes('data-action="'+action+'"'),action);assert(!node('#dialog').innerHTML.includes('목소리'));run("actions['toggle-bookmark']({dataset:{index:'2'}});actions.bookmarks()");assert.match(node('#dialog').innerHTML,/jump-bookmark/);run("actions['select-cast-art']({dataset:{value:'cast:'+state.work.characters[1].id}})");assert.equal(run('chatArtSource(state.work)'),run('state.work.characters[1].portrait'));run('actions.chats()');const sid=run('state.activeSession');run(`actions['resume-chat']({dataset:{id:'${sid}'}})`);assert.equal(run('state.messages.length'),7);assert.equal(run('state.chatBookmarks.includes(2)'),true)}
console.log('PASS three simulation entry/detail/cast/three exact speaker turns/art selection/session resume/bookmarks; reference drawer labels; removed menu actions absent; unavailable model/voice controls removed.');

assert(run('state.collected.length')>=9);run('actions.studio()');assert.match(node('#app').innerHTML,/대화한 캐릭터/);const key=run('state.collected[0].key');run(`actions['edit-collected']({dataset:{key:${JSON.stringify(key)}}})`);node('#collected-name').value='내 친구';node('#collected-note').value='<script>note</script>';node('#collected-favorite').checked=true;node('#collected-hidden').checked=false;run(`actions['save-collected']({dataset:{key:${JSON.stringify(key)}}})`);assert.match(node('#app').innerHTML,/내 친구/);assert(!node('#app').innerHTML.includes('<script>note</script>'));assert.equal(run('state.collected.find(c=>c.key==='+JSON.stringify(key)+').favorite'),true);console.log('PASS spoken cast collection, personal edits and escaped notes.');

run('state.font=21;state.art=false;saveDisplay();state.font=17;state.art=true;Object.assign(state,readDisplay())');
assert.equal(run('state.font'),21);assert.equal(run('state.art'),false);
assert.deepEqual(JSON.parse(preferences.get('onseo.display.v1')),{font:21,art:false});
preferences.set('onseo.display.v1','{"font":999,"art":"yes"}');assert.equal(run('readDisplay().font'),17);assert.equal(run('readDisplay().art'),true);
preferences.set('onseo.display.v1','bad JSON');assert.equal(run('readDisplay().font'),17);
console.log('PASS display preferences restore, validation and corruption fallback; only font/art stored.');
run(`actions.chats();actions['archive-chat']({dataset:{id:'${chatA}'}})`);assert.equal(run(`state.sessions.find(r=>r.id==='${chatA}').archived`),false);assert.match(node('#dialog').innerHTML,/confirm-delete-chat/);run('actions.close()');assert.equal(run(`state.sessions.find(r=>r.id==='${chatA}').archived`),false);run(`actions['confirm-delete-chat']({dataset:{id:'${chatA}'}})`);assert.equal(run(`state.sessions.find(r=>r.id==='${chatA}').archived`),true);run(`actions['restore-chat']({dataset:{id:'${chatA}'}})`);assert.equal(run(`state.sessions.find(r=>r.id==='${chatA}').archived`),false);console.log('PASS chat delete confirmation, cancellation, trash and restore.');
