import {modelByChoice} from './model-catalog';
import {db} from './db';
import {normalizedWork} from './data';
import {characterImage,scriptedSpeaker} from './simulation-dialogue';
export async function collectCharacters(owner:string,sessionId?:string){
 const rows=await db().prepare("SELECT s.id,s.snapshot,m.content,m.created FROM sessions s JOIN messages u ON u.session_id=s.id AND u.owner=s.owner AND u.role='user' JOIN messages m ON m.id=u.id||':reply' AND m.owner=u.owner AND m.role='assistant' WHERE s.owner=?"+(sessionId?' AND s.id=?':'')+' ORDER BY m.created').bind(...(sessionId?[owner,sessionId]:[owner])).all<any>();
 const seen=new Set<string>();for(const row of rows.results){const work=normalizedWork(JSON.parse(row.snapshot));const c=work.characters.length===1?work.characters[0]:scriptedSpeaker(work,row.content)?.character;if(!c)continue;const key=work.id+':'+c.id;if(seen.has(key))continue;seen.add(key);await db().prepare('INSERT OR IGNORE INTO character_collection(owner,character_key,session_id,name,image,note,favorite,hidden,revision,created) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(owner,key,row.id,c.name,characterImage(work,c),'',0,0,0,row.created).run();}
}
export async function readCharacters(owner:string){await collectCharacters(owner);return (await db().prepare('SELECT character_key,session_id,name,image,note,favorite,hidden,revision,created FROM character_collection WHERE owner=? ORDER BY favorite DESC,created DESC').bind(owner).all()).results;}
export async function characterAction(owner:string,b:any){if(b.action!=='editCollectedCharacter')return null;const name=typeof b.name==='string'?b.name.trim().slice(0,80):'';if(!name)return Response.json({error:'표시 이름을 입력해 주세요.'},{status:400});const r=await db().prepare('UPDATE character_collection SET name=?,note=?,favorite=?,hidden=?,revision=revision+1 WHERE owner=? AND character_key=? AND revision=?').bind(name,typeof b.note==='string'?b.note.slice(0,1000):'',b.favorite===true?1:0,b.hidden===true?1:0,owner,b.key,b.revision).run();return r.meta.changes?Response.json({characters:await readCharacters(owner)}):Response.json({error:'수집 정보가 변경됐거나 찾을 수 없어요. 다시 열어 주세요.'},{status:409});}
export async function modelPreference(owner:string,sid:string,choice?:string){const s=await db().prepare('SELECT snapshot FROM sessions WHERE id=? AND owner=?').bind(sid,owner).first<any>();if(!s)return Response.json({error:'대화를 찾을 수 없습니다.'},{status:404});if(choice!==undefined){const work=normalizedWork(JSON.parse(s.snapshot));if(!modelByChoice(choice))return Response.json({error:'지원하는 모델을 선택해 주세요.'},{status:400});await db().prepare('INSERT INTO model_preferences(owner,session_id,choice) VALUES(?,?,?) ON CONFLICT(owner,session_id) DO UPDATE SET choice=excluded.choice').bind(owner,sid,choice).run();}const row=await db().prepare('SELECT choice FROM model_preferences WHERE owner=? AND session_id=?').bind(owner,sid).first<any>();return Response.json({choice:row?.choice||''},{headers:{'Cache-Control':'no-store'}});}
