import { sampleSecrets } from './sample-secrets';
import { env } from 'cloudflare:workers';
import { db } from './db';
import { normalizedWork, sampleWorks, legacySampleWorks, workRating, type Work } from './data';
export type UnlockCondition={type:'messages'|'opening'|'keyword';value:string|number};
export async function readWork(owner:string,workId:string){const row=await db().prepare('SELECT data FROM works WHERE owner=? AND id=? AND archived=0').bind(owner,workId).first<{data:string}>();const w=row?JSON.parse(row.data):[...sampleWorks,...legacySampleWorks].find(w=>w.id===workId);return w?normalizedWork({...w,secret:row?w.secret:sampleSecrets[w.id]||w.secret}):null;}
export async function adultDeclared(owner:string){return !!await db().prepare('SELECT owner FROM age_declarations WHERE owner=?').bind(owner).first();}
export async function mayChat(owner:string,w:Work){return workRating(w)==='all'||await adultDeclared(owner);}
export function bucket():R2Bucket{if(!env.BUCKET)throw new Error('이미지 저장소를 사용할 수 없습니다.');return env.BUCKET;}
export function conditionLabel(c:UnlockCondition){return c.type==='messages'?`이 대화에서 내 메시지 ${c.value}개 보내기`:c.type==='opening'?`첫 장면 「${c.value}」로 대화 시작`:`내 메시지에 「${c.value}」 포함하기`;}
export function parseCondition(x:any,w:Work):UnlockCondition|null{if(x?.type==='messages'&&Number.isInteger(Number(x.value))&&Number(x.value)>=1&&Number(x.value)<=500)return {type:'messages',value:Number(x.value)};if(x?.type==='opening'&&w.openings.some(o=>o.title===x.value))return {type:'opening',value:x.value};if(x?.type==='keyword'&&typeof x.value==='string'&&x.value.trim().length>=1&&x.value.trim().length<=100)return {type:'keyword',value:x.value.trim()};return null;}
export async function assetMetadata(owner:string,workId:string,creator=false){const assets=await db().prepare('SELECT id,owner,work_id,character_id,character_name,title,condition,rating,active,created,updated FROM collectible_assets WHERE work_id=? AND owner=? AND active=1 ORDER BY created').bind(workId,owner).all<any>();const grants=await db().prepare('SELECT asset_id FROM collection_grants WHERE owner=? AND work_id=?').bind(owner,workId).all<any>();const owned=new Set(grants.results.map(g=>g.asset_id));return assets.results.map(a=>({...a,condition:JSON.parse(a.condition),unlocked:owned.has(a.id),...(creator||owned.has(a.id)?{image:'/api/media/'+encodeURIComponent(a.id)+(creator?'?preview=creator':'')}:{}),owner:undefined}));}
export async function progressFor(owner:string,s:any){const assets=await assetMetadata(owner,s.work_id);const msgs=await db().prepare("SELECT content FROM messages WHERE owner=? AND session_id=? AND role='user'").bind(owner,s.id).all<any>();return assets.map(a=>({...a,progress:a.condition.type==='messages'?Math.min(msgs.results.length,Number(a.condition.value)):undefined}));}
export async function awardAssets(owner:string,s:any){const assets=await db().prepare('SELECT id,work_id,character_id,condition FROM collectible_assets WHERE owner=? AND work_id=? AND active=1').bind(owner,s.work_id).all<any>();const msgs=await db().prepare("SELECT content FROM messages WHERE owner=? AND session_id=? AND role='user'").bind(owner,s.id).all<any>();const earned=[];for(const a of assets.results){const c=JSON.parse(a.condition) as UnlockCondition;const met=c.type==='messages'?msgs.results.length>=Number(c.value):c.type==='opening'?s.opening===c.value:msgs.results.some(m=>m.content.toLocaleLowerCase().includes(String(c.value).toLocaleLowerCase()));if(met){const r=await db().prepare('INSERT OR IGNORE INTO collection_grants(id,owner,asset_id,work_id,character_id,session_id,created) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,a.id,a.work_id,a.character_id,s.id,new Date().toISOString()).run();if(r.meta.changes)earned.push(a.id);}}return earned;}
export async function collections(owner:string){const r=await db().prepare('SELECT a.id,a.work_id,a.character_id,a.character_name,a.title,a.condition,a.rating,g.created,g.session_id FROM collection_grants g JOIN collectible_assets a ON a.id=g.asset_id WHERE g.owner=? ORDER BY g.created DESC').bind(owner).all<any>();return r.results.map(a=>({...a,condition:JSON.parse(a.condition),image:'/api/media/'+encodeURIComponent(a.id)}));}
