import {transcriptHash,orderedCloneTimes} from './message-actions';
import {db} from './db';
import {readLibrary,templateFields,templatePresets,readSessionDetails} from './library';
import {readMemory} from './memory';
import {readStatus} from './status';
import {readWork,mayChat} from './collectibles';
import {normalizedWork} from './data';
const now=()=>new Date().toISOString(),clean=(v:unknown,n:number)=>typeof v==='string'?v.trim().slice(0,n):'';
const out=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}}),fail=(error:string,status=400)=>out({error},status);
export async function libraryAction(owner:string,b:any):Promise<Response|null>{
 if(b.action==='savePersona'){
  const name=clean(b.name,60),content=clean(b.content,2000);if(!name||!content)return fail('페르소나의 이름과 설정을 입력해 주세요.');
  let id=clean(b.id,80)||crypto.randomUUID();if(b.createToken){if(!/^[A-Za-z0-9_-]{1,80}$/.test(b.createToken))return fail('다시 추가 화면을 열어 주세요.');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(owner+'|persona|'+b.createToken));id='persona-'+Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('')}const existing=await db().prepare('SELECT owner,revision,name,content,archived FROM personas WHERE id=?').bind(id).first<any>();
  if(existing&&existing.owner!==owner)return fail('페르소나를 찾을 수 없습니다.',404);
  if(existing&&b.createToken){if(existing.name===name&&existing.content===content&&!existing.archived)return out({id,...await readLibrary(owner)});return fail('이미 저장된 추가 요청이에요. 설정집에서 확인해 주세요.',409)}
  if(existing&&existing.revision!==b.revision)return fail('다른 창에서 페르소나가 바뀌었어요. 닫고 다시 열어 주세요.',409);
  const date=now(),r=await db().prepare('INSERT INTO personas(id,owner,name,content,created,updated) SELECT ?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM personas WHERE owner=?)<100 OR EXISTS(SELECT 1 FROM personas WHERE id=? AND owner=?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,content=excluded.content,revision=personas.revision+1,updated=excluded.updated WHERE personas.owner=excluded.owner AND personas.revision=? AND ?=0').bind(id,owner,name,content,date,date,owner,id,owner,b.revision??0,b.createToken?1:0).run();
  if(!r.meta.changes){const saved= b.createToken?await db().prepare('SELECT name,content,archived FROM personas WHERE id=? AND owner=?').bind(id,owner).first<any>():null;if(!saved||saved.archived||saved.name!==name||saved.content!==content)return fail('저장 한도에 도달했거나 다른 창에서 변경됐어요. 다시 확인해 주세요.',409)}return out({id,...await readLibrary(owner)});
 }
 if(['archivePersona','restorePersona'].includes(b.action)){const r=await db().prepare('UPDATE personas SET archived=?,revision=revision+1,updated=? WHERE id=? AND owner=? AND revision=?').bind(b.action==='archivePersona'?1:0,now(),b.id,owner,b.revision).run();if(!r.meta.changes)return fail('페르소나가 변경됐어요. 목록을 다시 열어 주세요.',409);return out(await readLibrary(owner));}
 if(b.action==='saveTemplate'){
  const name=clean(b.name,60);if(!name)return fail('트래커 이름을 입력해 주세요.');let fields;try{fields=templateFields(b.fields)}catch{return fail('상태창 구성 형식을 확인해 주세요.')}
  const id=clean(b.id,80)||crypto.randomUUID(),existing=await db().prepare('SELECT owner,revision FROM status_templates WHERE id=?').bind(id).first<any>();if(existing&&existing.owner!==owner)return fail('트래커을 찾을 수 없습니다.',404);if(existing&&existing.revision!==b.revision)return fail('다른 창에서 트래커이 바뀌었어요. 닫고 다시 열어 주세요.',409);
  const date=now(),r=await db().prepare("INSERT INTO status_templates(id,owner,name,description,fields,author_name,created,updated) SELECT ?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM status_templates WHERE owner=?)<100 OR EXISTS(SELECT 1 FROM status_templates WHERE id=? AND owner=?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,fields=excluded.fields,author_name=excluded.author_name,visibility='private',revision=status_templates.revision+1,updated=excluded.updated WHERE status_templates.owner=excluded.owner AND status_templates.revision=?").bind(id,owner,name,clean(b.description,200),JSON.stringify(fields),clean(b.authorName??b.author_name,40)||'익명 제작자',date,date,owner,id,owner,b.revision??0).run();if(!r.meta.changes)return fail('저장 한도에 도달했거나 다른 창에서 변경됐어요. 다시 확인해 주세요.',409);return out({id,...await readLibrary(owner)});
 }
 if(['shareTemplate','unshareTemplate','archiveTemplate','restoreTemplate'].includes(b.action)){
  if(b.action==='shareTemplate'&&b.confirmAudience!==true)return fail('이 사이트의 접근 권한이 있는 이용자에게 구성과 이름을 공유하는지 확인해 주세요.');
  const archived=b.action==='archiveTemplate'?1:0,visibility=b.action==='shareTemplate'?'shared':'private';
  const r=await db().prepare('UPDATE status_templates SET visibility=?,archived=?,revision=revision+1,updated=? WHERE id=? AND owner=? AND revision=?').bind(visibility,archived,now(),b.id,owner,b.revision).run();if(!r.meta.changes)return fail('트래커이 변경됐어요. 목록을 다시 열어 주세요.',409);return out(await readLibrary(owner));
 }
 if(b.action==='importTemplate'){
  const sourceId=clean(b.id,80),existing=await db().prepare('SELECT template_id FROM template_imports WHERE owner=? AND source_id=?').bind(owner,sourceId).first<any>();if(existing)return out({id:existing.template_id,alreadyImported:true,...await readLibrary(owner)});
  const builtin=templatePresets.find(t=>t.id===sourceId),shared=builtin||await db().prepare("SELECT id,name,description,fields FROM status_templates WHERE id=? AND visibility='shared' AND archived=0").bind(sourceId).first<any>();if(!shared)return fail('공유가 종료되었거나 트래커을 찾을 수 없습니다.',404);
  const fields=builtin?builtin.fields:templateFields(JSON.parse(shared.fields)),id=crypto.randomUUID(),date=now();
  const r=await db().batch([db().prepare('INSERT OR IGNORE INTO template_imports(owner,source_id,template_id) SELECT ?,?,? WHERE (SELECT COUNT(*) FROM status_templates WHERE owner=?)<100').bind(owner,sourceId,id,owner),db().prepare('INSERT INTO status_templates(id,owner,name,description,fields,source_id,created,updated) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM template_imports WHERE owner=? AND source_id=? AND template_id=?)').bind(id,owner,shared.name,shared.description,JSON.stringify(fields),sourceId,date,date,owner,sourceId,id)]);
  const saved=await db().prepare('SELECT template_id FROM template_imports WHERE owner=? AND source_id=?').bind(owner,sourceId).first<any>();if(!saved)return fail('트래커은 최대 100개까지 보관할 수 있어요.');return out({id:saved.template_id,alreadyImported:!r[0].meta.changes,...await readLibrary(owner)});
 }
 if(b.action==='createSummary'){
  const sid=clean(b.sessionId,80),content=clean(b.content,4000),request=clean(b.requestId,80);if(!content||!/^[A-Za-z0-9_-]{1,80}$/.test(request))return fail('기억할 내용을 입력해 주세요.');
  const session=await db().prepare('SELECT id FROM sessions WHERE id=? AND owner=? AND archived=0').bind(sid,owner).first();if(!session)return fail('대화를 찾을 수 없습니다.',404);const id=owner+':'+sid+':note:'+request;
  if(await db().prepare('SELECT id FROM memory_summaries WHERE id=? AND owner=? AND session_id=?').bind(id,owner,sid).first())return out({memory:await readMemory(owner,sid)});
  const transcript=await db().prepare('SELECT COUNT(*) AS count,COALESCE(SUM(revision),0) AS revision FROM messages WHERE owner=? AND session_id=?').bind(owner,sid).first<any>();
  const n=await db().prepare("SELECT COUNT(*) AS n FROM messages u WHERE u.owner=? AND u.session_id=? AND u.role='user' AND EXISTS(SELECT 1 FROM messages a WHERE a.id=u.id||':reply' AND a.owner=u.owner AND a.session_id=u.session_id)").bind(owner,sid).first<any>(),max=await db().prepare('SELECT COALESCE(MAX(to_turn),0) AS n FROM memory_summaries WHERE owner=? AND session_id=?').bind(owner,sid).first<any>();if(n.n<=max.n)return fail('아직 요약하지 않은 완료 턴이 없어요. 기존 요약을 수정하거나 장기 기억에 남겨 주세요.');const date=now();
  const r=await db().prepare("INSERT OR IGNORE INTO memory_summaries(id,owner,session_id,from_turn,to_turn,content,status,pinned,created,updated) SELECT ?,?,?,?,?,?,'manual',1,?,? WHERE NOT EXISTS(SELECT 1 FROM memory_summaries WHERE owner=? AND session_id=? AND from_turn<=? AND to_turn>=?) AND (SELECT COUNT(*) FROM messages WHERE owner=? AND session_id=?)=? AND (SELECT COALESCE(SUM(revision),0) FROM messages WHERE owner=? AND session_id=?)=? AND EXISTS(SELECT 1 FROM sessions WHERE id=? AND owner=? AND archived=0)").bind(id,owner,sid,max.n+1,n.n,content,date,date,owner,sid,n.n,max.n+1,owner,sid,transcript.count,owner,sid,transcript.revision,sid,owner).run();if(!r.meta.changes&&!await db().prepare('SELECT id FROM memory_summaries WHERE id=? AND owner=? AND session_id=?').bind(id,owner,sid).first())return fail('요약 구간이 바뀌었어요. 기억을 다시 열어 주세요.',409);return out({memory:await readMemory(owner,sid)});
 }
 if(b.action==='renameSession'){
  const title=clean(b.title,80);if(!title)return fail('대화 이름을 입력해 주세요.');const s=await db().prepare('SELECT id FROM sessions WHERE id=? AND owner=?').bind(b.id,owner).first<any>();if(!s)return fail('대화를 찾을 수 없습니다.',404);
  await db().prepare('INSERT INTO session_details(session_id,owner,title,updated) VALUES(?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET title=excluded.title,updated=excluded.updated WHERE session_details.owner=excluded.owner').bind(b.id,owner,title,now()).run();return out({ok:true});
 }
 if(b.action==='branchSession'){
  const requestId=clean(b.requestId,80);if(!/^[A-Za-z0-9_-]{1,80}$/.test(requestId))return fail('요청을 다시 시작해 주세요.');const source=await db().prepare('SELECT * FROM sessions WHERE id=? AND owner=? AND archived=0').bind(b.sessionId,owner).first<any>();if(!source)return fail('대화를 찾을 수 없습니다.',404);
  const w=normalizedWork(JSON.parse(source.snapshot));if(!await mayChat(owner,await readWork(owner,source.work_id)||w))return fail('19+ 이용 확인이 필요합니다.',403);
  const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(owner+'|'+source.id+'|'+requestId)),sid=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('');const prior=await db().prepare('SELECT id FROM sessions WHERE id=? AND owner=?').bind(sid,owner).first<any>();if(prior)return out({id:sid});
  const m=await db().prepare('SELECT * FROM messages WHERE session_id=? AND owner=? ORDER BY created,id').bind(source.id,owner).all<any>(),last=m.results.at(-1);if(!last||last.role!=='assistant'||last.id!==b.lastMessageId)return fail('새 메시지가 생겼어요. 대화를 다시 열고 현재 장면에서 갈래를 만들어 주세요.',409);if(b.sourceHash&&await transcriptHash(m.results)!==b.sourceHash)return fail('대화가 바뀌었어요. 다시 열고 갈래를 만들어 주세요.',409);if(m.results.length>401)return fail('갈래 저장은 현재 200턴까지 지원해요. 원본 대화는 계속 이어갈 수 있습니다.');
  const [details,memory,status]=await Promise.all([readSessionDetails(owner,source.id),readMemory(owner,source.id),readStatus(owner,source.id)]),date=now();
  const captureKey=crypto.randomUUID();
  const provenance={captureKey,kind:'branch',sourceSessionId:source.id,sourceMessageId:last.id,capturedAt:date,sourceTitle:details.title||w.title,inherited:'현재 장면의 페르소나·직접 기억·노트·메모리북·상태',turns:m.results.filter(x=>x.role==='user').length};
  const statements=[db().prepare("INSERT OR IGNORE INTO sessions(id,owner,work_id,snapshot,opening,created) SELECT ?,?,?,?,?,? WHERE (SELECT id FROM messages WHERE session_id=? AND owner=? ORDER BY created DESC,id DESC LIMIT 1)=? AND COALESCE((SELECT revision FROM session_memory WHERE session_id=? AND owner=?),0)=? AND COALESCE((SELECT revision FROM session_status WHERE session_id=? AND owner=?),0)=? AND EXISTS(SELECT 1 FROM sessions WHERE id=? AND owner=? AND archived=0) AND (SELECT COUNT(*) FROM memory_summaries WHERE session_id=? AND owner=?)=? AND COALESCE((SELECT SUM(revision) FROM memory_summaries WHERE session_id=? AND owner=?),0)=? AND COALESCE((SELECT SUM(revision) FROM messages WHERE session_id=? AND owner=?),0)=? AND (SELECT COUNT(*) FROM messages WHERE session_id=? AND owner=?)=?").bind(sid,owner,source.work_id,source.snapshot,source.opening,date,source.id,owner,last.id,source.id,owner,memory.settings.revision,source.id,owner,status.revision,source.id,owner,source.id,owner,memory.summaries.length,source.id,owner,memory.summaries.reduce((sum,x)=>sum+x.revision,0),source.id,owner,m.results.reduce((sum,x)=>sum+x.revision,0),source.id,owner,m.results.length)];
  const exists=" WHERE EXISTS(SELECT 1 FROM session_details WHERE session_id=? AND owner=? AND json_extract(provenance,'$.captureKey')=?)";
  statements.push(db().prepare('INSERT OR IGNORE INTO session_details(session_id,owner,title,persona_snapshot,provenance,updated) SELECT ?,?,?,?,?,? WHERE changes()=1 AND EXISTS(SELECT 1 FROM sessions WHERE id=? AND owner=?)').bind(sid,owner,clean(b.title,80)||((details.title||w.title)+' · 갈래').slice(0,80),JSON.stringify(details.personaSnapshot),JSON.stringify(provenance),date,sid,owner));
  const ids=new Map(m.results.map((x,i)=>[x.id,sid+':m'+String(i).padStart(6,'0')]));for(const x of m.results)if(x.id.endsWith(':reply')&&ids.has(x.id.slice(0,-6)))ids.set(x.id,ids.get(x.id.slice(0,-6))+':reply');
  const cloneTimes=orderedCloneTimes(m.results);for(const [index,x] of m.results.entries())statements.push(db().prepare('INSERT OR IGNORE INTO messages(id,owner,session_id,role,content,created) SELECT ?,?,?,?,?,?'+exists).bind(ids.get(x.id),owner,sid,x.role,x.content,cloneTimes[index],sid,owner,captureKey));
  const f=memory.settings;statements.push(db().prepare('INSERT OR IGNORE INTO session_memory(session_id,owner,manual,user_notes,persona,interval,enabled,include_book,updated) SELECT ?,?,?,?,?,?,?,?,?'+exists).bind(sid,owner,f.manual,f.user_notes,f.persona,f.interval,f.enabled,f.include_book??1,date,sid,owner,captureKey));
  statements.push(db().prepare('INSERT OR IGNORE INTO session_status(session_id,owner,data,updated) SELECT ?,?,?,?'+exists).bind(sid,owner,JSON.stringify({values:status.data,template:status.template,tracker:status.tracker}),date,sid,owner,captureKey));
  for(const x of memory.summaries)statements.push(db().prepare('INSERT OR IGNORE INTO memory_summaries(id,owner,session_id,from_turn,to_turn,content,status,pinned,created,updated) SELECT ?,?,?,?,?,?,?,?,?,?'+exists).bind(sid+':'+x.from_turn,owner,sid,x.from_turn,x.to_turn,x.content,x.status,x.pinned,date,date,sid,owner,captureKey));
  const result=await db().batch(statements);if(!result[0].meta.changes){const duplicate=await db().prepare('SELECT id FROM sessions WHERE id=? AND owner=?').bind(sid,owner).first();if(duplicate)return out({id:sid});return fail('대화나 기억이 바뀌었어요. 다시 열고 갈래를 만들어 주세요.',409);}return out({id:sid});
 }
 return null;
}
