import {normalizeStatusTemplate} from './status-fields';
import {readStatus} from './status';
import { db } from './db';
import { type Work, defaultRules } from './data';
export async function readMemory(owner:string,sessionId:string){const [m,s]=await Promise.all([db().prepare('SELECT manual,user_notes,persona,interval,enabled,include_book,revision,updated FROM session_memory WHERE owner=? AND session_id=?').bind(owner,sessionId).first<any>(),db().prepare('SELECT id,from_turn,to_turn,content,status,pinned,revision,created FROM memory_summaries WHERE owner=? AND session_id=? ORDER BY from_turn').bind(owner,sessionId).all<any>()]);return {settings:m||{manual:'',user_notes:'',persona:'',interval:10,enabled:1,include_book:1,revision:0},summaries:s.results};}
export async function scheduleSummary(owner:string,sessionId:string){const m=await readMemory(owner,sessionId);if(!m.settings.enabled)return;const row=await db().prepare("SELECT COUNT(*) AS n FROM messages u WHERE u.owner=? AND u.session_id=? AND u.role='user' AND EXISTS (SELECT 1 FROM messages a WHERE a.id=u.id||':reply' AND a.owner=u.owner AND a.session_id=u.session_id)").bind(owner,sessionId).first<any>();const max=await db().prepare('SELECT COALESCE(MAX(to_turn),0) AS n FROM memory_summaries WHERE owner=? AND session_id=?').bind(owner,sessionId).first<any>();const interval=m.settings.interval;for(let end=max.n+interval;end<=row.n;end+=interval){const time=new Date().toISOString();const result=await db().prepare('INSERT OR IGNORE INTO memory_summaries(id,owner,session_id,from_turn,to_turn,content,status,created,updated) SELECT ?,?,?,?,?,?,?,?,? WHERE COALESCE((SELECT revision FROM session_memory WHERE owner=? AND session_id=?),0)=? AND COALESCE((SELECT interval FROM session_memory WHERE owner=? AND session_id=?),10)=? AND COALESCE((SELECT enabled FROM session_memory WHERE owner=? AND session_id=?),1)=1 AND NOT EXISTS (SELECT 1 FROM memory_summaries WHERE owner=? AND session_id=? AND from_turn<=? AND to_turn>=?)').bind(crypto.randomUUID(),owner,sessionId,end-interval+1,end,'','provider_required',time,time,owner,sessionId,m.settings.revision,owner,sessionId,interval,owner,sessionId,owner,sessionId,end,end-interval+1).run();if(!result.meta.changes)return;}}

// Server-only provider input. Separate editor quotas do not remove model context cost.
export async function compileProviderContext(owner:string,sessionId:string,work:Work){const m=await readMemory(owner,sessionId),rules=work.responseRules||defaultRules(),status=await readStatus(owner,sessionId);return {publicStory:{title:work.title,world:work.world,characters:work.characters},creatorInstructions:{privateSetting:work.secret||'',ooc:rules.ooc,writingStyle:rules.style,perspective:rules.perspective,responseLength:rules.length},readerContext:{storyStatus:status.data,statusOutput:status.tracker?.enabled===false?null:{instruction:'본문 끝에 상태창을 <details><summary>상태창</summary>로 감싸 출력하세요. 아래 사용자 지정 항목을 따르세요. PC 감정과 행동은 사용자가 밝힌 내용만 반영하고 알 수 없는 값은 미확인으로 표시하세요.',fields:normalizeStatusTemplate(status.template||work.statusTemplate).filter(f=>f.enabled)},persona:m.settings.persona,userNotes:m.settings.user_notes,longTermMemory:m.settings.manual,memoryBook:(m.settings.include_book?m.summaries:[]).filter(s=>s.content&&s.status!=='invalidated').sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.to_turn-a.to_turn).slice(0,10).map(s=>({fromTurn:s.from_turn,toTurn:s.to_turn,content:s.content,pinned:!!s.pinned}))}};}
