// Generated by scripts/build-portrait-variants.mjs; original artwork is unchanged.
export const portraitVariants = {
  "/characters/character-01.webp": {
    "width": 1248,
    "height": 1600,
    "bytes": 1588320,
    "sha256": "a1c4dfea76f2440eb6c1fa01844622dad6926b7f686691f4433716c50bf09118",
    "variants": [
      {
        "src": "/characters/responsive/character-01-96.webp",
        "width": 96,
        "height": 123,
        "bytes": 3768
      },
      {
        "src": "/characters/responsive/character-01-320.webp",
        "width": 320,
        "height": 410,
        "bytes": 23368
      },
      {
        "src": "/characters/responsive/character-01-640.webp",
        "width": 640,
        "height": 821,
        "bytes": 61352
      },
      {
        "src": "/characters/responsive/character-01-960.webp",
        "width": 960,
        "height": 1231,
        "bytes": 107474
      }
    ]
  },
  "/characters/character-02.webp": {
    "width": 1248,
    "height": 1600,
    "bytes": 1674730,
    "sha256": "9ed634fca51445e0ab33c1cda3301cd603f04b6af611e34263b6a0ec06b4c8dd",
    "variants": [
      {
        "src": "/characters/responsive/character-02-96.webp",
        "width": 96,
        "height": 123,
        "bytes": 3162
      },
      {
        "src": "/characters/responsive/character-02-320.webp",
        "width": 320,
        "height": 410,
        "bytes": 18792
      },
      {
        "src": "/characters/responsive/character-02-640.webp",
        "width": 640,
        "height": 821,
        "bytes": 52942
      },
      {
        "src": "/characters/responsive/character-02-960.webp",
        "width": 960,
        "height": 1231,
        "bytes": 93902
      }
    ]
  },
  "/characters/character-03.webp": {
    "width": 1248,
    "height": 1600,
    "bytes": 1600222,
    "sha256": "fac0790dade66e6a39c28f0adc82c8b964fa82fe389204b0e791b73ae74c7cad",
    "variants": [
      {
        "src": "/characters/responsive/character-03-96.webp",
        "width": 96,
        "height": 123,
        "bytes": 3488
      },
      {
        "src": "/characters/responsive/character-03-320.webp",
        "width": 320,
        "height": 410,
        "bytes": 20500
      },
      {
        "src": "/characters/responsive/character-03-640.webp",
        "width": 640,
        "height": 821,
        "bytes": 53542
      },
      {
        "src": "/characters/responsive/character-03-960.webp",
        "width": 960,
        "height": 1231,
        "bytes": 90912
      }
    ]
  },
  "/characters/character-04.webp": {
    "width": 768,
    "height": 1280,
    "bytes": 764158,
    "sha256": "44fdfcbe31c74512da6af59cc3005f1050901a0c91d8a1996f0292ae960a2483",
    "variants": [
      {
        "src": "/characters/responsive/character-04-96.webp",
        "width": 96,
        "height": 160,
        "bytes": 4242
      },
      {
        "src": "/characters/responsive/character-04-320.webp",
        "width": 320,
        "height": 533,
        "bytes": 29708
      },
      {
        "src": "/characters/responsive/character-04-640.webp",
        "width": 640,
        "height": 1067,
        "bytes": 75754
      }
    ]
  },
  "/characters/character-05.webp": {
    "width": 1248,
    "height": 1600,
    "bytes": 1656010,
    "sha256": "2d6a6a74990b47104245af155ad843e3a3415e6016b994e294c6ba37b9d98033",
    "variants": [
      {
        "src": "/characters/responsive/character-05-96.webp",
        "width": 96,
        "height": 123,
        "bytes": 3690
      },
      {
        "src": "/characters/responsive/character-05-320.webp",
        "width": 320,
        "height": 410,
        "bytes": 22440
      },
      {
        "src": "/characters/responsive/character-05-640.webp",
        "width": 640,
        "height": 821,
        "bytes": 64026
      },
      {
        "src": "/characters/responsive/character-05-960.webp",
        "width": 960,
        "height": 1231,
        "bytes": 116132
      }
    ]
  },
  "/characters/character-06.webp": {
    "width": 1248,
    "height": 1600,
    "bytes": 1691454,
    "sha256": "7d263fda45171e686e78e583aeacf7dd52c8b716152ead666584472393d0d458",
    "variants": [
      {
        "src": "/characters/responsive/character-06-96.webp",
        "width": 96,
        "height": 123,
        "bytes": 3810
      },
      {
        "src": "/characters/responsive/character-06-320.webp",
        "width": 320,
        "height": 410,
        "bytes": 24394
      },
      {
        "src": "/characters/responsive/character-06-640.webp",
        "width": 640,
        "height": 821,
        "bytes": 68008
      },
      {
        "src": "/characters/responsive/character-06-960.webp",
        "width": 960,
        "height": 1231,
        "bytes": 121880
      }
    ]
  },
  "/characters/character-07.webp": {
    "width": 1248,
    "height": 1600,
    "bytes": 1567740,
    "sha256": "ff3673eddda27798c75b2848cdc40e9e6768b6146bcac13e3fb7733a6c1bea88",
    "variants": [
      {
        "src": "/characters/responsive/character-07-96.webp",
        "width": 96,
        "height": 123,
        "bytes": 3600
      },
      {
        "src": "/characters/responsive/character-07-320.webp",
        "width": 320,
        "height": 410,
        "bytes": 23412
      },
      {
        "src": "/characters/responsive/character-07-640.webp",
        "width": 640,
        "height": 821,
        "bytes": 64056
      },
      {
        "src": "/characters/responsive/character-07-960.webp",
        "width": 960,
        "height": 1231,
        "bytes": 109944
      }
    ]
  },
  "/characters/character-08.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1726472,
    "sha256": "0ddcae8a0ef019c0ed6d18965c564e7891ba9bee6b6c214ce3d16a6fa87257e6",
    "variants": [
      {
        "src": "/characters/responsive/character-08-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 3626
      },
      {
        "src": "/characters/responsive/character-08-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 22034
      },
      {
        "src": "/characters/responsive/character-08-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 60874
      },
      {
        "src": "/characters/responsive/character-08-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 109208
      }
    ]
  },
  "/characters/character-09.webp": {
    "width": 1248,
    "height": 1600,
    "bytes": 1542348,
    "sha256": "0918839dcf986b06454c6c96597a683ef72e6a4545de6738235a3a0117605914",
    "variants": [
      {
        "src": "/characters/responsive/character-09-96.webp",
        "width": 96,
        "height": 123,
        "bytes": 3822
      },
      {
        "src": "/characters/responsive/character-09-320.webp",
        "width": 320,
        "height": 410,
        "bytes": 21160
      },
      {
        "src": "/characters/responsive/character-09-640.webp",
        "width": 640,
        "height": 821,
        "bytes": 55070
      },
      {
        "src": "/characters/responsive/character-09-960.webp",
        "width": 960,
        "height": 1231,
        "bytes": 94438
      }
    ]
  },
  "/characters/character-10.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 2298468,
    "sha256": "ac08353c29327b7e4c6c45dcfc0ae9206aedd5189dcbc135b7afffc06797e7b9",
    "variants": [
      {
        "src": "/characters/responsive/character-10-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 5948
      },
      {
        "src": "/characters/responsive/character-10-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 41728
      },
      {
        "src": "/characters/responsive/character-10-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 124186
      },
      {
        "src": "/characters/responsive/character-10-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 224882
      }
    ]
  },
  "/characters/character-11.webp": {
    "width": 1536,
    "height": 2048,
    "bytes": 3307370,
    "sha256": "41aec19ab1a2a05dd59f122ed3d1326ab2378504c6d34478c5ac7f2581c150b8",
    "variants": [
      {
        "src": "/characters/responsive/character-11-96.webp",
        "width": 96,
        "height": 128,
        "bytes": 5128
      },
      {
        "src": "/characters/responsive/character-11-320.webp",
        "width": 320,
        "height": 427,
        "bytes": 32550
      },
      {
        "src": "/characters/responsive/character-11-640.webp",
        "width": 640,
        "height": 853,
        "bytes": 93604
      },
      {
        "src": "/characters/responsive/character-11-960.webp",
        "width": 960,
        "height": 1280,
        "bytes": 173648
      }
    ]
  },
  "/characters/character-12.webp": {
    "width": 1536,
    "height": 2048,
    "bytes": 3276382,
    "sha256": "4502b6424b8311282589a9c4895b937942b79e5fc0c9e95585fd5d97f70f676f",
    "variants": [
      {
        "src": "/characters/responsive/character-12-96.webp",
        "width": 96,
        "height": 128,
        "bytes": 4098
      },
      {
        "src": "/characters/responsive/character-12-320.webp",
        "width": 320,
        "height": 427,
        "bytes": 25716
      },
      {
        "src": "/characters/responsive/character-12-640.webp",
        "width": 640,
        "height": 853,
        "bytes": 73432
      },
      {
        "src": "/characters/responsive/character-12-960.webp",
        "width": 960,
        "height": 1280,
        "bytes": 138096
      }
    ]
  },
  "/characters/character-13.webp": {
    "width": 1536,
    "height": 2048,
    "bytes": 3238738,
    "sha256": "ba1a710870a899071ef4434d962ab5f6f0421284561cd4ea15c88ae097765bdc",
    "variants": [
      {
        "src": "/characters/responsive/character-13-96.webp",
        "width": 96,
        "height": 128,
        "bytes": 4274
      },
      {
        "src": "/characters/responsive/character-13-320.webp",
        "width": 320,
        "height": 427,
        "bytes": 28354
      },
      {
        "src": "/characters/responsive/character-13-640.webp",
        "width": 640,
        "height": 853,
        "bytes": 81676
      },
      {
        "src": "/characters/responsive/character-13-960.webp",
        "width": 960,
        "height": 1280,
        "bytes": 156292
      }
    ]
  },
  "/characters/character-14.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1947250,
    "sha256": "1c43e61a844f0d3fa1e2a76c148ea6fb70ce1a43d5af6e0d7645ceb52ff83f94",
    "variants": [
      {
        "src": "/characters/responsive/character-14-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 4140
      },
      {
        "src": "/characters/responsive/character-14-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 25926
      },
      {
        "src": "/characters/responsive/character-14-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 75320
      },
      {
        "src": "/characters/responsive/character-14-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 137026
      }
    ]
  },
  "/characters/character-15.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1712234,
    "sha256": "9640b374c7d822a8816c9df9c96c1e8bedf145bcc0de2a76c415af8ee653b84d",
    "variants": [
      {
        "src": "/characters/responsive/character-15-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 5174
      },
      {
        "src": "/characters/responsive/character-15-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 32632
      },
      {
        "src": "/characters/responsive/character-15-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 87182
      },
      {
        "src": "/characters/responsive/character-15-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 145718
      }
    ]
  },
  "/characters/character-16.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1674272,
    "sha256": "305af78be7e8dedd6159a789ac0b6ed1aa68fe4cffa50631e742b4dbf3835e97",
    "variants": [
      {
        "src": "/characters/responsive/character-16-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 5300
      },
      {
        "src": "/characters/responsive/character-16-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 34756
      },
      {
        "src": "/characters/responsive/character-16-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 96272
      },
      {
        "src": "/characters/responsive/character-16-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 163380
      }
    ]
  },
  "/characters/character-17.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1466622,
    "sha256": "baa3fd6823fa1fa4fe4923417f5bf7b5586813daf7f9f63909dc9f4a9794442c",
    "variants": [
      {
        "src": "/characters/responsive/character-17-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 4552
      },
      {
        "src": "/characters/responsive/character-17-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 27978
      },
      {
        "src": "/characters/responsive/character-17-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 72890
      },
      {
        "src": "/characters/responsive/character-17-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 122222
      }
    ]
  },
  "/characters/character-18.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1789428,
    "sha256": "66bb7d90210e68dd98aff05cafaf70d08b6f7b03b7b8c23bd5611cf462df60a7",
    "variants": [
      {
        "src": "/characters/responsive/character-18-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 5962
      },
      {
        "src": "/characters/responsive/character-18-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 40598
      },
      {
        "src": "/characters/responsive/character-18-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 111672
      },
      {
        "src": "/characters/responsive/character-18-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 190442
      }
    ]
  },
  "/characters/character-19.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1870614,
    "sha256": "f1052c0880c5eec08ea5c59f30b30fde420f479e86d9783468d87d909a7820ec",
    "variants": [
      {
        "src": "/characters/responsive/character-19-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 5666
      },
      {
        "src": "/characters/responsive/character-19-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 38596
      },
      {
        "src": "/characters/responsive/character-19-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 103394
      },
      {
        "src": "/characters/responsive/character-19-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 180232
      }
    ]
  },
  "/characters/character-20.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1737020,
    "sha256": "eb49373dd034c49e1331ff4a851f67f054e827c64bd28db9c539a35de98fb575",
    "variants": [
      {
        "src": "/characters/responsive/character-20-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 5252
      },
      {
        "src": "/characters/responsive/character-20-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 33406
      },
      {
        "src": "/characters/responsive/character-20-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 88016
      },
      {
        "src": "/characters/responsive/character-20-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 146820
      }
    ]
  },
  "/characters/character-21.webp": {
    "width": 768,
    "height": 1280,
    "bytes": 1078608,
    "sha256": "497e266935b427214aefc2675e67207477fa23d5911d9dba9bb2aedb90afd7b0",
    "variants": [
      {
        "src": "/characters/responsive/character-21-96.webp",
        "width": 96,
        "height": 160,
        "bytes": 6232
      },
      {
        "src": "/characters/responsive/character-21-320.webp",
        "width": 320,
        "height": 533,
        "bytes": 39270
      },
      {
        "src": "/characters/responsive/character-21-640.webp",
        "width": 640,
        "height": 1067,
        "bytes": 101896
      }
    ]
  },
  "/characters/character-22.webp": {
    "width": 768,
    "height": 1280,
    "bytes": 1070016,
    "sha256": "edc9de2f8871b94d806b7fdb74393b3d26414b64770233be1efb55916d94c9ad",
    "variants": [
      {
        "src": "/characters/responsive/character-22-96.webp",
        "width": 96,
        "height": 160,
        "bytes": 6580
      },
      {
        "src": "/characters/responsive/character-22-320.webp",
        "width": 320,
        "height": 533,
        "bytes": 41878
      },
      {
        "src": "/characters/responsive/character-22-640.webp",
        "width": 640,
        "height": 1067,
        "bytes": 102090
      }
    ]
  },
  "/characters/character-23.webp": {
    "width": 768,
    "height": 1280,
    "bytes": 1077970,
    "sha256": "407616e1ff7a827a033c70cd859abe620fd2387321239bd7822390386dfc8ffa",
    "variants": [
      {
        "src": "/characters/responsive/character-23-96.webp",
        "width": 96,
        "height": 160,
        "bytes": 6046
      },
      {
        "src": "/characters/responsive/character-23-320.webp",
        "width": 320,
        "height": 533,
        "bytes": 39008
      },
      {
        "src": "/characters/responsive/character-23-640.webp",
        "width": 640,
        "height": 1067,
        "bytes": 96494
      }
    ]
  },
  "/characters/character-24.webp": {
    "width": 768,
    "height": 1280,
    "bytes": 1196696,
    "sha256": "1eac5d114a62f4291b3b5ec5513dc5afd5ceed213097e31141b67c0665bf7810",
    "variants": [
      {
        "src": "/characters/responsive/character-24-96.webp",
        "width": 96,
        "height": 160,
        "bytes": 6198
      },
      {
        "src": "/characters/responsive/character-24-320.webp",
        "width": 320,
        "height": 533,
        "bytes": 45952
      },
      {
        "src": "/characters/responsive/character-24-640.webp",
        "width": 640,
        "height": 1067,
        "bytes": 118562
      }
    ]
  },
  "/characters/character-25.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1629630,
    "sha256": "b041bc09ac49041e25c0865ec7a1ef2438d1f31e61b48b8c47dd06c1e19aabdc",
    "variants": [
      {
        "src": "/characters/responsive/character-25-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 4580
      },
      {
        "src": "/characters/responsive/character-25-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 26052
      },
      {
        "src": "/characters/responsive/character-25-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 64494
      },
      {
        "src": "/characters/responsive/character-25-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 106656
      }
    ]
  },
  "/characters/character-26.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 1242652,
    "sha256": "e17f5b6b7d750b20f6f62ed78f42be341ce018dec0a3cda2677f73414d8a7e9d",
    "variants": [
      {
        "src": "/characters/responsive/character-26-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 2882
      },
      {
        "src": "/characters/responsive/character-26-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 15638
      },
      {
        "src": "/characters/responsive/character-26-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 40718
      },
      {
        "src": "/characters/responsive/character-26-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 72074
      }
    ]
  },
  "/characters/character-28.webp": {
    "width": 768,
    "height": 1280,
    "bytes": 863288,
    "sha256": "d41c568ca0a154743e3ef7c756bae88669042827b7b6400cbe84e52458cc5ff5",
    "variants": [
      {
        "src": "/characters/responsive/character-28-96.webp",
        "width": 96,
        "height": 160,
        "bytes": 5244
      },
      {
        "src": "/characters/responsive/character-28-320.webp",
        "width": 320,
        "height": 533,
        "bytes": 34358
      },
      {
        "src": "/characters/responsive/character-28-640.webp",
        "width": 640,
        "height": 1067,
        "bytes": 83056
      }
    ]
  },
  "/characters/character-29.webp": {
    "width": 1104,
    "height": 1824,
    "bytes": 2179852,
    "sha256": "0b9268e2ae55ad3d9ddbb223a8453b064ff65f2628f7c6477a9a03a65ba27342",
    "variants": [
      {
        "src": "/characters/responsive/character-29-96.webp",
        "width": 96,
        "height": 159,
        "bytes": 6078
      },
      {
        "src": "/characters/responsive/character-29-320.webp",
        "width": 320,
        "height": 529,
        "bytes": 47794
      },
      {
        "src": "/characters/responsive/character-29-640.webp",
        "width": 640,
        "height": 1057,
        "bytes": 142516
      },
      {
        "src": "/characters/responsive/character-29-960.webp",
        "width": 960,
        "height": 1586,
        "bytes": 244648
      }
    ]
  }
} as const;
