const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');
const root=path.resolve(__dirname,'..');
const sql=new DatabaseSync(':memory:');
for(const f of fs.readdirSync(root+'/drizzle').filter(f=>f.endsWith('.sql')).sort()) sql.exec(fs.readFileSync(root+'/drizzle/'+f,'utf8'));
let owner='test-alice'; const objects=new Map();
let afterQuery=null;
class Query { constructor(text,args=[]){this.text=text;this.args=args;} bind(...a){return new Query(this.text,a)} async first(){const value=sql.prepare(this.text).get(...this.args)||null; if(afterQuery) await afterQuery(this.text,this.args,value);return value} async all(){const results=sql.prepare(this.text).all(...this.args);if(afterQuery)await afterQuery(this.text,this.args,results);return {results}} async run(){const r=sql.prepare(this.text).run(...this.args);if(afterQuery)await afterQuery(this.text,this.args,r);return {meta:{changes:Number(r.changes)}}}}
const db={prepare:t=>new Query(t),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e}}};
const env={DB:db,BUCKET:{put:async(k,b,o)=>objects.set(k,{body:b,options:o}),get:async k=>objects.get(k),delete:async k=>objects.delete(k)}};
const cache={};
function load(file){file=path.resolve(file);if(!fs.existsSync(file)&&fs.existsSync(file+'x'))file+='x';if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const req=name=>{if(name==='react'&&(file.endsWith('/status-panel.tsx')||file.endsWith('/memory-panel.tsx')))return fakeReact;if(name==='cloudflare:workers')return {env};if(name.endsWith('chatgpt-auth'))return {getChatGPTUser:async()=>owner?{userId:owner,email:owner+'@example.test'}:null};if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+'.ts');return require(require.resolve(name,{paths:[root]}))};vm.runInThisContext('(function(require,module,exports){'+code+'\n})',{filename:file})(req,module,module.exports);return module.exports;}
const api=load(root+'/app/api/app/route.ts'),media=load(root+'/app/api/media/[id]/route.ts'),memory=load(root+'/app/lib/memory.ts'),data=load(root+'/app/lib/data.ts');
const req=(suffix='',body)=>new Request('https://test.example/api/app'+suffix,body?{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://test.example'},body:JSON.stringify(body)}:{});
async function post(action,body={}){const r=await api.POST(req('',{action,...body}));return {status:r.status,data:await r.json()}}
async function get(q=''){const r=await api.GET(req(q));return {status:r.status,data:await r.json()}}
async function image(id,query=''){const r=await media.GET(new Request('https://test.example/api/media/'+encodeURIComponent(id)+query),{params:Promise.resolve({id})});return r}

(async()=>{
const w={...data.blankWork(),title:'Status review',rating:'all',secret:'CREATOR_PRIVATE_SENTINEL',characters:[{name:'Adult',age:25,role:'friend',personality:'friendly'}],openings:[{title:'A',text:'opening',suggestions:[]}],cover:data.covers[1]};
let r=await post('saveWork',{work:w});assert.equal(r.status,200);const saved=r.data.work;let s=await post('startChat',{workId:saved.id});const sid=s.data.id;s=await post('startChat',{workId:saved.id});const sid2=s.data.id;
r=await get('?session='+sid);assert.equal(r.status,200);assert.equal(r.data.status.source,'manual');assert.equal(r.data.status.data.inner_thought,'');assert.equal(JSON.stringify(r.data.status).includes('CREATOR_PRIVATE_SENTINEL'),false);
const fields=load(root+'/app/lib/status-fields.ts');
r=await post('saveStatus',{sessionId:sid,revision:0,data:{place:'ALICE_PRIVATE_PLACE',inner_thought:'ALICE_PRIVATE_THOUGHT',secret:'NOT_ALLOWED',notes:'NOT_ALLOWED',x:'NOT_ALLOWED',emotion:'x'.repeat(400)},template:[{key:'place',label:'<script>alert(1)</script>',enabled:true,value:'DO_NOT_EXPORT',secret:'DO_NOT_EXPORT'},{key:'inner_thought',label:'Thought',enabled:false}]});assert.equal(r.status,200);assert.equal(r.data.status.revision,1);assert.equal(r.data.status.data.emotion.length,300);assert.equal(r.data.status.data.secret,undefined);assert.equal(r.data.status.data.inner_thought,'ALICE_PRIVATE_THOUGHT');assert.equal(r.data.status.template.length,13);
assert.equal(JSON.stringify(r.data.status.template).includes('DO_NOT_EXPORT'),false);assert.equal(JSON.stringify(r.data.status.template).includes('ALICE_PRIVATE'),false);const stored=r.data.status;
r=await post('saveStatus',{sessionId:sid,revision:0,data:{place:'stale'}});assert.equal(r.status,409);
r=await get('?session='+sid2);assert.equal(r.data.status.data.place,'');assert.equal(r.data.status.data.inner_thought,'');
owner='test-bob';assert.equal((await get('?session='+sid)).status,404);assert.equal((await post('saveStatus',{sessionId:sid,revision:1,data:{place:'intrusion'}})).status,404);owner='test-alice';
const context=await memory.compileProviderContext(owner,sid,saved);assert.equal(context.readerContext.storyStatus.inner_thought,'ALICE_PRIVATE_THOUGHT');assert.equal(context.creatorInstructions.privateSetting,'CREATOR_PRIVATE_SENTINEL');assert.equal(JSON.stringify(context.readerContext).includes('CREATOR_PRIVATE_SENTINEL'),false);
const secondContext=await memory.compileProviderContext(owner,sid2,saved);assert.equal(secondContext.readerContext.storyStatus.inner_thought,'');
const template=fields.normalizeStatusTemplate([{key:'place',label:'Place',enabled:true,value:'ALICE_PRIVATE_PLACE',notes:'ALICE_NOTE',inner_thought:'ALICE_PRIVATE_THOUGHT',secret:'CREATOR_PRIVATE_SENTINEL'}]);const exported=JSON.stringify({schema:'onseo.status-template.v1',fields:template});assert.equal(/PRIVATE|ALICE_NOTE/.test(exported),false);assert.equal(template.every(t=>Object.keys(t).sort().join(',')==='enabled,key,label'),true);
console.log('PASS new status endpoint owner/session isolation, CAS revisions, 13-field schema, truncation, no automatic secret mapping, scoped provider context and template-only export shape.');
// Hook-level regression: a refreshed prop revision must not authorize stale local editor values.
let hookIndex=0;const hookState=[],effects=[];global.fakeReact={useRef(initial){const i=hookIndex++;if(!(i in hookState))hookState[i]={current:initial};return hookState[i];},useState(initial){const i=hookIndex++;if(!(i in hookState))hookState[i]=typeof initial==='function'?initial():initial;return [hookState[i],v=>hookState[i]=typeof v==='function'?v(hookState[i]):v];},useEffect(effect,deps){const i=hookIndex++,old=hookState[i];if(!old||deps.some((d,j)=>d!==old[j])){hookState[i]=deps;effects.push(effect)}}};
const Panel=load(root+'/app/status-panel.tsx').default;let props={sessionId:sid,template:undefined,status:{data:fields.cleanStatusData({}),revision:0},onChange:()=>{},onError:()=>{}};
const render=()=>{hookIndex=0;let tree=Panel(props);while(effects.length)effects.shift()();hookIndex=0;tree=Panel(props);while(effects.length)effects.shift()();return tree};const flatten=e=>!e||typeof e!=='object'?[]:[e,...(Array.isArray(e.props?.children)?e.props.children:[e.props?.children]).flat(Infinity).flatMap(flatten)];const labels=e=>{if(typeof e==='string')return e;if(!e||typeof e!=='object')return '';return (Array.isArray(e.props?.children)?e.props.children:[e.props?.children]).flat(Infinity).map(labels).join('')};
render();props={...props,status:stored};let tree=render();let button=flatten(tree).find(e=>e.type==='button'&&labels(e)==='값 입력');button.props.onClick();tree=render();let input=flatten(tree).find(e=>e.type==='input');input.props.onChange({target:{value:'one new field'}});tree=render();
let sent;const oldFetch=global.fetch;global.fetch=async(_url,options)=>{sent=JSON.parse(options.body);return {ok:true,json:async()=>({status:stored})}};button=flatten(tree).find(e=>e.type==='button'&&labels(e).includes('상태창 저장'));await button.props.onClick();assert.equal(sent.revision,1);assert.equal(sent.data.inner_thought,'ALICE_PRIVATE_THOUGHT');console.log('PASS pristine editor refresh syncs matching status values and revision.');
// When editing has already begun, newer props must not advance the editor revision.
hookState.length=0;effects.length=0;props={...props,status:{data:fields.cleanStatusData({}),revision:0}};tree=render();button=flatten(tree).find(e=>e.type==='button'&&labels(e)==='값 입력');button.props.onClick();tree=render();input=flatten(tree).find(e=>e.type==='input');input.props.onChange({target:{value:'unsaved local'}});tree=render();props={...props,status:stored};tree=render();button=flatten(tree).find(e=>e.type==='button'&&labels(e).includes('상태창 저장'));await button.props.onClick();assert.equal(sent.revision,0);assert.equal(sent.data.inner_thought,'');global.fetch=oldFetch;console.log('PASS active editor keeps its old revision so stale save returns409 rather than overwriting newer status.');
// Exercise the actual export/import callbacks with DOM and download mocked locally.
hookState.length=0;hookIndex=0;const Editor=load(root+'/app/status-panel.tsx').StatusTemplateEditor;const editor=Editor({template:[...template.map(f=>({...f,value:'ALICE_PRIVATE_PLACE',notes:'ALICE_NOTE'}))],onChange:()=>{}});const transferElement=flatten(editor).find(e=>typeof e.type==='function'&&e.type.name==='TemplateTransfer');let imported;hookIndex=0;const transfer=transferElement.type({...transferElement.props,onImport:x=>imported=x});
const oldDocument=global.document,oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL;let downloadBlob,clicked=false;global.document={createElement(){return {click(){clicked=true}}}};URL.createObjectURL=blob=>{downloadBlob=blob;return 'blob:mock'};URL.revokeObjectURL=()=>{};const exportButton=flatten(transfer).find(e=>e.type==='button'&&labels(e).includes('내보내기'));exportButton.props.onClick();assert.equal(clicked,true);const download=JSON.parse(await downloadBlob.text());assert.equal(download.schema,'onseo.status-template.v1');assert.deepEqual(Object.keys(download).sort(),['fields','schema']);assert.equal(JSON.stringify(download).includes('ALICE_'),false);assert.equal(download.fields.every(f=>Object.keys(f).sort().join(',')==='enabled,key,label'),true);
const importer=flatten(transfer).find(e=>e.type==='input'&&e.props.type==='file');await importer.props.onChange({target:{files:[{size:100,text:async()=>JSON.stringify({schema:'onseo.status-template.v1',fields:[{key:'place',label:'<script>alert(1)</script>',enabled:true,value:'SHOULD_NOT_IMPORT'}],values:{inner_thought:'SHOULD_NOT_IMPORT'},secret:'SHOULD_NOT_IMPORT',notes:'SHOULD_NOT_IMPORT'})}]}});assert.equal(JSON.stringify(imported).includes('SHOULD_NOT_IMPORT'),false);global.document=oldDocument;URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke;
const React=require(require.resolve('react',{paths:[root]})),Server=require(require.resolve('react-dom/server',{paths:[root]}));hookState.length=0;hookIndex=0;const rendered=Server.renderToStaticMarkup(Panel({...props,status:{data:fields.cleanStatusData({place:'<img src=x onerror=alert(1)>'}),template:imported,revision:1}}));assert.equal(rendered.includes('<script>'),false);assert.equal(rendered.includes('<img src=x'),false);assert.equal(rendered.includes('&lt;script&gt;'),true);assert.equal(rendered.includes('&lt;img'),true);
console.log('PASS actual template export/import handlers exclude live/unknown values; status values and labels render escaped, not raw HTML.');
// Saving a summary must not discard an independently edited persona draft.
hookState.length=0;effects.length=0;const MemoryPanel=load(root+'/app/memory-panel.tsx').default;const memorySettings={manual:'',user_notes:'',persona:'saved persona',interval:10,enabled:1,revision:1};const memoryProps={sessionId:sid,memory:{settings:memorySettings,summaries:[{id:'summary',from_turn:1,to_turn:10,content:'summary',status:'manual',pinned:0,revision:1}]},onChange:()=>{},onError:()=>{}};const renderMemory=()=>{hookIndex=0;return MemoryPanel(memoryProps)};
let mtree=renderMemory(),persona=flatten(mtree).find(e=>typeof e.type==='function'&&e.type.name==='PersonaBuilder');persona.props.onChange('UNSAVED_PERSONA_DRAFT');mtree=renderMemory();global.fetch=async()=>({ok:true,json:async()=>({memory:memoryProps.memory})});const summaryComponent=flatten(mtree).find(e=>typeof e.type==='function'&&e.type.name==='Summary');await summaryComponent.props.onSave('edited summary',true);global.fetch=oldFetch;mtree=renderMemory();persona=flatten(mtree).find(e=>typeof e.type==='function'&&e.type.name==='PersonaBuilder');assert.equal(persona.props.value,'UNSAVED_PERSONA_DRAFT');console.log('PERSONA_AFTER_SUMMARY_SAVE',JSON.stringify({persona:persona.props.value,draftPreserved:persona.props.value==='UNSAVED_PERSONA_DRAFT'}));
console.log('DONE new-surface-only tests; no real user data, browser or providers.');
})().catch(e=>{console.error(e);process.exitCode=1});
