const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript'),{DatabaseSync}=require('node:sqlite');
const root=path.resolve(__dirname,'..'),sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync(root+'/drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync(root+'/drizzle/'+f,'utf8'));
class Q{constructor(q,a=[]){this.q=q;this.a=a}bind(...a){return new Q(this.q,a)}async first(){return sql.prepare(this.q).get(...this.a)||null}async all(){return {results:sql.prepare(this.q).all(...this.a)}}async run(){return {meta:{changes:Number(sql.prepare(this.q).run(...this.a).changes)}}}}
const db={prepare:q=>new Q(q),batch:async qs=>{sql.exec('BEGIN');try{const r=[];for(const q of qs)r.push(await q.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
const env={DB:db,KG_ENABLED:'true',KG_PAYMENT_MODE:'live',KG_LIVE_CONFIRMED:'true',KG_MID:'TESTMID001',KG_SIGN_KEY:'unit-test-key',PAYMENT_ORIGIN:'https://test.example',KG_PACKS_JSON:JSON.stringify([{id:'basic',name:'unit test',units:120,price:1000}])};let owner='alice',network=0,approve;
const cache={};function load(f){f=path.resolve(f);if(cache[f])return cache[f].exports;const m={exports:{}};cache[f]=m;const req=n=>n==='cloudflare:workers'?{env}:n.endsWith('chatgpt-auth')?{getChatGPTUser:async()=>({userId:owner})}:n.startsWith('.')?load(path.resolve(path.dirname(f),n)+'.ts'):require(n);const code=ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInThisContext('(function(require,module,exports){'+code+'})')(req,m,m.exports);return m.exports}
const api=load(root+'/app/api/payments/route.ts'),callback=load(root+'/app/api/payments/return/route.ts'),config=load(root+'/app/lib/payment-config.ts');
const request=(data,origin='https://test.example')=>new Request('https://test.example/api/payments',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(data)});
const buyer={packId:'basic',requestId:'12345678-1234-1234-1234-123456789abc',confirm:true,name:'Test',phone:'01000000000',email:'test@example.com'};
async function cb(o,changes={}){return callback.POST(new Request('https://test.example/api/payments/return?order='+o.id+'&token='+o.token,{method:'POST',body:new URLSearchParams({resultCode:'0000',mid:o.mid,orderNumber:o.id,authToken:'test-token',idc_name:'fc',authUrl:'https://fcstdpay.inicis.com/api/payAuth',netCancelUrl:'https://fcstdpay.inicis.com/api/netCancel',...changes})}))}
(async()=>{
assert.equal((await api.POST(request(buyer,'https://evil.example'))).status,403);env.KG_ENABLED='false';assert.equal((await api.POST(request(buyer))).status,503);env.KG_ENABLED='true';
let r=await api.POST(request({...buyer,price:1,units:999999}));assert.equal(r.status,200);let j=await r.json();assert.equal(j.fields.price,'1000');assert(!JSON.stringify(j).includes(env.KG_SIGN_KEY));assert.equal(j.fields.signature,await config.sha256(`oid=${j.orderId}&price=1000&timestamp=${j.fields.timestamp}`));
let order=sql.prepare('SELECT * FROM payment_orders').get();assert.equal((await(await api.POST(request(buyer))).json()).orderId,order.id);owner='bob';assert.equal((await api.GET(new Request('https://test.example/api/payments?order='+order.id))).status,404);owner='alice';
for(const u of ['https://evil.example/api/payAuth','https://fcstdpay.inicis.com.evil.example/api/payAuth','http://fcstdpay.inicis.com/api/payAuth','https://fcstdpay.inicis.com/api/payAuth?redirect=evil'])assert.throws(()=>config.approvalURL(u,'approve'));
const oldFetch=global.fetch;global.fetch=async url=>{network++;return Response.json(String(url).endsWith('/netCancel')?{resultCode:'0000'}:approve)};
await cb(order,{idc_name:'ks'});assert.equal(network,0);assert.equal(sql.prepare('SELECT status FROM payment_orders').get().status,'pending');
approve={resultCode:'0000',mid:order.mid,MOID:order.id,TotPrice:'1000',tid:'TEST_TRANSACTION_1'};await cb(order);await cb(order);assert.equal(network,1);assert.equal(sql.prepare('SELECT SUM(delta) n FROM ledger').get().n,120);assert.equal(sql.prepare('SELECT status FROM payment_orders').get().status,'paid');
const next={...buyer,requestId:crypto.randomUUID()};await api.POST(request(next));order=sql.prepare('SELECT * FROM payment_orders WHERE request_id=?').get(next.requestId);approve={...approve,MOID:order.id,TotPrice:'1',tid:'TEST_TRANSACTION_2'};await cb(order);assert.equal(sql.prepare('SELECT status FROM payment_orders WHERE id=?').get(order.id).status,'cancelled');assert.equal(sql.prepare('SELECT SUM(delta) n FROM ledger').get().n,120);
global.fetch=oldFetch;console.log('PASS KG: disabled gate, origin, server prices, signatures, idempotency, ownership, URL/IDC validation, single credit, mismatch net-cancel. No external requests or real payments.');
})().catch(e=>{console.error(e);process.exitCode=1});
