import assert from 'node:assert/strict';
const base=process.env.QA_BASE||'http://127.0.0.1:5182',owner='runtime-'+Date.now();
const headers=(o=owner)=>({'oai-authenticated-user-id':o,'oai-authenticated-user-email':o+'@test.invalid','Content-Type':'application/json'});
async function call(action,data={},o=owner){const r=await fetch(base+'/api/app',{method:action?'POST':'GET',headers:headers(o),body:action?JSON.stringify({action,...data}):undefined});return {status:r.status,...await r.json()};}
async function read(sid,o=owner){const r=await fetch(base+'/api/app?session='+sid,{headers:headers(o)});return {status:r.status,...await r.json()};}
assert.equal((await fetch(base+'/api/app')).status,401);assert.deepEqual((await call()).assets,[]);assert.equal((await call('startChat',{workId:'sample-silver'})).status,403);assert.equal((await call('startChat',{workId:'sample-sori'})).status,200);await call('declareAdult',{confirm:true});assert.equal((await call('startChat',{workId:'sample-silver'})).status,200);
const w={title:'Runtime work',rating:'all',status:'catalog',desc:'test',world:'test',secret:'PRIVATE_SENTINEL',responseRules:{ooc:'PRIVATE_RULE',style:'calm',perspective:'third',length:'long'},tag:'미스터리',characters:[{name:'Guide',age:25,role:'guide',personality:'calm'}],openings:[{title:'A',text:'*walks* hello',suggestions:[]},{title:'B',text:'another opening',suggestions:[]}],cover:'/characters/character-02.webp'};
let j=await call('saveWork',{work:w});assert.equal(j.status,200);const work=j.work;assert.equal(JSON.stringify(await call()).includes('PRIVATE_SENTINEL'),false);assert.equal((await call('saveWork',{work:{...work,title:'intruder'}},owner+'-other')).status,403);
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=';let assets=[];for(const [i,condition] of [{type:'messages',value:2},{type:'opening',value:'B'},{type:'keyword',value:'unlock'}].entries()){j=await call('saveCollectible',{workId:work.id,characterId:work.characters[0].id,title:'reward'+i,condition,requestId:'asset'+i,file:png});assert.equal(j.status,200);assets=j.assets;}
const countAsset=assets.find(a=>a.title==='reward0');const media=()=>fetch(base+'/api/media/'+encodeURIComponent(countAsset.id),{headers:headers()});assert.equal((await media()).status,403);
j=await call('startChat',{workId:work.id,opening:0});const sid=j.id;assert.equal((await read(sid,owner+'-other')).status,404);assert.equal(JSON.stringify(await read(sid)).includes('PRIVATE_SENTINEL'),false);
await call('saveMemory',{sessionId:sid,manual:'durable manual',userNotes:'note',persona:'이름: 민',interval:2,enabled:true,revision:0});assert.equal((await call('saveMemory',{sessionId:sid,manual:'stale',interval:2,enabled:true,revision:0})).status,409);
await call('message',{sessionId:sid,content:'one',requestId:'one'});await call('message',{sessionId:sid,content:'retry',requestId:'one'});assert.equal((await read(sid)).messages.length,3);assert.equal((await media()).status,403);assert.equal((await call('message',{sessionId:sid,content:'bad',requestId:'one:reply'})).status,400);
await call('message',{sessionId:sid,content:'UNLOCK',requestId:'two'});assert.equal((await media()).status,200);j=await read(sid);assert.equal(j.memory.settings.manual,'durable manual');assert.equal(j.memory.summaries.length,1);assert.equal(j.memory.summaries[0].status,'provider_required');const summary=j.memory.summaries[0];await call('saveSummary',{sessionId:sid,id:summary.id,revision:0,content:'manual summary',pinned:true});j=await read(sid);assert.equal(j.memory.summaries[0].pinned,1);assert.equal(j.memory.summaries[0].status,'manual');
j=await call('saveStatus',{sessionId:sid,revision:0,data:{place:'library',inner_thought:'manual thought',secret:'must not persist'},template:[{key:'place',label:'현재 위치',enabled:true},{key:'inner_thought',label:'속마음',enabled:true}]});assert.equal(j.status.revision,1);j=await read(sid);assert.equal(j.status.data.place,'library');assert.equal(j.status.data.secret,undefined);assert.equal(j.status.template[0].label,'현재 위치');assert.equal((await call('saveStatus',{sessionId:sid,revision:0,data:{place:'stale'}})).status,409);assert.equal((await call('saveStatus',{sessionId:sid,revision:1,data:{place:'intrusion'}},owner+'-other')).status,404);
j=await call();assert.equal(j.assets.length,2);assert.equal(j.activity.find(a=>a.work_id===work.id).turns,2);await call('startChat',{workId:work.id,opening:1});assert.equal((await call()).assets.length,3);assert.equal((await call(null,{},owner+'-other')).assets.length,0);await call('archiveSession',{id:sid});assert.ok(!(await call()).activity.some(a=>a.work_id===work.id));
const page=await fetch(base+'/works/'+work.id,{headers:headers()});assert.equal(page.status,200);assert.ok((await page.text()).includes('top-navigation'));
console.log('PASS real local Worker/D1/R2: auth/age, tenant ownership, saved conditions for count/opening/keyword, locked media then grants, retries, memory manual/pin/schedule/revisions, status template/values, private settings exclusion, recommendation history and archived-session exclusion, deep-link server route.');
